export type TermsSection = {
  heading?: string;
  paragraphs: string[];
};

export const termsOfUseIntro: string[] = [
  `Welcome to www.eilite.com (collectively, the "Site"), an Internet property of Eilite Systems, Inc. ("Eilite™," "we," "us" or "our"). The following Eilite™ Terms of Use ("Terms of Use") shall incorporate and govern the Eilite™ Privacy Policy ("Privacy Policy"), the Eilite™ Lead Sales Agreement ("Lead Agreement") and any and all other applicable Eilite™ operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time (collectively, the "Agreement").`,
  `THESE TERMS CONTAIN A BINDING ARBITRATION CLAUSE THAT REQUIRES YOU TO SUBMIT ANY DISPUTE YOU HAVE WITH Eilite TO ARBITRATION.`,
  `You agree, without limitation or qualification, to be bound by the terms of the Agreement in its entirety when you: (a) access the Site; (b) utilize the Eilite™ search directory ("Directory") in order to obtain search listings and related information (collectively, "Listings") regarding a variety of home improvement and gardening businesses, professionals, venues, products and/or services (collectively, "Contractor Offerings") as offered and provided by the y contractors, business entities and professionals featured on the Site (collectively, "Third Party Contractors"); (c) access articles, discussions, Site User (as defined below) feedback and/or other content on the Site (collectively, "Content"); (d) utilize the Site's many interactive features designed to facilitate interaction between you, Eilite™, other Site Users and "Contributors" (collectively, "Participants") participating in the blogs, comment sections, reviews and other interactive features located in designated areas of the Site ("Interactive Services"); (e) register to submit a free Listing of your Contractor Offerings; (f) agree to waive any right to participate in a class action against eilite; (g) access links to our social media pages on Third Party social media websites, including, but not limited to, Facebook®, Google+®, TikTok®, Instagram®, LinkedIn®, Youtube®, Glassdoor® and Pinterest® ("Social Media Pages,") and together with the Site, Directory, Listings, Content, Interactive Services, Enhanced Services and Social Media Pages, the "Eilite™ Offerings"). Please review the Agreement carefully. If you do not agree to the terms of the Agreement in their entirety, you are not authorized to use the Eilite™ Offerings in any manner or form.`,
  `You understand and agree that Eilite™ shall not be liable to you, any other Site User or any third party for any claim in connection with your use of, or inability to use, the Eilite™ Offerings. Eilite™ disclaims any and all liability for any loss, damage, or injury based on Content, Contractor Offerings or other products, services and/or information directly or indirectly obtained through the Eilite™ Offerings. You understand and agree that Eilite™ is not responsible or liable in any manner whatsoever for any dispute between you and any Site User.`,
  `Facebook® is a registered trademark of Facebook, Inc. ("Facebook"). Google+® is a registered trademark of Google, Inc. ("Google"). Twitter® is a registered trademark of Twitter, Inc. ("Twitter"). Please be advised that Eilite™ is not in any way affiliated with Facebook, Google or Twitter, and the Eilite™ Offerings are not endorsed, administered or sponsored by Facebook, Google or Twitter.`,
];

export const termsOfUseSections: TermsSection[] = [
  {
    heading: "Scope/Modification of Agreement/Termination",
    paragraphs: [
      `The Agreement constitutes the entire and only agreement between you and Eilite™ with respect to your use of the Eilite™ Offerings, and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to the Site. We may amend the Agreement from time to time in our sole discretion, without specific notice to you; provided, however, that: (a) any amendment or modification to the arbitration provisions, prohibition on class action provisions or any other provisions applicable to dispute resolution (collectively, "Dispute Resolution Provisions") shall not apply to any disputes incurred prior to the applicable amendment or modification; and (b) any amendment or modification to pricing and/or billing provisions ("Billing Provisions") shall not apply to any charges incurred prior to the applicable amendment or modification. The latest Terms of Use and Privacy Policy will be posted on the Site, and you should review same prior to using the Eilite™ Offerings. By your continued use of the Eilite™ Offerings, you hereby agree to comply with, and be bound by, all of the terms and conditions contained within the Agreement effective at that time (other than with respect to disputes arising prior to the amendment or modification of the Dispute Resolution Provisions, or charges incurred prior to the amendment or modification of the Billing Provisions, which shall be governed by the Dispute Resolution Provisions and/or Billing Provisions then in effect at the time of the subject dispute or incurred charges, as applicable). Unless explicitly stated otherwise, any future offer(s) made available to you on the Site that augment(s) or otherwise enhance(s) the current features of the Eilite™ Offerings shall be subject to the Agreement.`,
      `Eilite™ reserves the right to terminate the Agreement, remove your Listings (if any) and terminate your access to the Eilite™ Offerings at any time in its sole discretion including, without limitation, where Eilite™ believes that you are: (i) violating any applicable law, rule or regulation; (ii) in breach of the Agreement; or (iii) otherwise acting in a manner that is detrimental to the interests of Eilite™ and/or other Site Users. If Eilite™ terminates the Agreement for any reason, Eilite™ shall have no liability or responsibility to you. You understand and agree that refusal to use the Eilite™ Offerings is your sole right and remedy with respect to any dispute that you may have with Eilite™. The Agreement only governs your use of the Eilite™ Offerings.`,
    ],
  },
  {
    heading: "Non-Endorsement: Site Content and Site Users",
    paragraphs: [
      `(a) Eilite™ does not sponsor, recommend or endorse: (i) any Third Party Contractors (including Advertisers) that are accessible by and through the Directory and/or Interactive Services; (ii) any Participants that are accessible by and through the Interactive Services; and/or (iii) any Site visitors ("Visitors") that are accessible by and through the Site and/or Interactive Services. The Site facilitates communication between Third Party Contractors, Participants, Visitors and potential users of associated Contractor Offerings. Some of the Third Party Contractors that are accessible by and through the Directory pay a fee for inclusion in the Directory.`,
      `(b) The Eilite™ Offerings contain comments, opinions, statements, feedback, submissions and other content (collectively, "Feedback"), Listings, Content, articles, advertisements, responses, statements, promises and other information (collectively, "Site Content") that is provided directly by Third Party Contractors, Participants, Visitors and any other parties that use the Site (collectively, "Site Users"). Please use caution and common sense when using the Site and Directory. You agree that Eilite™ shall have no obligation and incur no liability to you in connection with any Site Content and/or Feedback appearing in or through the Interactive Services. Eilite™ does not represent or warrant that the Site Content featured by and through the Site and/or Feedback posted through the Interactive Services is accurate, complete or appropriate. Eilite™ in no way endorses the Site Content made available by Site Users through the Interactive Services, Directory and/or any other Eilite™ Offerings. The Site Content and other information submitted or made available by Site Users is not verified or reviewed in any way before it appears on the Site or otherwise through the Eilite™ Offerings. Eilite™ does not warrant the validity or accuracy of any such Site Content. Each Site User shall be solely responsible for the Site Content posted by and through the Eilite™ Offerings. Eilite™ reserves the right to prohibit any conduct by Site Users or remove any Site Content from the Eilite™ Offerings at any time and for any reason, in Eilite's™ sole discretion. The reasons for removal may include where Eilite™ believes that the Site Content posted by a Site User is unsuitable for the Eilite™ Offerings for any reason including, without limitation, where: (i) the Site Content contains or links to material that could be considered unlawful, harmful, threatening, defamatory, obscene, harassing or otherwise objectionable; (ii) the Site Content contains or links to material that infringes upon the trademark, trade name, service mark, copyright, license, or other intellectual property or proprietary right of any third party; (iii) Eilite™ believes that a Site User is, at any time, conducting any commercial activity by and through the Site; and/or (iv) Eilite™ believes that a Site User is in violation of the Agreement including, without limitation, Section 12 below.`,
      `(c) Eilite™ does not involve itself in the agreements arrived at by and between Visitors and Third Party Contractors, or in the actual provision of Contractor Offerings in connection with the relationships created thereby. Therefore, Eilite™ does not make any representations regarding the competency, trustworthiness, honesty, integrity and/or behavior of either its Visitors or Third Party Contractors. Visitors, and not Eilite™, are solely responsible for assessing the competency, trustworthiness, honesty and integrity of all Third Party Contractors that such Visitors contact via the Directory.`,
    ],
  },
  {
    heading: "Requirements",
    paragraphs: [
      `The Eilite™ Offerings are available only to individuals who can enter into legally binding contracts under applicable law. The Eilite™ Offerings are not intended for use by individuals under eighteen (18) years of age (or the applicable age of majority, if greater than eighteen (18) years of age). If you are under eighteen (18) years of age (or the applicable age of majority, if greater than eighteen (18) years of age), you do not have permission to use and/or access the Eilite™ Offerings.`,
    ],
  },
  {
    heading: "Directory",
    paragraphs: [
      `Eilite™ provides Visitors with the opportunity to: (a) conduct searches for various Third Party Contractors; (b) view the Listings that match their Third Party Contractor search results; and (c) obtain contact information for such Third Party Contractors in order to contact them regarding their Contractor Offerings. Some of the Third Party Contractors that are accessible by and through the Directory pay a fee for inclusion in the Directory. Please be advised that Eilite™ does not itself provide any underlying products and/or services, and the ultimate terms and conditions of any Contractor Offerings will be determined by the applicable Third Party Contractors. To receive information regarding Third Party Contractors, you must first fully complete the registration forms located on the Site (collectively, the "Site Form"). The information that you must supply on the Site Form includes, but is not limited to: (i) your zip code; (ii) the category applicable to your inquiry, if any; (iii) a brief description of your request; (iv) your full name; (v) your e-mail address; (vi) your telephone number; and/or (vii) any other information requested on the Site Form (collectively, the "Directory Registration Data"). You agree to provide true, accurate, current and complete Directory Registration Data and to update your Directory Registration Data as necessary in order to maintain it in a current and accurate fashion. Eilite's™ use of the Directory Registration Data shall be governed by the Privacy Policy.`,
      `Upon entering your Directory Registration Data and clicking on the applicable submission button on the Site, you may be provided additional information regarding participating Third Party Contractors that are located in your designated geographic area that you can choose to contact or be contacted by. Upon your request to contact, or be contacted by, any of the applicable Third Party Contractors. Eilite™ may transfer all or some of your Directory Registration Data to the applicable Third Party Contractor(s) in connection with facilitating your request for Contractor Offerings from same. In the event Eilite™ does not have any Third Party Contractor in your service area, Eilite™ may share your Directory Registration Data with Fulfillment Partners, including but not limited to CraftJack or Angi, in connection with facilitating your request for Contractor Offerings. Any information provided to any Fulfillment Partner shall be governed by the applicable Fulfillment Partner's Terms and Conditions and Privacy Policy.`,
      `You understand and agree that Eilite™ shall not be liable to you or any third party for any modification, suspension or discontinuation of any service offered by any Third Party Contractor.`,
    ],
  },
  {
    heading: "Listings/Free Listings",
    paragraphs: [
      `Subject to the terms and conditions of the Agreement, by registering on the Site, agreeing to the Agreement and receiving approval from Eilite™, you (acting as a Third Party Contractor) can submit, or attempt to submit, Listings for display to Site Users that conduct searches by and through the Directory. To submit a Listing, you must first fully complete the applicable Site Form. The information that you must supply on the Site Form includes, but is not limited to: (a) your company name; (b) your full name; (c) your telephone number; (d) your mobile telephone number; (e) your zip code; (f) your e-mail address; (g) categories that apply to your Contractor Offerings, if applicable; and/or (h) any other information requested on the Site Form (collectively, the "Listing Registration Data" and together with the Directory Registration Data, the "Registration Data"). You agree to provide true, accurate, current and complete Listing Registration Data and to update your Listing Registration Data as necessary in order to maintain it in a current and accurate fashion. Eilite's™ use of the Listing Registration Data shall be governed by the Privacy Policy.`,
      `The Listings contain descriptions that are provided directly by the applicable Third Party Contractors, or the manufacturers or distributors of the Contractor Offerings featured in the Listings, as applicable. Eilite™ does not represent or warrant that the descriptions of such items are accurate or complete. As a result, Eilite™ has no control over: (i) the quality, safety or legality of the Contractor Offerings; (ii) the truth or accuracy of the Listings; and/or (iii) the ability of the applicable Third Party Contractors to sell/provide the Contractor Offerings. Do not assume that the offer, sale, purchase, export or import of any Contractor Offerings is valid and legal simply because they are listed on the Site. We are not responsible for ensuring that any applicable Third Party Contractor actually completes a transaction. Where you submit a Listing by and through the Site, you represent and warrant that: (A) all content in the Listing is accurate, complete and current; (B) you have all necessary rights, power and authority to publish the Listing; (C) the Listing, and any website listed in, or linked to from, the Listing: (I) complies with all applicable laws and regulations; (II) does not infringe upon, misappropriate or otherwise violate any copyright, patent, trademark, service mark, trade secret or other intellectual property right of any Third Party; (III) does not violate the rights of any person or entity, including rights of publicity or privacy, and is not defamatory; and (IV) does not result in consumer fraud (including being false or misleading), product liability, tort, breach of contract, injury, damage or harm of any kind to any person or entity; and (D) you possess documents that substantiate all claims, express and implied, contained within the Listing.`,
    ],
  },
  {
    heading: "Enhanced Services",
    paragraphs: [
      `Subject to the terms and conditions of the Agreement, as well as the Lead Agreement that you must agree to in its entirety and execute when you attempt to become an Advertiser, you can obtain, or attempt to obtain, for a fee, access to the Enhanced Services as an Advertiser. Advertisers are subject to the same obligations, terms and conditions as apply to Third Party Contractors under the Agreement including, without limitation, those applicable to Listings set forth above.`,
    ],
  },
  {
    heading: "Content",
    paragraphs: [
      `Subject to the terms and conditions of the Agreement, end-users that possess the requisite technology shall have the opportunity to view, download and/or interact with all or some of the Content made available by and through the Site and/or other Eilite™ Offerings. The Content is compiled, distributed and displayed by Eilite™, as well as various Third Party content providers including, without limitation, Third Party Contractors, Visitors and Participants ("Third Party Providers"). Eilite™ does not control the Content provided by Third Party Providers that is made available by and through the Eilite™ Offerings. Such Third-Party Providers are solely responsible for the accuracy, completeness, appropriateness and/or usefulness of such Content. The Content should not necessarily be relied upon. Eilite™ does not represent or warrant that the Content and other information posted by and through the Eilite™ Offerings is accurate, complete, up-to-date or appropriate. You understand and agree that Eilite™ shall not be responsible for, and Eilite™ undertakes no responsibility to monitor or otherwise police, Content provided by Third-Party Providers. You agree that Eilite™ shall have no obligation and incur no liability to you in connection with any Content. You may find certain Content to be outdated, harmful, inaccurate and/or deceptive. Please use caution, common sense and safety when using the Content.`,
    ],
  },
  {
    heading: "Social Media Pages",
    paragraphs: [
      `The Site contains links to various Social Media Pages. The Social Media Pages are hosted and made available on Third Party websites ("Social Media Websites") by Third Party entities. Your use of Social Media Pages and Social Media Websites shall be governed by the applicable terms and conditions of those Social Media Websites. You understand and agree that Eilite™ shall not be liable to you, any other end-user or any Third Party for any claim in connection with your use of, or inability to use, the Social Media Pages and/or Social Media Websites.`,
    ],
  },
  {
    heading: "Interactive Services",
    paragraphs: [
      `Subject to the restrictions set forth herein, the Interactive Services will allow you to participate in, and provide Feedback in connection with, comment sections, blogs, message boards, question and answer areas and other interactive areas of the Site.`,
    ],
  },
  {
    heading: "Site Content Submission Guidelines",
    paragraphs: [
      `All Site Content that you submit through or in association with the Eilite™ Offerings including, without limitation, the Registration Data, Feedback, Listings, Content, articles, advertisements, responses, comments, statements, promises or other information, shall be subject to the Privacy Policy. For a copy of the Privacy Policy, please Click Here.`,
      `By submitting such Site Content to us, you represent and warrant that:`,
      `(a) You agree to use the Eilite™ Offerings in full compliance with all applicable laws, rules and regulations.`,
      `(b) Eilite's™ use of your submission does not and will not breach any agreement, violate any law or infringe upon any third party's rights;`,
      `(c) You are the sole author and owner of any intellectual property contained in any protected Site Content you submit;`,
      `(d) You are solely responsible for the Site Content that you publish or post, including any Feedback by and through the Eilite™ Offerings;`,
      `(e) All Site Content that you post is accurate;`,
      `(f) You have not been offered, have not accepted, and are not entitled to receive any compensation in any form and from any party in connection with submitted Site Content;`,
      `(g) Your use of Site Content does not violate this Agreement and will not cause injury to any person or entity; and`,
      `You further agree and warrant that you will not:`,
      `(a) Submit Site Content that contains confidential information including financial information, phone numbers, email addresses, mailing addresses, medical information, or trade secrets;`,
      `(b) Submit Site Content that contains content that is unlawful, harmful, defamatory, indecent, obscene, libelous, harassing, abusive, vulgar, sexually explicit or otherwise objectionable;`,
      `(c) Submit Site Content that includes inappropriate content on the basis of race, gender, national origin, ethnicity, religion, sexual orientation, gender identity, age, disability, or any other intrinsic or protected characteristic;`,
      `(d) Submit Site Content that is threatening, demands payment, or is designed only to damage a contractor's reputation;`,
      `(e) Submit any Site Content that is false or misleading;`,
      `(f) Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity, including Eilite™.`,
      `(g) Act in a manner that affects other Site Users' ability to engage in real time exchanges;`,
      `(h) Engage in unauthorized advertising or marketing to, or commercial solicitation of, Site Users;`,
      `(i) Post, offer for download, transmit or promote any chain letters, spam, spyware, adware or junk e-mails to Site Users or other parties;`,
      `(j) Express or imply that any statements you make are endorsed by Eilite™;`,
      `(k) Invade another's privacy in any way, including harvesting or collecting personal information of Site Users, whether or not for commercial purposes, without their express consent;`,
      `(l) Use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, "data mine," or in any way reproduce or circumvent the navigational structure or presentation of the Site or its contents;`,
      `(m) Post, distribute or reproduce in any way any copyrighted material, trade secrets, trademarks or other proprietary information without obtaining the prior consent of the owner of such proprietary rights;`,
      `(n) Remove any copyright, trademark or other proprietary rights notices contained in the Eilite™ Offerings;`,
      `(o) Interfere with or disrupt any of the Eilite™ Offerings and/or the servers or networks connected to same;`,
      `(p) Manipulate identifiers in order to disguise the origin of any Site Content submitted;`,
      `(q) Post, offer for download, e-mail or otherwise transmit any Site Content that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;`,
      `(r) Post, offer for download, transmit, promote or otherwise make available any software, product or service that is illegal or that violates the rights of a third party including, but not limited to, spyware, adware, programs designed to send unsolicited advertisements (i.e. "spamware"), services that send unsolicited advertisements, programs designed to initiate "denial of service" attacks, mail bomb programs and programs designed to gain unauthorized access to networks on the Internet;`,
      `(s) "Frame" or "mirror" any part of the Eilite™ Offerings;`,
      `(t) Use metatags or code or other devices containing any reference to the Eilite™ Offerings in order to direct any person to any other website for any purpose; and/or`,
      `(u) Modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Eilite™ Offerings or any software used on or in connection with same.`,
      `Engaging in any of the aforementioned prohibited practices shall be deemed a breach of the Agreement and may result in the immediate termination of your access to some or all of the Eilite™ Offerings without notice, in the sole discretion of Eilite™. Eilite™ reserves the right to pursue any and all legal remedies against Site Users that engage in the aforementioned prohibited conduct. You agree that Eilite™ has the right, in its sole discretion, to remove, refuse, move, edit, or delete any Site Content submitted, regardless of whether the Site Content violates this Agreement.`,
      `Any submission of Site Content will be deemed and remain the property of Eilite™. Eilite™ is free to use in any manner all or part of any such Site Content or other materials in perpetuity, on an unrestricted basis, without the obligation to notify, identify or compensate you or anyone else. By submitting User Content, you hereby grant Eilite™ the royalty free, perpetual, irrevocable right, including a waiver of all copyright, trademark, privacy and moral rights, to use, reproduce, modify, publish, distribute, translate, create derivative works from and display all Site Content and/or materials, in whole or in part, without any duty by Eilite™ to anyone whatsoever. You also acknowledge that Eilite™ does not accept unsolicited ideas, works, or other materials and that you are responsible for, and bear all risk arising out of the use or distribution of any such ideas, works, or materials. You also agree that you will indemnify, defend, and hold harmless Eilite™ and its officers, directors, employees and agents from any third-party claim(s) and any damages, losses or injuries resulting from the display of your Site Content;`,
      `Eilite™ shall not be subject to any obligations of confidentiality regarding Site Content except as expressly agreed by Eilite™ or as required by applicable law. Nothing in this Agreement shall be construed as limiting Eilite™ rights, responsibilities or obligations under its Privacy Policy.`,
    ],
  },
  {
    heading: "License Grant",
    paragraphs: [
      `As a user of the Site, you are granted a non-exclusive, non-transferable, revocable and limited license to access and use the Eilite™ Offerings and associated content in accordance with the Agreement. Eilite™ may terminate this license at any time for any reason. Other than where expressly permitted by Eilite™, you may only use the Eilite™ Offerings on one computer for your own personal, non-commercial use. No part of the Eilite™ Offerings may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical. You may not use, copy, emulate, clone, rent, lease, sell, modify, decompile, disassemble, reverse engineer or transfer the Eilite™ Offerings or any portion thereof. Eilite™ reserves all rights not explicitly granted in the Agreement. You may not use any device, software or routine to interfere or attempt to interfere with the proper working of the Eilite™ Offerings. You may not take any action that imposes an unreasonable or disproportionately large load on Eilite™ infrastructure. Your right to use the Eilite™ Offerings is not transferable.`,
    ],
  },
  {
    heading: "Proprietary Rights",
    paragraphs: [
      `The content, organization, graphics, design, compilation, magnetic translation, digital conversion, software, services and other matters related to the Eilite™ Offerings are protected under applicable copyright, trademark and other proprietary (including, but not limited to, intellectual property) rights. The copying, redistribution, publication or sale by you of any part of the Eilite™ Offerings is strictly prohibited. Systematic retrieval of material from the Site by automated means or any other form of scraping or data extraction in order to create or compile, directly or indirectly, a collection, compilation, database or directory without written permission from Eilite™ is prohibited. You do not acquire ownership rights in or to any content, document, software, services or other materials viewed at the Site or through the Eilite™ Offerings. The posting of information or material on the Site by Eilite™ does not constitute a waiver of any right in or to such information and/or materials. The "Eilite" name and logo, and all associated graphics, icons and service names, are trademarks of Eilite Systems, Inc. All other trademarks are the property of their respective owners. The use of any trademark without the applicable trademark owner's prior express written consent is strictly prohibited.`,
    ],
  },
  {
    heading: "Copyright Policy/DMCA Compliance",
    paragraphs: [
      `Eilite™ reserves the right to terminate access to the Site of any Site User who infringes upon third-party copyright rights. If you believe that a copyrighted work has been copied and/or posted via the Site and/or other Eilite™ Offerings in a way that constitutes copyright infringement, you should provide Eilite™ with the following information: (a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyrighted work; (b) an identification and location on the Site (or otherwise) of the copyrighted work that you claim has been infringed upon; (c) a written statement by you that you have a good faith belief that the disputed use is not authorized by the owner, its agent or the law; (d) your name and contact information, such as telephone number or e-mail address; and (e) a statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner's behalf. Contact information for Eilite's™ Copyright Agent for notice of claims of copyright infringement is as follows:`,
      `Eilite Systems, Inc.\nAttn: DMCA/Copyright Agent\n3445 Peachtree Rd NE\nAtlanta, Georgia 30326\ninfo@eilite.com`,
    ],
  },
  {
    heading: "Editing, Deleting and Modification",
    paragraphs: [
      `We reserve the right in our sole discretion to edit and/or delete any documents, information or other content appearing on the Site.`,
    ],
  },
  {
    heading: "Legal Warning",
    paragraphs: [
      `Any attempt by any individual, whether or not a Eilite™ customer, to damage, destroy, tamper with, vandalize and/or otherwise interfere with the operation of the Eilite™ Offerings, is a violation of criminal and civil law, and Eilite™ will diligently pursue any and all remedies in this regard against any offending individual or entity to the fullest extent permissible by law and in equity.`,
    ],
  },
  {
    heading: "Indemnification",
    paragraphs: [
      `You agree to indemnify and hold Eilite™, its parents, subsidiaries and affiliates, and each of their respective members, officers, directors, employees, agents, co-branders and/or other partners, harmless from and against any and all claims, expenses (including reasonable attorneys' fees), damages, suits, costs, demands and/or judgments whatsoever, made by any third party due to or arising out of: (a) your use of the Eilite™ Offerings; (b) your breach of the Agreement; (c) any dispute between you and any Site User or third party; and/or (d) your violation of any rights of another individual and/or entity. The provisions of this Section are for the benefit of Eilite™, its parents, subsidiaries and/or affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.`,
    ],
  },
  {
    heading: "Disclaimer of Warranties",
    paragraphs: [
      `The Eilite™ Offerings and/or any other products and/or services that you may apply for through same are provided to you on an "as is" and "as available" basis. And all warranties, express and implied, are disclaimed to the fullest extent permissible pursuant to applicable law (including, but not limited to, the disclaimer of any warranties of merchantability, non-infringement of intellectual property and/or fitness for a particular purpose). In particular, but not as a limitation thereof, Eilite™ makes no warranty that: (a) the Eilite™ Offerings and/or any other products and/or services that you may apply for through same will meet your requirements; (b) the Eilite™ Offerings and/or any other products and/or services that you may apply for through same will be uninterrupted, timely, secure or error-free; (c) you will qualify for contractor offerings from any third party contractor; or (d) the results that may be obtained from the use of the Eilite™ Offerings and/or any other products and/or services that you may apply for through same will be accurate or reliable. The Eilite™ offerings and/or any other products and/or services that you may apply for through same may contain bugs, errors, problems or other limitations. We will not be liable for the availability of the underlying internet connection associated with the site. No advice or information, whether oral or written, obtained by you from Eilite™, any site user or otherwise through or from the Eilite™ offerings, shall create any warranty not expressly stated in the agreement.`,
    ],
  },
  {
    heading: "Limitation of Liability",
    paragraphs: [
      `You expressly understand and agree that Eilite™ shall not be liable to you or any third party for any direct, indirect, incidental, special, consequential and/or exemplary damages including, but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if Eilite™ has been advised of the possibility of such damages), to the fullest extent permissible by law for: (a) the use or the inability to use the Eilite™ offerings and/or any other products and/or services that you may apply for through same; (b) the cost of procurement of substitute goods and services resulting from any goods, data, information and/or services purchased or obtained from, or transactions entered into through, the Eilite™ offerings; (c) the failure to qualify for contractor offerings from any third party contractor; (d) the unauthorized access to, or alteration of, your registration data; and (e) any other matter relating to the Eilite™ Offerings and/or any other products and/or services that you may apply for through same. This limitation applies to all causes of action, in the aggregate including, but not limited to, breach of contract, breach of warranty, negligence, strict liability, misrepresentations and any and all other torts. You hereby release Eilite™ from any and all obligations, liabilities and claims in excess of the limitations stated herein. If applicable law does not permit such limitations, the maximum liability of Eilite™ to you under any and all circumstances will be five hundred dollars ($500.00). The negation of damages set forth above is a fundamental element of the basis of the bargain between you and Eilite™. The Eilite™ Offerings and/or any other products and/or services that you may apply for through same would not be provided to you without such limitations.`,
      `THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.`,
    ],
  },
  {
    heading: "Third Party Websites",
    paragraphs: [
      `The Site may provide links to and/or refer you to other Internet websites and/or resources including, but not limited to, certain Site User websites. Because Eilite™ has no control over such third-party websites and/or resources, you hereby acknowledge and agree that Eilite™ is not responsible for the availability of such third party websites and/or resources. Furthermore, Eilite™ does not endorse, and is not responsible or liable for, any terms and conditions, privacy policies, content, advertising, services, products and/or other materials at or available from such third party websites or resources, or for any damages and/or losses arising therefrom.`,
    ],
  },
  {
    heading: "Governing Law",
    paragraphs: [
      `The Agreement shall be treated as though it were executed and performed in Atlanta, Georgia 30326 and shall be governed by and construed in accordance with the laws of the State of New York (without regard to conflict of law principles).`,
    ],
  },
  {
    heading: "Arbitration and Class Action Waiver",
    paragraphs: [
      `YOU AND Eilite™ AGREE TO ARBITRATE DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO ANY COMMUNICATIONS YOU RECEIVE FROM EILITE™, ITS AFFILIATES, OR ANYONE ELSE CONCERNING EILITE™ OR THE EILITE™ OFFERINGS, AND ANY DISPUTES CONCERNING THE AGREEMENT (INCLUDING ALL OTHER POLICIES AND AGREEMENTS INCORPORATED HEREIN BY REFERENCE) OR THE SITE, THEIR INTERPRETATION, VIOLATION, INVALIDITY, NON-PERFORMANCE, OR TERMINATION.`,
      `If you intend to seek arbitration, you must first commence a formal dispute proceeding by completing and submitting an Initial Dispute Notice. The Initial Dispute Notice should be addressed to: Eilite Systems, Inc., 3445 Peachtree Rd NE, Atlanta, Georgia 30326. The Initial Dispute Notice must: (1) describe the nature and basis of the claim or dispute; and (ii) set forth the specific relief sought. We may choose to provide you with a final written settlement offer after receiving your Initial Dispute Notice ("Final Settlement Offer"). If we provide you with a Final Settlement Offer and you do not accept it, or we cannot otherwise satisfactorily resolve your dispute within thirty (30) days of receiving the Initial Dispute Notice, you may commence an arbitration proceeding under the terms of this Agreement in Atlanta, Georgia 30326.`,
      `The arbitration shall be governed by the Consumer Arbitration Rules (collectively, "AAA Rules") of the American Arbitration Association ("AAA"), as modified by the terms of this Agreement, and the arbitration shall be administered by the AAA. The AAA Rules and fee information are available at "www.adr.org" or by calling the AAA at 1-800-778-7879. The arbitrator shall have the exclusive authority to resolve any dispute relating to the interpretation, applicability, scope, or enforceability of these arbitration provisions and the terms of this Agreement.`,
      `For claims of Ten Thousand Dollars ($10,000.00) or less, you can choose whether the arbitration proceeds in person, by telephone or based only on written submissions. Otherwise, if the arbitrator awards you relief that is greater than our Final Settlement Offer, then we will pay all filing, administration and arbitrator fees associated with the arbitration, and, if you retained an attorney to represent you in connection with the arbitration, we will reimburse any reasonable attorneys' fees that your attorney accrued for investigating, preparing and pursuing the claim in arbitration. Notwithstanding the aforementioned allocation of fees, Eilite shall bear the cost of any arbitration filing fees and arbitrator's fees required by the AAA rules or to the extent required under applicable law to render these arbitration terms enforceable.`,
      `Any award rendered shall be final and conclusive to the parties and a judgment thereon may be entered in any court of competent jurisdiction. Nothing contained herein shall be construed to preclude any party from: (i) seeking injunctive relief in order to protect its rights pending an outcome in arbitration; and/or (ii) pursuing the matter in small claims court rather than arbitration. Although we may have a right to an award of attorneys' fees and expenses if we prevail in arbitration, we will not seek such an award from you unless the arbitrator determines that your claim was frivolous.`,
      `TO THE EXTENT PERMITTED BY LAW, YOU AGREE THAT YOU WILL NOT BRING, JOIN OR PARTICIPATE IN ANY CLASS ACTION LAWSUIT OR ARBITRATION AS TO ANY CLAIM, DISPUTE OR CONTROVERSY THAT YOU MAY HAVE AGAINST EILITE™ AND/OR ITS EMPLOYEES, OFFICERS, DIRECTORS, MEMBERS, REPRESENTATIVES AND/OR ASSIGNS. YOU AND EILITE AGREE THAT CLAIMS MAY ONLY BE BROUGHT IN A PARTY'S INDIVIDUAL CAPACITY AND NOT ON BEHALF OR, AS A PART OF, A CLASS ACTION OR REPRESENTATIVE PROCEEDING. You agree to the entry of injunctive relief to stop such a lawsuit or to remove you as a participant in the suit. You agree to pay the attorney's fees and court costs that Eilite™ incurs in seeking such relief. This class action waiver: (A) does not constitute a waiver of any of your rights or remedies to pursue a claim individually and not as a class action in binding arbitration as provided above; and (B) is an independent agreement.`,
      `You may opt-out of these dispute resolution provisions by providing written notice of your decision at the email or mailing addresses listed below within thirty (30) days of the date that you first access the Site.`,
      `This section shall survive the termination of this Agreement.`,
    ],
  },
  {
    heading: "Miscellaneous",
    paragraphs: [
      `Should any part of the Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. To the extent that anything in or associated with any Eilite™ Offerings is in conflict or inconsistent with the Agreement, the Agreement shall take precedence. Our failure to enforce any provision of the Agreement shall not be deemed a waiver of such provision nor of the right to enforce such provision. The parties do not intend that any agency or partnership relationship be created through operation of the Agreement.`,
    ],
  },
  {
    heading: "Contact Us",
    paragraphs: [
      `If you have any questions regarding the Agreement, or would like more information from Eilite™, please call us at: (302) 244-7240, or email us at: info@eilite.com.`,
      `Our corporate offices are located at:\n1111B S Governors Ave STE 21889, Dover, Delaware 19904`,
    ],
  },
];
