import type { SolutionVertical } from "./types";

export const healthcareSolutions: SolutionVertical[] = [
  {
    slug: "medicare-lead-generation",
    label: "Medicare",
    category: "Healthcare",
    keywords: ["medicare"],
    tagline: "Medicare Leads That Are",
    highlight: "Actually Ready to Enroll",
    subheadline:
      "Get exclusive Medicare leads and live warm transfers — screened for age, ZIP code, and current coverage — so your agents spend AEP calling real prospects, not chasing aggregator leftovers.",
    searchChips: ["medicare enrollment help", "when can i change my medicare plan", "medicare plans near me"],
    demoIndustry: "Medicare",
    overviewEyebrow: "The Problem",
    overviewHeading: "Medicare leads are heavily regulated, heavily competed for, and full of low-intent clicks",
    overviewParagraphs: [
      "Medicare is one of the most heavily regulated categories in all of marketing — CMS marketing guidelines govern what can even be said in an ad, and a single non-consented call can create real compliance exposure, not just a wasted dial. Layer on the Annual Enrollment Period, when every agent in the country is competing for the same prospects at once, and it's easy to end up paying premium prices for \"just checking\" clicks from people who aren't near a decision, let alone eligible.",
      "Every Medicare lead and warm transfer we deliver is screened for real eligibility — age, ZIP code, and current coverage status — and verified consent before it ever reaches your team. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and CMS-aware TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for age, ZIP code, and current coverage before they ever reach your team",
      "Exclusive delivery — sold once, never resold to a competing agent or agency",
      "Volume that scales up for Annual Enrollment Period and pulls back the rest of the year",
      "Live warm transfers for agents who want a screened beneficiary already on the phone",
    ],
    faqs: [
      { q: "What qualification criteria are used for Medicare leads?", a: "Every lead is screened for age, ZIP code, and current coverage status before delivery, so you're calling beneficiaries who actually match your target enrollment window instead of generic \"just researching\" traffic." },
      { q: "Are Medicare leads exclusive to my agency?", a: "Yes. Every lead and transfer is sold once, to a single agent or agency — never resold or shared with a competitor working the same market." },
      { q: "Can I target specific states or counties?", a: "Yes. Campaigns are built around the states you're licensed in, down to the specific counties you actually serve, since plan availability and competitive intensity shift meaningfully at the local level." },
      { q: "How fast are leads delivered, and can volume scale during AEP?", a: "Web-form leads deliver in real time as beneficiaries submit, and live warm transfers connect you while they're still on the phone. Volume is built to scale up heading into Annual Enrollment Period and other Medicare enrollment windows, then pull back the rest of the year." },
      { q: "How is compliance handled given how regulated Medicare marketing is?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, in addition to identity verification and documented consent certification, before it's ever delivered — with CMS marketing guidelines factored into how campaigns are built and screened from the start." },
    ],
  },
  {
    slug: "medicare-advantage-lead-generation",
    label: "Medicare Advantage",
    category: "Healthcare",
    keywords: ["medicare-advantage"],
    tagline: "Medicare Advantage Leads,",
    highlight: "Filtered Down to the County",
    subheadline:
      "Reach beneficiaries actively comparing Medicare Advantage plans — filtered by age, ZIP code, and current coverage, and matched to the plans actually available where they live.",
    searchChips: ["best medicare advantage plan 2026", "medicare advantage vs original medicare", "medicare advantage plans in my area"],
    demoIndustry: "Medicare Advantage",
    overviewEyebrow: "The Problem",
    overviewHeading: "Medicare Advantage plan availability is hyper-local, and a statewide lead doesn't account for that",
    overviewParagraphs: [
      "Medicare Advantage carrier participation and plan availability can shift meaningfully from one county to the next, even within the same state — a lead sourced off a broad statewide or national buy can land you a beneficiary whose county doesn't even carry the plans you're contracted to sell. Add in Annual Enrollment Period and Medicare Advantage Open Enrollment Period volume spikes, when every agent in the market is chasing the same limited pool, and untargeted leads become an expensive way to reach people you can't actually enroll.",
      "Every Medicare Advantage lead we deliver is screened for real eligibility — age, ZIP code, and current coverage — and matched against the counties you're actually licensed and contracted to serve, so you're never quoting plans that aren't available where the beneficiary lives. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and CMS-aware TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered down to the county level, matched to where your contracted plans are actually available",
      "Pre-screened for age, ZIP code, and current coverage before they ever reach your team",
      "Exclusive delivery — never resold to a competing agent or agency in your market",
      "Live warm transfers for agents who want a screened beneficiary already on the phone, ready to compare plans",
    ],
    faqs: [
      { q: "What qualification criteria are used for Medicare Advantage leads?", a: "Every lead is screened for age, ZIP code, and current coverage status, then matched to the counties where your contracted plans are actually available, so you're not paying for prospects outside your service area." },
      { q: "Are Medicare Advantage leads exclusive to my agency?", a: "Yes. Every lead and transfer is sold once, to a single agent or agency — never resold or shared with a competitor working the same county." },
      { q: "Can I target specific states or counties?", a: "Yes. Since Medicare Advantage plan availability varies county by county, campaigns are built around the specific counties you're contracted to sell in, not just a broad state or metro area." },
      { q: "How fast are leads delivered, and can volume scale during AEP?", a: "Web-form leads deliver in real time as beneficiaries submit, and live warm transfers connect you while they're still on the phone. Volume is built to scale up heading into Annual Enrollment Period and Medicare Advantage Open Enrollment Period, then pull back the rest of the year." },
      { q: "How is compliance handled given how regulated this space is?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, in addition to identity verification and documented consent certification, before it's ever delivered — with CMS marketing guidelines factored into how campaigns are built and screened from the start." },
    ],
  },
  {
    slug: "medicare-supplement-lead-generation",
    label: "Medicare Supplement (Medigap)",
    category: "Healthcare",
    keywords: ["medigap", "medicare-supplement"],
    tagline: "Medigap Leads for Prospects",
    highlight: "Who Already Know Which Plan Letter They Want",
    subheadline:
      "Connect with beneficiaries actively comparing Medicare Supplement plan letters — screened for age, ZIP code, and current coverage, and timed around guaranteed-issue and underwriting windows.",
    searchChips: ["medicare plan g vs plan n", "medicare supplement insurance cost", "best medigap plan for seniors"],
    demoIndustry: "Medicare Supplement (Medigap)",
    overviewEyebrow: "The Problem",
    overviewHeading: "Medigap shoppers compare specific plan letters, and most need underwriting outside open enrollment",
    overviewParagraphs: [
      "Medigap buyers behave differently than Medicare Advantage shoppers — they're often already comparing specific lettered plans like Plan G and Plan N, and outside of a guaranteed-issue window or a prospect's initial enrollment period, most need to qualify through medical underwriting before a carrier will accept the application. A generic Medicare lead that skips this context wastes agent time re-explaining plan letters and underwriting timing to someone who was never close to a decision.",
      "Every Medigap lead we deliver is screened for real eligibility — age, ZIP code, and current coverage status — before it's sent, so agents aren't guessing at where a prospect stands relative to their guaranteed-issue or enrollment window. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and CMS-aware TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for age, ZIP code, and current coverage before they ever reach your team",
      "Exclusive delivery — sold once, never resold to a competing agent or agency",
      "Volume that scales around guaranteed-issue windows, 65th-birthday timing, and Annual Enrollment Period",
      "Live warm transfers for agents who want a screened beneficiary already on the phone, ready to talk plan letters",
    ],
    faqs: [
      { q: "What qualification criteria are used for Medigap leads?", a: "Every lead is screened for age, ZIP code, and current coverage status before delivery, so you're calling beneficiaries who genuinely fit a Medicare Supplement conversation rather than generic Medicare traffic." },
      { q: "Are Medigap leads exclusive to my agency?", a: "Yes. Every lead and transfer is sold once, to a single agent or agency — never resold or shared with a competitor working the same market." },
      { q: "Can I target specific states or counties?", a: "Yes. Campaigns are built around the states you're licensed in, since Medigap premium structures and carrier participation vary by state and county." },
      { q: "How fast are leads delivered, and can volume scale during AEP?", a: "Web-form leads deliver in real time as beneficiaries submit, and live warm transfers connect you while they're still on the phone. Volume is built to scale up heading into Annual Enrollment Period and around guaranteed-issue and 65th-birthday enrollment windows, then pull back the rest of the year." },
      { q: "How is compliance handled given how regulated Medigap marketing is?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, in addition to identity verification and documented consent certification, before it's ever delivered — with CMS marketing guidelines factored into how campaigns are built and screened from the start." },
    ],
  },
  {
    slug: "final-expense-lead-generation",
    label: "Final Expense",
    category: "Healthcare",
    keywords: ["final-expense"],
    tagline: "Final Expense Leads,",
    highlight: "Handled With the Care This Audience Deserves",
    subheadline:
      "Reach seniors actively shopping final expense and burial insurance coverage — screened for age, ZIP code, and current coverage, and delivered with the compliant, respectful outreach this audience requires.",
    searchChips: ["final expense insurance quotes", "burial insurance for seniors", "life insurance for funeral costs"],
    demoIndustry: "Final Expense",
    overviewEyebrow: "The Problem",
    overviewHeading: "Final expense is a fast-close product with an older buyer pool that demands careful outreach",
    overviewParagraphs: [
      "Final expense is a lower-face-value, faster-closing product than most Medicare-related lines, but the buyer pool skews older, is often approaching the decision for personal or family reasons, and requires the same compliant, careful outreach as any senior-targeted marketing category. Generic leads that skip real screening put agents in the position of cold-calling people who were never close to a decision, or worse, contacting someone who never consented to be reached in the first place.",
      "Every final expense lead and warm transfer we deliver is screened for real eligibility — age, ZIP code, and current coverage status — and verified consent before it ever reaches your team. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and CMS-aware TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for age, ZIP code, and current coverage before they ever reach your team",
      "Exclusive delivery — sold once, never resold to a competing agent or agency",
      "Volume that scales up around Annual Enrollment Period and pulls back the rest of the year",
      "Live warm transfers for agents who want a screened prospect already on the phone, ready to talk coverage",
    ],
    faqs: [
      { q: "What qualification criteria are used for final expense leads?", a: "Every lead is screened for age, ZIP code, and current coverage status before delivery, so you're calling seniors who genuinely fit a final expense conversation rather than unscreened, generic traffic." },
      { q: "Are final expense leads exclusive to my agency?", a: "Yes. Every lead and transfer is sold once, to a single agent or agency — never resold or shared with a competitor working the same market." },
      { q: "Can I target specific states or counties?", a: "Yes. Campaigns are built around the states and counties you're licensed and actually serve, so every lead delivered is one you can act on." },
      { q: "How fast are leads delivered, and can volume scale during AEP?", a: "Web-form leads deliver in real time as prospects submit, and live warm transfers connect you while they're still on the phone. Volume is built to scale up heading into Annual Enrollment Period and other high-demand windows, then pull back the rest of the year." },
      { q: "How is compliance handled given how sensitive this audience is?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, in addition to identity verification and documented consent certification, before it's ever delivered — with CMS marketing guidelines factored into how campaigns are built and screened from the start, given how closely senior-targeted marketing is regulated." },
    ],
  },
];
