import type { SolutionVertical } from "./types";

export const homeServices2: SolutionVertical[] = [
  {
    slug: "pest-control-lead-generation",
    label: "Pest Control",
    category: "Home Services",
    keywords: ["pest control", "pest"],
    tagline: "Book More Treatments,",
    highlight: "From First Call to Recurring Contract",
    subheadline:
      "Get exclusive pest control leads — from one-time ant and roach treatments to full-year recurring contracts — filtered by pest type and delivered while the homeowner is still searching.",
    searchChips: ["pest control near me", "termite inspection cost", "ant exterminator same day"],
    demoIndustry: "Pest Control",
    overviewEyebrow: "The Problem",
    overviewHeading: "Pest control leads swing between $89 one-time sprays and $600 annual contracts",
    overviewParagraphs: [
      "A \"pest control lead\" could be a one-time ant spray or a full year-round contract with quarterly visits — and the two have completely different economics, so paying flat rates for both erodes your margin. Demand is also brutally seasonal: termite swarms in spring, ants and wasps in summer, rodents moving indoors in fall, which means the same directory that's too slow in June leaves you idle in February. On top of that, aggregator sites resell the same homeowner to five competing companies, so the exterminator who calls back first — not necessarily the best one — wins the job.",
      "We fix that by filtering every pest control lead by pest type and service type — one-time treatment versus recurring contract — before it reaches you. Leads are captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold lists or aggregator leftovers, then screened for real contact info, real intent, and a real pest issue before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by pest type and service type — one-time treatment or recurring contract",
      "Exclusive delivery — never resold to a competing pest control company in your market",
      "Real-time delivery so you can call back before the homeowner tries the next exterminator",
      "Volume scales up for seasonal pest spikes — termites in spring, ants in summer, rodents in fall",
    ],
    faqs: [
      { q: "What types of pest control leads can I buy?", a: "One-time treatments (ants, roaches, wasps, spiders), termite inspections and treatment, rodent and wildlife removal, bed bug treatment, and recurring quarterly or annual contracts — filtered so you're only paying for the service types you actually offer." },
      { q: "Are pest control leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single pest control company — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually service, so you're not paying to chase jobs outside your route." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit. Warm transfers connect you live, on the phone, while the homeowner still has the pest problem in front of them." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered — so you're calling a real homeowner with a real pest issue, not a bot or duplicate." },
    ],
  },
  {
    slug: "flooring-lead-generation",
    label: "Flooring",
    category: "Home Services",
    keywords: ["flooring", "floor"],
    tagline: "Fill Your Install Calendar",
    highlight: "With Homeowners Ready to Choose Materials",
    subheadline:
      "Connect with homeowners actively comparing hardwood, tile, LVP, and carpet — filtered by material interest and project scope, and delivered while they're still deciding, not just dreaming.",
    searchChips: ["flooring installation cost", "hardwood vs laminate flooring", "flooring contractors near me"],
    demoIndustry: "Flooring",
    overviewEyebrow: "The Problem",
    overviewHeading: "Flooring leads take weeks to close and most never make it past the sample stage",
    overviewParagraphs: [
      "Flooring is a material-selection business first and a sales business second — a homeowner comparing hardwood, tile, LVP, and carpet swatches can take weeks or months before they're ready to sign, and a large share of directory leads are still in the browsing phase, not the buying phase. Shared lead platforms make it worse by selling the same homeowner to every flooring contractor in the market, turning a considered purchase into a race-to-the-bottom bidding war on price alone.",
      "We filter flooring leads by material interest and project scope — whole-home versus single-room, replacement versus new install — so your estimators are quoting homeowners who've already narrowed their choice, not starting from zero. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real project scope before it's delivered exclusively to you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by material interest — hardwood, tile, LVP, or carpet",
      "Exclusive delivery, never resold to a competing flooring contractor in your area",
      "Filtered by project scope — whole-home replacement or single-room install",
      "Real-time delivery so you're quoting while the homeowner is still comparing samples",
    ],
    faqs: [
      { q: "What flooring job types can I target?", a: "Hardwood, tile, luxury vinyl plank, carpet, and laminate installs, plus refinishing and repair work — filtered by material interest and whether it's a single room or whole-home project." },
      { q: "Are flooring leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single flooring contractor — never resold or shared with a competitor in the same market." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually install in." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your estimator can follow up while material preferences are still fresh." },
      { q: "How is lead quality verified?", a: "Every submission goes through fraud screening, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "electrician-lead-generation",
    label: "Electrician",
    category: "Home Services",
    keywords: ["electrician", "electrical"],
    tagline: "Answer the Call First",
    highlight: "On Every Electrical Job That Matters",
    subheadline:
      "From panel upgrades and EV charger installs to same-day outage calls, get exclusive electrician leads filtered by job type and delivered the moment a homeowner needs help.",
    searchChips: ["electrician near me", "panel upgrade cost", "EV charger installation"],
    demoIndustry: "Electrician",
    overviewEyebrow: "The Problem",
    overviewHeading: "Electrical work spans emergency panics and multi-week rewiring projects — and pricing them the same doesn't work",
    overviewParagraphs: [
      "Electrician leads span a wide range: a homeowner with a dead panel who needs someone in the next hour, and a homeowner planning a whole-house rewire or an EV charger install who's comparing quotes over weeks. Treating both like the same lead wastes your dispatcher's time, and in a trade where the first electrician to answer usually books the job, slow-delivered directory leads mean you're losing emergency calls to whoever picks up the phone first.",
      "We split electrician leads by job type and urgency — emergency repair, panel upgrade, rewiring, EV charger installation, inspection — and route true emergencies as live warm transfers so your team can respond while the homeowner is still on the phone. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — emergency repair, panel upgrade, rewiring, EV charger install, or inspection",
      "Live warm transfers for true electrical emergencies that need an answer now",
      "Exclusive delivery, never resold to another electrician in your service area",
      "Filter by residential, commercial, or both based on your crew's focus",
    ],
    faqs: [
      { q: "What electrician job types are available?", a: "Emergency repairs, panel upgrades, full rewiring, EV charger installation, lighting and outlet work, and inspections — filtered by job type so your dispatcher can route calls appropriately." },
      { q: "Can I get emergency electrical calls in real time?", a: "Yes. True emergencies — outages, sparking panels, safety hazards — can be routed as live warm transfers so your team can respond immediately." },
      { q: "Are electrician leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing electrician in your area." },
      { q: "Can I choose residential, commercial, or both?", a: "Yes. Campaigns are configured to your target property type and service area before any leads are delivered." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for phone and address accuracy, and checked against TCPA/DNC lists before delivery." },
    ],
  },
  {
    slug: "kitchen-remodeling-lead-generation",
    label: "Kitchen Remodeling",
    category: "Home Services",
    keywords: ["kitchen remodeling", "kitchen"],
    tagline: "Spend Your Time Closing,",
    highlight: "Not Qualifying Tire-Kickers",
    subheadline:
      "Get exclusive kitchen remodeling leads pre-screened for real budget and project scope, so your design consultants spend their hours with homeowners ready to sign, not window-shoppers.",
    searchChips: ["kitchen remodel cost", "kitchen renovation contractors near me", "custom cabinet installation"],
    demoIndustry: "Kitchen Remodeling",
    overviewEyebrow: "The Problem",
    overviewHeading: "Kitchen remodeling leads take months to close and most are just pricing it out",
    overviewParagraphs: [
      "A kitchen remodel is one of the highest-ticket, highest-consideration purchases a homeowner makes — it's common for months to pass between the first inquiry and a signed contract, and along the way your design consultants field a steady stream of homeowners who are years away from budget-ready, gathering numbers for a project they may never start. Shared lead platforms compound the problem by sending the same homeowner to four or five design-build firms at once, turning a consultative sales process into a price-comparison exercise.",
      "We pre-screen kitchen remodeling leads for real budget range, project scope, and timeline before they ever reach your calendar, so your consultants spend their hours with homeowners who are actually ready to move forward. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers — never resold lists — and verified for real contact info before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for real budget range, project scope, and timeline",
      "Exclusive delivery — never shopped to competing design-build firms",
      "Real-time delivery so your consultants reach homeowners before the competition",
      "Filter by project type — full remodel, cabinet refacing, or countertop/appliance upgrades",
    ],
    faqs: [
      { q: "What kitchen remodeling leads can I buy?", a: "Full kitchen remodels, cabinet refacing and replacement, countertop and appliance upgrades, and layout/design-build projects — filtered by estimated budget and project scope." },
      { q: "Are kitchen remodeling leads exclusive?", a: "Yes. Every lead is sold once, to a single design-build firm or remodeling contractor — never shopped to competitors." },
      { q: "Can I target a specific service area or budget tier?", a: "Yes. Campaigns are built around your service area and can be filtered to a minimum project budget, so you're not paying for jobs below your threshold." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your consultant can reach out while the project is top of mind." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "home-security-lead-generation",
    label: "Home Security",
    category: "Home Services",
    keywords: ["home security", "security"],
    tagline: "Beat the DIY Kits",
    highlight: "With Homeowners Ready for Pro Installation",
    subheadline:
      "Reach homeowners who've outgrown self-install kits and want a monitored system — filtered by property type and install preference, and delivered while they're still comparing providers.",
    searchChips: ["home security system cost", "alarm monitoring companies near me", "smart home security installation"],
    demoIndustry: "Home Security",
    overviewEyebrow: "The Problem",
    overviewHeading: "Home security leads have to compete with a $200 kit from a big-box store",
    overviewParagraphs: [
      "Home security is unlike most home services because the biggest competitor isn't another installer — it's a self-install kit a homeowner can set up in an afternoon. The homeowners worth reaching are the ones who've decided they want professional monitoring, integrated smart-home control, or a system tied to a real contract, not the ones comparison-shopping DIY cameras. Add in genuine hesitation around long-term monitoring contracts and installation fees, and generic ad traffic wastes budget on browsers who were never going to book a pro install.",
      "We filter home security leads by property type, install preference, and monitoring interest so you're reaching homeowners who've already ruled out the DIY route. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before it's delivered exclusively to you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by property type, install preference, and monitoring interest",
      "Pre-screened to exclude DIY-kit shoppers, so you're reaching pro-install prospects",
      "Exclusive delivery — never resold to a competing security provider",
      "Real-time delivery to keep pace with a fast-moving comparison process",
    ],
    faqs: [
      { q: "What home security leads can I buy?", a: "Monitored alarm system installs, smart home and camera integration, video surveillance, and system upgrades or takeovers — filtered by property type and monitoring interest." },
      { q: "Are home security leads exclusive?", a: "Yes. Every lead is sold once, to a single security provider — never resold or shared with a competitor." },
      { q: "Can I target specific states or a service area?", a: "Yes. Campaigns are built around the states, counties, or metro areas you're licensed and equipped to serve." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your sales rep can reach out while they're still comparing providers." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "bathroom-remodeling-lead-generation",
    label: "Bathroom Remodeling",
    category: "Home Services",
    keywords: ["bathroom remodeling", "bathroom"],
    tagline: "Book More Renovations,",
    highlight: "Not More Free Estimates",
    subheadline:
      "Get exclusive bathroom remodeling leads — from fixture refreshes to full gut renovations — pre-screened for real budget and timeline before they ever reach your calendar.",
    searchChips: ["bathroom remodel cost", "walk-in shower conversion", "bathroom renovation contractors near me"],
    demoIndustry: "Bathroom Remodeling",
    overviewEyebrow: "The Problem",
    overviewHeading: "Bathroom remodeling leads sit in the pipeline for months before they're ready to sign",
    overviewParagraphs: [
      "Like kitchens, bathroom remodels are a high-ticket, high-consideration purchase — a homeowner might request quotes for a full gut renovation, a walk-in shower conversion, or an aging-in-place accessibility update, and take months weighing options before committing. Directory leads rarely distinguish between a fixture refresh and a full renovation, so your team wastes estimate visits on jobs below your minimum while shared platforms shop the same lead to every remodeler in town.",
      "We pre-screen bathroom remodeling leads for project scope and real budget range — full renovation, partial update, or accessibility project — before they reach your calendar. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold lists, and verified for real contact info before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for real budget range and project scope",
      "Filter by job type — full renovation, fixture refresh, or accessibility upgrade",
      "Exclusive delivery, never shopped to competing remodelers in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing",
    ],
    faqs: [
      { q: "What bathroom remodeling leads can I buy?", a: "Full renovations, walk-in shower and tub conversions, fixture-only refreshes, and accessibility/aging-in-place upgrades — filtered by project scope and estimated budget." },
      { q: "Are bathroom remodeling leads exclusive?", a: "Yes. Every lead is sold once, to a single remodeling contractor — never shopped to competitors bidding the same job." },
      { q: "Can I target a specific service area or budget tier?", a: "Yes. Campaigns are built around your service area and can be filtered to a minimum project budget." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so you can follow up while they're still deciding." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for contact accuracy, and checked against TCPA/DNC compliance requirements." },
    ],
  },
  {
    slug: "appliance-repair-lead-generation",
    label: "Appliance Repair",
    category: "Home Services",
    keywords: ["appliance repair", "appliance"],
    tagline: "Be the First Call",
    highlight: "Homeowners Book the Same Day",
    subheadline:
      "Get exclusive appliance repair leads — washers, dryers, refrigerators, ovens, and dishwashers — delivered in real time so you're calling before the homeowner tries the next company on the list.",
    searchChips: ["appliance repair near me", "refrigerator not cooling repair", "same day washer repair"],
    demoIndustry: "Appliance Repair",
    overviewEyebrow: "The Problem",
    overviewHeading: "Appliance repair is a same-day business, and the slowest company loses the job",
    overviewParagraphs: [
      "When a refrigerator stops cooling or a washer floods the laundry room, the homeowner is calling every appliance repair company in range and booking whoever calls back first — often within the hour. Directory leads that take hours to reach you are effectively dead on arrival, and a meaningful share of submissions come from renters without authority to approve a repair or homeowners just price-checking before they call their home warranty company instead.",
      "We deliver appliance repair leads in real time, filtered by appliance type and brand, with live warm transfers available so you can be talking to the homeowner while their fridge is still warming up. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by appliance type and brand — washer, dryer, fridge, oven, dishwasher",
      "Live warm transfers for same-day repair requests that need an answer now",
      "Exclusive delivery, never resold to another repair company in your area",
      "Real-time delivery so you're the first call back, not the fourth",
    ],
    faqs: [
      { q: "What appliance repair leads can I buy?", a: "Washer, dryer, refrigerator, oven, range, dishwasher, and small appliance repair — filtered by appliance type, brand, and urgency." },
      { q: "Can I get same-day repair calls in real time?", a: "Yes. Urgent requests can be routed as live warm transfers so your dispatcher can respond immediately." },
      { q: "Are appliance repair leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing repair company." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas your technicians actually cover." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "energy-lead-generation",
    label: "Energy",
    category: "Home Services",
    keywords: ["insulation", "weatherization"],
    tagline: "Turn Rebate Season",
    highlight: "Into Your Busiest Season",
    subheadline:
      "Reach homeowners exploring insulation, air sealing, and efficiency upgrades — filtered by upgrade type and rebate eligibility, and delivered while utility incentives are still driving them to act.",
    searchChips: ["home insulation cost", "attic insulation near me", "energy efficiency rebate programs"],
    demoIndustry: "Energy",
    overviewEyebrow: "The Problem",
    overviewHeading: "Energy efficiency demand rises and falls with rebate deadlines, not the weather",
    overviewParagraphs: [
      "Demand for insulation, air sealing, and weatherization work doesn't move on its own schedule — it spikes when a utility rebate program opens, a tax credit deadline approaches, or a homeowner gets a high winter heating bill, then goes quiet in between. Homeowners researching efficiency upgrades are also easily lumped in with solar shoppers by broad ad campaigns, and many submissions come from people who are years from qualifying for the rebate programs that would actually make the project affordable.",
      "We filter energy efficiency leads by upgrade type — insulation, air sealing, weatherization, efficient HVAC — and rebate eligibility, and scale volume up around the utility incentive windows that actually drive homeowners to act. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by upgrade type — insulation, air sealing, weatherization, or efficient HVAC",
      "Filtered by utility rebate and incentive eligibility, not just interest",
      "Exclusive delivery — never resold to a competing contractor in your territory",
      "Volume scales up around utility rebate windows and seasonal bill spikes",
    ],
    faqs: [
      { q: "What energy efficiency leads can I buy?", a: "Insulation and air sealing, weatherization, attic and duct sealing, window and door efficiency upgrades, and efficient HVAC replacement — filtered by upgrade type and rebate eligibility." },
      { q: "Are energy efficiency leads exclusive?", a: "Yes. Every lead is sold once, to a single contractor — never resold or shared with a competitor in your territory." },
      { q: "Can I target specific utility territories or states?", a: "Yes. Campaigns are built around the states and utility territories where your rebate programs and licensing apply." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so you can follow up while rebate deadlines are still driving their decision." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "handyman-lead-generation",
    label: "Handyman",
    category: "Home Services",
    keywords: ["handyman"],
    tagline: "Fill Your Schedule,",
    highlight: "Without the Middleman Markup",
    subheadline:
      "Get a steady stream of exclusive handyman leads — filtered by task type and job size — so you're never paying directory rates for jobs outside your skillset.",
    searchChips: ["handyman near me", "furniture assembly service", "small home repairs cost"],
    demoIndustry: "Handyman",
    overviewEyebrow: "The Problem",
    overviewHeading: "Handyman jobs are small, which means volume — not price per lead — decides your economics",
    overviewParagraphs: [
      "A handyman business runs on a high volume of small jobs, not a handful of big-ticket sales, so paying premium per-lead rates that make sense for a $20,000 remodel doesn't pencil out for a $150 furniture assembly or a half-day punch list. Directory sites pile on high markups and resell the same job request to multiple handymen, and a good share of submissions are DIY-curious homeowners who were never going to hire out the work.",
      "We deliver handyman leads filtered by task type — carpentry, assembly, painting, general repairs — at volume and price points built for small-job economics, so you can stay booked without directory markups eating your margin. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by task type — carpentry, assembly, painting, and general repairs",
      "Priced and delivered for small-job volume, not big-ticket remodel economics",
      "Exclusive delivery, never resold to a competing handyman in your area",
      "Real-time, mobile-ready delivery so you can respond between jobs",
    ],
    faqs: [
      { q: "What handyman job types can I buy?", a: "Carpentry, furniture assembly, drywall and painting, fixture installs, and general repair and punch-list work — filtered by task type so you're matched to jobs within your skillset." },
      { q: "Are handyman leads exclusive?", a: "Yes. Every lead is sold once, to a single handyman or small business — never resold or shared with a competitor." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or neighborhoods you actually cover." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time, with mobile-ready notifications so you can respond between jobs." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for contact accuracy, and checked against TCPA/DNC compliance requirements." },
    ],
  },
  {
    slug: "junk-removal-lead-generation",
    label: "Junk Removal",
    category: "Home Services",
    keywords: ["junk removal", "junk"],
    tagline: "Book the Job",
    highlight: "Before They Call the Next Hauler",
    subheadline:
      "Get exclusive junk removal leads — from single-item pickups to full estate cleanouts — filtered by job size and delivered in real time while the homeowner is still ready to book.",
    searchChips: ["junk removal near me", "furniture removal cost", "estate cleanout service"],
    demoIndustry: "Junk Removal",
    overviewEyebrow: "The Problem",
    overviewHeading: "Junk removal demand spikes overnight, and the fastest hauler gets the job",
    overviewParagraphs: [
      "Junk removal demand is driven by moments, not planning — a move-out deadline, an estate cleanout, a renovation dumpster that's already full — and most homeowners want it gone today or tomorrow, not next week. That urgency creates a mismatch problem too: a single-item pickup and a full-house cleanout require completely different crew time and truck capacity, but directory leads rarely tell you which one you're getting until you're already on-site.",
      "We filter junk removal leads by job size and type — single item, full load, estate or construction cleanout — and deliver them in real time, with live warm transfers available for same-day requests. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by job size and type — single item, full load, estate, or construction cleanout",
      "Live warm transfers for same-day and next-day pickup requests",
      "Exclusive delivery, never resold to a competing hauler in your market",
      "Real-time delivery so you can book the job before they call the next company",
    ],
    faqs: [
      { q: "What junk removal leads can I buy?", a: "Single-item pickups, full-house and estate cleanouts, construction debris removal, and foreclosure or move-out cleanouts — filtered by job size and type." },
      { q: "Can I get same-day removal requests in real time?", a: "Yes. Urgent, same-day requests can be routed as live warm transfers so your crew can respond immediately." },
      { q: "Are junk removal leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing hauler in your market." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas your trucks actually service." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
];
