import type { SolutionVertical } from "./types";

export const homeServices5: SolutionVertical[] = [
  {
    slug: "water-heater-lead-generation",
    label: "Water Heater",
    category: "Home Services",
    keywords: ["water-heater"],
    tagline: "Water Heater Leads,",
    highlight: "Delivered While It's Still an Emergency",
    subheadline:
      "Connect with homeowners facing a failed water heater or planning a tankless upgrade — filtered by urgency and delivered in real time so you're the first call, not the fourth.",
    searchChips: ["water heater not working", "tankless water heater cost", "water heater replacement near me"],
    demoIndustry: "Water Heater",
    overviewEyebrow: "The Problem",
    overviewHeading: "A cold shower has homeowners calling everyone at once — and slow leads lose that race",
    overviewParagraphs: [
      "Water heater demand splits sharply between two very different buyers: a homeowner with a dead unit and no hot water who needs someone on-site today, and a homeowner weighing a tank replacement against a tankless upgrade on their own timeline. Selling both the same way — or worse, delivering the emergency lead hours late — means losing the fastest-closing jobs in the category to whichever competitor answered the phone first.",
      "We split water heater leads by urgency before they ever reach you. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info, confirmed intent, and project scope, so emergency replacement calls and planned tankless-conversion inquiries route differently, not identically.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by urgency — emergency no-hot-water repair vs. planned replacement or tankless upgrade",
      "Live warm transfers for active failures, so you're talking to the homeowner while the water's still cold",
      "Exclusive delivery — never resold to another plumbing or water heater company in your market",
      "Filter by tank or tankless interest so your team can lead with the right pitch from the first call",
    ],
    faqs: [
      { q: "What types of water heater leads can I buy?", a: "Emergency tank replacement, standard water heater installation, tankless conversions, and routine repair or maintenance calls — filtered so you're not paying full price for a maintenance inquiry when you wanted an emergency replacement lead." },
      { q: "Are water heater leads exclusive to my company?", a: "Yes. Every water heater lead and transfer is sold once, to a single contractor — never resold or shared with a competing plumbing or water heater company in your area." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas your crew actually services." },
      { q: "How fast are water heater leads delivered?", a: "Emergency no-hot-water leads can be routed as live warm transfers for an immediate connection; standard replacement and tankless-upgrade leads deliver in real time as homeowners submit." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery, so you're calling a real homeowner with a genuine water heater need." },
    ],
  },
  {
    slug: "foundation-repair-lead-generation",
    label: "Foundation Repair",
    category: "Home Services",
    keywords: ["foundation-repair", "foundation"],
    tagline: "Foundation Repair Leads,",
    highlight: "From Homeowners Who Already Trust the Process",
    subheadline:
      "Reach homeowners dealing with real structural warning signs — cracks, uneven floors, sticking doors — pre-screened for genuine concern so your team isn't starting every call from scratch convincing a skeptic.",
    searchChips: ["foundation crack repair cost", "house settling signs", "foundation inspection near me"],
    demoIndustry: "Foundation Repair",
    overviewEyebrow: "The Problem",
    overviewHeading: "Foundation repair is a high-ticket sell to homeowners who've been burned by scare tactics",
    overviewParagraphs: [
      "Foundation repair carries some of the highest average ticket sizes in home services, which makes it one of the most trust-sensitive categories to sell into. Homeowners who spot a crack have usually already braced for a worst-case pitch, and a wave of scare-tactic marketing in this space has made many wary of committing before they trust the contractor in front of them. Add a sales cycle that often runs a week or more, plus real estate deals that hinge on repairs being completed or credited before closing, and generic leads with no confirmed symptoms or timeline just waste expensive estimator hours.",
      "We deliver foundation repair leads built around genuine structural concern, not a vague \"home repair\" interest checkbox. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info, confirmed warning signs, and project intent before it reaches your estimators.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads confirmed with real warning signs — cracking, settling, uneven floors, or sticking doors/windows",
      "Exclusive delivery, never resold to another foundation repair contractor in your market",
      "Filter by real estate transaction leads (pre-sale inspection repairs) vs. standard homeowner inquiries",
      "Real-time delivery so your estimator can schedule the inspection while trust and urgency are highest",
    ],
    faqs: [
      { q: "What types of foundation repair leads can I buy?", a: "Foundation cracking and settling repair, structural stabilization work (push piers, helical piers, slab jacking), and inspection requests tied to a home sale — filtered so you're not fielding generic \"home repair\" leads outside your scope." },
      { q: "Are foundation repair leads exclusive to my company?", a: "Yes. Every foundation repair lead is sold once, to a single contractor — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific counties or a service radius?", a: "Yes. Campaigns are built around the counties or metro areas you actually service, including targeting toward regions with expansive clay soils or drought-flood cycles where foundation movement is more common." },
      { q: "How fast are foundation repair leads delivered?", a: "Standard leads deliver in real time as homeowners submit; live warm transfers are available for homeowners who want to speak with a specialist immediately about visible damage." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks — plus confirmation of the specific warning signs the homeowner has noticed — before it's ever delivered." },
    ],
  },
  {
    slug: "chimney-lead-generation",
    label: "Chimney Services",
    category: "Home Services",
    keywords: ["chimney"],
    tagline: "Book Your Fall Season Solid",
    highlight: "With Exclusive Chimney Leads",
    subheadline:
      "Get homeowner leads for sweeping, inspection, and masonry repair — filtered by service type so a routine cleaning and a major rebuild never get treated the same, and delivered ahead of your peak fall surge.",
    searchChips: ["chimney sweep near me", "chimney inspection cost", "chimney repair and masonry"],
    demoIndustry: "Chimney Services",
    overviewEyebrow: "The Problem",
    overviewHeading: "Chimney demand spikes hard every fall — and swings from a routine sweep to a full rebuild",
    overviewParagraphs: [
      "Chimney services span two very different businesses under one roof: routine sweeping and inspection work that homeowners book every fall before lighting the first fire, and major masonry or structural repair triggered by visible damage that carries a far higher ticket and a longer sales cycle. Demand concentrates so heavily into a few months that competition — and lead pricing — spikes right when volume matters most, and generic leads that don't distinguish a routine cleaning request from an urgent repair leave crews either overbooked on low-ticket work or blind to the higher-value jobs sitting in the same list.",
      "We filter chimney leads by service type before they reach you. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info and confirmed intent, so sweeping and inspection requests route separately from masonry and structural repair inquiries.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by service type — sweeping/inspection vs. masonry and structural repair",
      "Exclusive delivery, never resold to another chimney company in your market",
      "Volume that scales up ahead of the fall surge and pulls back in the off-season",
      "Real-time delivery so you can book the appointment while the homeowner is still planning for winter",
    ],
    faqs: [
      { q: "What types of chimney leads can I buy?", a: "Chimney sweeping and inspection, masonry and structural repair, and home-purchase inspection requests — filtered so a routine seasonal cleaning and a major repair job aren't priced or routed the same way." },
      { q: "Are chimney leads exclusive to my company?", a: "Yes. Every chimney lead is sold once, to a single company — never resold or shared with a competitor in your service area." },
      { q: "Can I target a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually service, with volume you can scale up heading into the fall season." },
      { q: "How fast are chimney leads delivered?", a: "Leads deliver in real time as homeowners submit, so you can lock in appointments before the fall booking calendar fills up. Live warm transfers are available for urgent repair calls involving visible damage or odor." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery, and includes enough detail to tell a routine maintenance request from an urgent repair." },
    ],
  },
  {
    slug: "driveway-paving-lead-generation",
    label: "Driveway & Paving",
    category: "Home Services",
    keywords: ["driveway", "paving"],
    tagline: "Fill Your Paving Calendar",
    highlight: "Before the Season Books Solid",
    subheadline:
      "Get exclusive leads for driveway paving, resurfacing, and sealcoating — filtered by material preference and approximate size so a small patch job and a full concrete replacement never price the same.",
    searchChips: ["driveway paving cost", "asphalt vs concrete driveway", "driveway resurfacing near me"],
    demoIndustry: "Driveway & Paving",
    overviewEyebrow: "The Problem",
    overviewHeading: "Paving is a short season with huge swings in price depending on the material",
    overviewParagraphs: [
      "Driveway and paving work is heavily seasonal — most regions compress installation into spring and summer, so demand and competition for the same homeowners peak all at once. On top of that, a \"driveway lead\" can mean almost anything: a small asphalt patch, a full-depth removal and replacement, a concrete pour, or a paver installation, each with dramatically different project values. Buying leads at a flat volume without knowing material preference, approximate size, or existing driveway condition means bidding blind and underquoting jobs that turn out to need far more work than expected.",
      "We qualify driveway and paving leads on the details that actually move price — material preference, approximate driveway size, and current condition — before they reach you. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info and genuine project intent.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by material preference — asphalt, concrete, or pavers — and approximate driveway size",
      "Exclusive delivery, never resold to another paving company in your market",
      "Volume that scales up for your peak spring/summer season and pulls back in the off-season",
      "Real-time delivery so you can quote while the homeowner is still comparing bids",
    ],
    faqs: [
      { q: "What types of driveway and paving leads can I buy?", a: "New driveway installation, full replacement, resurfacing/overlay, and sealcoating — filtered by asphalt, concrete, or paver preference so you're not quoting blind on material or scope." },
      { q: "Are driveway and paving leads exclusive to my company?", a: "Yes. Every driveway and paving lead is sold once, to a single company — never resold or shared with a competitor in your market." },
      { q: "Can I target a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or counties you actually service, with volume you can ramp up heading into your peak paving season." },
      { q: "How fast are driveway and paving leads delivered?", a: "Leads deliver in real time as homeowners submit, which matters most early in the season when calendars fill up fast." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery, and captures material preference and approximate size so you can quote accurately." },
    ],
  },
  {
    slug: "sprinkler-irrigation-lead-generation",
    label: "Sprinkler & Irrigation",
    category: "Home Services",
    keywords: ["sprinkler", "irrigation"],
    tagline: "Sprinkler & Irrigation Leads,",
    highlight: "Timed to Your Spring and Fall Surges",
    subheadline:
      "Get exclusive leads for new irrigation installs, repairs, and seasonal startup/winterization — filtered by property size and service type so you can staff for the surge instead of guessing.",
    searchChips: ["sprinkler system installation cost", "sprinkler repair near me", "sprinkler winterization service"],
    demoIndustry: "Sprinkler & Irrigation",
    overviewEyebrow: "The Problem",
    overviewHeading: "Irrigation demand is narrow, seasonal, and split between installs and service",
    overviewParagraphs: [
      "Sprinkler and irrigation is a narrower niche than most home services categories, and it splits into two distinct businesses: new system installation, priced by property size and zone count, and seasonal startup and winterization service, which spikes hard every spring and fall. A poorly winterized system also drives a wave of emergency repair calls each spring when homeowners discover frozen, burst pipes — a predictable surge that generic, unfiltered leads don't help you plan for.",
      "We split irrigation leads by type before they reach you — new installation, repair, and seasonal startup/winterization route separately, since they carry different project values and urgency. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info and genuine project intent.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by type — new installation, repair, or seasonal startup/winterization",
      "Exclusive delivery, never resold to another irrigation contractor in your market",
      "Volume that scales up for your spring and fall service surges",
      "Real-time delivery so you can book while the homeowner is still planning the season",
    ],
    faqs: [
      { q: "What types of sprinkler and irrigation leads can I buy?", a: "New irrigation system installation, repair (including spring burst-pipe emergencies from improper winterization), and seasonal startup or winterization service — filtered so you're not paying the same rate for a full install and a routine seasonal visit." },
      { q: "Are sprinkler and irrigation leads exclusive to my company?", a: "Yes. Every sprinkler and irrigation lead is sold once, to a single contractor — never resold or shared with a competitor in your service area." },
      { q: "Can I target a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually service, with volume you can plan around your spring and fall surges." },
      { q: "How fast are sprinkler and irrigation leads delivered?", a: "Leads deliver in real time as homeowners submit, which matters most during the tight spring startup and fall winterization windows when calendars fill fast." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery, and captures property size and service type so you can staff and quote accurately." },
    ],
  },
];
