import {
  Home,
  Building2,
  Bug,
  Leaf,
  Layers,
  HardHat,
  Zap,
  BatteryCharging,
  Hammer,
  Camera,
  Lock,
  Accessibility,
  Award,
  Wrench,
  Gauge,
  Thermometer,
  KeyRound,
  Package,
  Truck,
} from "lucide-react";
import type { SolutionVertical } from "./types";

export const homeServices2: SolutionVertical[] = [
  {
    slug: "pest-control-lead-generation",
    label: "Pest Control",
    category: "Home Services",
    keywords: ["pest control", "pest"],
    tagline: "Book More Treatments,",
    highlight: "From First Call to Recurring Contract",
    subheadline:
      "Get exclusive pest control leads — from one-time ant and roach treatments to full-year recurring contracts — filtered by pest type and delivered while the homeowner is still searching.",
    searchChips: ["pest control near me", "termite inspection cost", "ant exterminator same day"],
    demoIndustry: "Pest Control",
    overviewEyebrow: "The Problem",
    overviewHeading: "Pest control leads swing between $89 one-time sprays and $600 annual contracts",
    overviewParagraphs: [
      "A \"pest control lead\" could be a one-time ant spray or a full year-round contract with quarterly visits — and the two have completely different economics, so paying flat rates for both erodes your margin. Demand is also brutally seasonal: termite swarms in spring, ants and wasps in summer, rodents moving indoors in fall, which means the same directory that's too slow in June leaves you idle in February. On top of that, aggregator sites resell the same homeowner to five competing companies, so the exterminator who calls back first — not necessarily the best one — wins the job.",
      "We fix that by filtering every pest control lead by pest type and service type — one-time treatment versus recurring contract — before it reaches you. Leads are captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold lists or aggregator leftovers, then screened for real contact info, real intent, and a real pest issue before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by pest type and service type — one-time treatment or recurring contract",
      "Exclusive delivery — never resold to a competing pest control company in your market",
      "Real-time delivery so you can call back before the homeowner tries the next exterminator",
      "Volume scales up for seasonal pest spikes — termites in spring, ants in summer, rodents in fall",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect pest control companies with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Pest Control Customer", detail: "We qualify by pest type, property type, one-time versus recurring service interest, and the ZIP codes or counties you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and a real pest issue before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Routine treatment requests deliver as web-form leads; active infestations like wasp nests, rodent intrusions, or termite swarms route as live warm transfers so your dispatcher can respond immediately." },
      { title: "Scale With the Season", detail: "Volume ramps for termite swarm season in spring, ants and wasps in summer, and rodents moving indoors in fall, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Pest Control Leads",
    whoBenefitsSubheading: "From single-tech operators to national pest brands, here's who buys pest control leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Pest Control Companies", detail: "Independent exterminators filling their route with treatments in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Pest Control Franchises & Multi-Branch Companies", detail: "National and regional brands distributing volume across branches and technician routes." },
      { tag: "Termite Specialists", icon: Bug, title: "Termite & Wildlife Specialists", detail: "Companies focused on higher-ticket termite inspection, treatment, and wildlife removal work." },
      { tag: "Adjacent Trades", icon: Leaf, title: "Lawn Care Companies Adding Pest Control", detail: "Lawn and landscape businesses expanding into pest treatment without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What types of pest control leads can I buy?", a: "One-time treatments (ants, roaches, wasps, spiders), termite inspections and treatment, rodent and wildlife removal, bed bug treatment, and recurring quarterly or annual contracts — filtered so you're only paying for the service types you actually offer." },
      { q: "Are pest control leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single pest control company — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually service, so you're not paying to chase jobs outside your route." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit. Warm transfers connect you live, on the phone, while the homeowner still has the pest problem in front of them." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered — so you're calling a real homeowner with a real pest issue, not a bot or duplicate." },
    ],
  },
  {
    slug: "flooring-lead-generation",
    label: "Flooring",
    category: "Home Services",
    keywords: ["flooring", "floor"],
    tagline: "Fill Your Install Calendar",
    highlight: "With Homeowners Ready to Choose Materials",
    subheadline:
      "Connect with homeowners actively comparing hardwood, tile, LVP, and carpet — filtered by material interest and project scope, and delivered while they're still deciding, not just dreaming.",
    searchChips: ["flooring installation cost", "hardwood vs laminate flooring", "flooring contractors near me"],
    demoIndustry: "Flooring",
    overviewEyebrow: "The Problem",
    overviewHeading: "Flooring leads take weeks to close and most never make it past the sample stage",
    overviewParagraphs: [
      "Flooring is a material-selection business first and a sales business second — a homeowner comparing hardwood, tile, LVP, and carpet swatches can take weeks or months before they're ready to sign, and a large share of directory leads are still in the browsing phase, not the buying phase. Shared lead platforms make it worse by selling the same homeowner to every flooring contractor in the market, turning a considered purchase into a race-to-the-bottom bidding war on price alone.",
      "We filter flooring leads by material interest and project scope — whole-home versus single-room, replacement versus new install — so your estimators are quoting homeowners who've already narrowed their choice, not starting from zero. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real project scope before it's delivered exclusively to you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by material interest — hardwood, tile, LVP, or carpet",
      "Exclusive delivery, never resold to a competing flooring contractor in your area",
      "Filtered by project scope — whole-home replacement or single-room install",
      "Real-time delivery so you're quoting while the homeowner is still comparing samples",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect flooring contractors with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Flooring Customer", detail: "We qualify by material interest, project scope, property type, and the ZIP codes or counties you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and real intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Single-room jobs deliver as web-form leads; whole-home or higher-budget projects route as inbound calls or live warm transfers so your estimator can walk through material options directly." },
      { title: "Scale With Renovation Season", detail: "Volume ramps with spring and summer moving season and the post-holiday remodel push, and pulls back in slower months." },
    ],
    whoBenefitsHeading: "Who Benefits From Flooring Leads",
    whoBenefitsSubheading: "From single-crew installers to multi-location flooring retailers, here's who buys flooring leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Flooring Contractors", detail: "Independent installers filling their calendar with residential flooring jobs in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Flooring Franchises & Multi-Location Retailers", detail: "Regional and national flooring brands distributing installation volume across showroom locations." },
      { tag: "Specialty Installers", icon: Layers, title: "Hardwood & Tile Specialty Installers", detail: "Installers focused on higher-ticket refinishing and custom tile work who want pre-qualified material interest." },
      { tag: "Remodelers", icon: HardHat, title: "General Contractors & Remodelers Adding Flooring", detail: "Remodeling companies expanding into flooring installation without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What flooring job types can I target?", a: "Hardwood, tile, luxury vinyl plank, carpet, and laminate installs, plus refinishing and repair work — filtered by material interest and whether it's a single room or whole-home project." },
      { q: "Are flooring leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single flooring contractor — never resold or shared with a competitor in the same market." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually install in." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your estimator can follow up while material preferences are still fresh." },
      { q: "How is lead quality verified?", a: "Every submission goes through fraud screening, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "electrician-lead-generation",
    label: "Electrician",
    category: "Home Services",
    keywords: ["electrician", "electrical"],
    tagline: "Answer the Call First",
    highlight: "On Every Electrical Job That Matters",
    subheadline:
      "From panel upgrades and EV charger installs to same-day outage calls, get exclusive electrician leads filtered by job type and delivered the moment a homeowner needs help.",
    searchChips: ["electrician near me", "panel upgrade cost", "EV charger installation"],
    demoIndustry: "Electrician",
    overviewEyebrow: "The Problem",
    overviewHeading: "Electrical work spans emergency panics and multi-week rewiring projects — and pricing them the same doesn't work",
    overviewParagraphs: [
      "Electrician leads span a wide range: a homeowner with a dead panel who needs someone in the next hour, and a homeowner planning a whole-house rewire or an EV charger install who's comparing quotes over weeks. Treating both like the same lead wastes your dispatcher's time, and in a trade where the first electrician to answer usually books the job, slow-delivered directory leads mean you're losing emergency calls to whoever picks up the phone first.",
      "We split electrician leads by job type and urgency — emergency repair, panel upgrade, rewiring, EV charger installation, inspection — and route true emergencies as live warm transfers so your team can respond while the homeowner is still on the phone. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — emergency repair, panel upgrade, rewiring, EV charger install, or inspection",
      "Live warm transfers for true electrical emergencies that need an answer now",
      "Exclusive delivery, never resold to another electrician in your service area",
      "Filter by residential, commercial, or both based on your crew's focus",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We route electrical demand to your team as leads, live warm transfers, or inbound calls — matched to how urgent the job is.",
    howItWorksSteps: [
      { title: "Define Your Ideal Electrician Customer", detail: "We qualify by job type, property type, budget, and the service area your crews actually cover." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real intent the moment it's captured, before it's counted as a lead." },
      { title: "Choose Your Delivery", detail: "Panel upgrades, rewiring, and EV charger installs deliver as web-form leads; outages and sparking-panel emergencies route as live warm transfers so your dispatcher can respond immediately." },
      { title: "Scale With Demand", detail: "Volume ramps with EV adoption surges and storm-driven outage spikes, and pulls back in quieter stretches, without a new contract each time." },
    ],
    whoBenefitsHeading: "Who Benefits From Electrician Leads",
    whoBenefitsSubheading: "From single-truck electricians to multi-branch service companies, here's who buys electrician leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Electrical Contractors", detail: "Independent electricians filling their schedule within a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Electrical Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing volume across branches and dispatch zones." },
      { tag: "Emergency Service", icon: Zap, title: "24/7 Emergency Electricians", detail: "Companies built around fast response to outages and safety hazards that need a live transfer, not a form." },
      { tag: "EV & Solar", icon: BatteryCharging, title: "EV Charger & Solar Panel Installers", detail: "Electricians expanding into EV charger installation and solar-tied electrical work." },
    ],
    faqs: [
      { q: "What electrician job types are available?", a: "Emergency repairs, panel upgrades, full rewiring, EV charger installation, lighting and outlet work, and inspections — filtered by job type so your dispatcher can route calls appropriately." },
      { q: "Can I get emergency electrical calls in real time?", a: "Yes. True emergencies — outages, sparking panels, safety hazards — can be routed as live warm transfers so your team can respond immediately." },
      { q: "Are electrician leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing electrician in your area." },
      { q: "Can I choose residential, commercial, or both?", a: "Yes. Campaigns are configured to your target property type and service area before any leads are delivered." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for phone and address accuracy, and checked against TCPA/DNC lists before delivery." },
    ],
  },
  {
    slug: "kitchen-remodeling-lead-generation",
    label: "Kitchen Remodeling",
    category: "Home Services",
    keywords: ["kitchen remodeling", "kitchen"],
    tagline: "Spend Your Time Closing,",
    highlight: "Not Qualifying Tire-Kickers",
    subheadline:
      "Get exclusive kitchen remodeling leads pre-screened for real budget and project scope, so your design consultants spend their hours with homeowners ready to sign, not window-shoppers.",
    searchChips: ["kitchen remodel cost", "kitchen renovation contractors near me", "custom cabinet installation"],
    demoIndustry: "Kitchen Remodeling",
    overviewEyebrow: "The Problem",
    overviewHeading: "Kitchen remodeling leads take months to close and most are just pricing it out",
    overviewParagraphs: [
      "A kitchen remodel is one of the highest-ticket, highest-consideration purchases a homeowner makes — it's common for months to pass between the first inquiry and a signed contract, and along the way your design consultants field a steady stream of homeowners who are years away from budget-ready, gathering numbers for a project they may never start. Shared lead platforms compound the problem by sending the same homeowner to four or five design-build firms at once, turning a consultative sales process into a price-comparison exercise.",
      "We pre-screen kitchen remodeling leads for real budget range, project scope, and timeline before they ever reach your calendar, so your consultants spend their hours with homeowners who are actually ready to move forward. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers — never resold lists — and verified for real contact info before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for real budget range, project scope, and timeline",
      "Exclusive delivery — never shopped to competing design-build firms",
      "Real-time delivery so your consultants reach homeowners before the competition",
      "Filter by project type — full remodel, cabinet refacing, or countertop/appliance upgrades",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect kitchen remodeling firms with homeowners ready to invest — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Kitchen Remodeling Customer", detail: "We qualify by budget range, project scope, timeline, and the ZIP codes or counties you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is screened for real budget, homeownership, and intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard inquiries deliver as web-form leads; full-remodel and higher-budget projects route as inbound calls or live warm transfers straight to your design consultants." },
      { title: "Scale With Demand", detail: "Volume ramps with the fall and winter project-planning season and the spring and summer construction push, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Kitchen Remodeling Leads",
    whoBenefitsSubheading: "From single-crew design-build firms to multi-location remodeling brands, here's who buys kitchen remodeling leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Kitchen Remodeling Contractors", detail: "Independent design-build firms filling their calendar with remodels in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Design-Build Franchises & Multi-Location Firms", detail: "Regional and national remodeling brands distributing consultation volume across locations." },
      { tag: "Custom Specialists", icon: Hammer, title: "Custom Cabinet & High-End Remodel Specialists", detail: "Firms focused on higher-ticket full gut renovations who need pre-screened budget and scope." },
      { tag: "General Contractors", icon: HardHat, title: "General Contractors Adding Kitchen Remodeling", detail: "Construction companies expanding into kitchen design-build work without building their own pipeline first." },
    ],
    faqs: [
      { q: "What kitchen remodeling leads can I buy?", a: "Full kitchen remodels, cabinet refacing and replacement, countertop and appliance upgrades, and layout/design-build projects — filtered by estimated budget and project scope." },
      { q: "Are kitchen remodeling leads exclusive?", a: "Yes. Every lead is sold once, to a single design-build firm or remodeling contractor — never shopped to competitors." },
      { q: "Can I target a specific service area or budget tier?", a: "Yes. Campaigns are built around your service area and can be filtered to a minimum project budget, so you're not paying for jobs below your threshold." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your consultant can reach out while the project is top of mind." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "home-security-lead-generation",
    label: "Home Security",
    category: "Home Services",
    keywords: ["home security", "security"],
    tagline: "Beat the DIY Kits",
    highlight: "With Homeowners Ready for Pro Installation",
    subheadline:
      "Reach homeowners who've outgrown self-install kits and want a monitored system — filtered by property type and install preference, and delivered while they're still comparing providers.",
    searchChips: ["home security system cost", "alarm monitoring companies near me", "smart home security installation"],
    demoIndustry: "Home Security",
    overviewEyebrow: "The Problem",
    overviewHeading: "Home security leads have to compete with a $200 kit from a big-box store",
    overviewParagraphs: [
      "Home security is unlike most home services because the biggest competitor isn't another installer — it's a self-install kit a homeowner can set up in an afternoon. The homeowners worth reaching are the ones who've decided they want professional monitoring, integrated smart-home control, or a system tied to a real contract, not the ones comparison-shopping DIY cameras. Add in genuine hesitation around long-term monitoring contracts and installation fees, and generic ad traffic wastes budget on browsers who were never going to book a pro install.",
      "We filter home security leads by property type, install preference, and monitoring interest so you're reaching homeowners who've already ruled out the DIY route. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before it's delivered exclusively to you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by property type, install preference, and monitoring interest",
      "Pre-screened to exclude DIY-kit shoppers, so you're reaching pro-install prospects",
      "Exclusive delivery — never resold to a competing security provider",
      "Real-time delivery to keep pace with a fast-moving comparison process",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect home security providers with homeowners ready for pro installation — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Home Security Customer", detail: "We qualify by property type, install preference, monitoring interest, and the states or metro areas you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Interest is captured on owned pages or vetted publisher sites, then screened to exclude DIY-kit shoppers before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard inquiries deliver as web-form leads; homeowners ready to commit to a monitored system route as live warm transfers or inbound calls so your rep can close while they're on the phone." },
      { title: "Scale With Demand", detail: "Volume flexes with home-buying season and local demand spikes after break-ins or severe weather, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Home Security Leads",
    whoBenefitsSubheading: "From local install dealers to national monitoring brands, here's who buys home security leads from Eilite.",
    whoBenefits: [
      { tag: "Local Installers", icon: Home, title: "Local Home Security Installers", detail: "Independent dealers filling their install schedule within a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Security Franchises & Multi-Branch Dealers", detail: "Regional and national brands distributing installation volume across branches and territories." },
      { tag: "Smart Home", icon: Camera, title: "Smart Home & Camera Integration Specialists", detail: "Companies focused on higher-ticket integrated systems beyond basic alarm monitoring." },
      { tag: "Monitoring Companies", icon: Lock, title: "Monitoring Companies Adding Installation", detail: "Alarm monitoring providers expanding into pro-install services without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What home security leads can I buy?", a: "Monitored alarm system installs, smart home and camera integration, video surveillance, and system upgrades or takeovers — filtered by property type and monitoring interest." },
      { q: "Are home security leads exclusive?", a: "Yes. Every lead is sold once, to a single security provider — never resold or shared with a competitor." },
      { q: "Can I target specific states or a service area?", a: "Yes. Campaigns are built around the states, counties, or metro areas you're licensed and equipped to serve." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so your sales rep can reach out while they're still comparing providers." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "bathroom-remodeling-lead-generation",
    label: "Bathroom Remodeling",
    category: "Home Services",
    keywords: ["bathroom remodeling", "bathroom"],
    tagline: "Book More Renovations,",
    highlight: "Not More Free Estimates",
    subheadline:
      "Get exclusive bathroom remodeling leads — from fixture refreshes to full gut renovations — pre-screened for real budget and timeline before they ever reach your calendar.",
    searchChips: ["bathroom remodel cost", "walk-in shower conversion", "bathroom renovation contractors near me"],
    demoIndustry: "Bathroom Remodeling",
    overviewEyebrow: "The Problem",
    overviewHeading: "Bathroom remodeling leads sit in the pipeline for months before they're ready to sign",
    overviewParagraphs: [
      "Like kitchens, bathroom remodels are a high-ticket, high-consideration purchase — a homeowner might request quotes for a full gut renovation, a walk-in shower conversion, or an aging-in-place accessibility update, and take months weighing options before committing. Directory leads rarely distinguish between a fixture refresh and a full renovation, so your team wastes estimate visits on jobs below your minimum while shared platforms shop the same lead to every remodeler in town.",
      "We pre-screen bathroom remodeling leads for project scope and real budget range — full renovation, partial update, or accessibility project — before they reach your calendar. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold lists, and verified for real contact info before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for real budget range and project scope",
      "Filter by job type — full renovation, fixture refresh, or accessibility upgrade",
      "Exclusive delivery, never shopped to competing remodelers in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect bathroom remodeling firms with homeowners ready to invest — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Bathroom Remodeling Customer", detail: "We qualify by budget range, project scope, timeline, and the ZIP codes or counties you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is screened for real budget, homeownership, and intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Fixture refreshes and smaller jobs deliver as web-form leads; full gut renovations and accessibility projects route as inbound calls or live warm transfers straight to your consultants." },
      { title: "Scale With Demand", detail: "Volume ramps with the fall and winter remodel-planning season and steady aging-in-place demand, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Bathroom Remodeling Leads",
    whoBenefitsSubheading: "From single-crew remodelers to multi-location renovation brands, here's who buys bathroom remodeling leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Bathroom Remodeling Contractors", detail: "Independent remodelers filling their calendar with renovations in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Remodeling Franchises & Multi-Location Firms", detail: "Regional and national brands distributing consultation volume across locations." },
      { tag: "Accessibility Specialists", icon: Accessibility, title: "Walk-In Shower & Aging-in-Place Specialists", detail: "Companies focused on accessibility conversions and safety upgrades for aging-in-place homeowners." },
      { tag: "General Contractors", icon: HardHat, title: "General Contractors Adding Bathroom Remodeling", detail: "Construction companies expanding into bathroom design-build work without building their own pipeline first." },
    ],
    faqs: [
      { q: "What bathroom remodeling leads can I buy?", a: "Full renovations, walk-in shower and tub conversions, fixture-only refreshes, and accessibility/aging-in-place upgrades — filtered by project scope and estimated budget." },
      { q: "Are bathroom remodeling leads exclusive?", a: "Yes. Every lead is sold once, to a single remodeling contractor — never shopped to competitors bidding the same job." },
      { q: "Can I target a specific service area or budget tier?", a: "Yes. Campaigns are built around your service area and can be filtered to a minimum project budget." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so you can follow up while they're still deciding." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for contact accuracy, and checked against TCPA/DNC compliance requirements." },
    ],
  },
  {
    slug: "appliance-repair-lead-generation",
    label: "Appliance Repair",
    category: "Home Services",
    keywords: ["appliance repair", "appliance"],
    tagline: "Be the First Call",
    highlight: "Homeowners Book the Same Day",
    subheadline:
      "Get exclusive appliance repair leads — washers, dryers, refrigerators, ovens, and dishwashers — delivered in real time so you're calling before the homeowner tries the next company on the list.",
    searchChips: ["appliance repair near me", "refrigerator not cooling repair", "same day washer repair"],
    demoIndustry: "Appliance Repair",
    overviewEyebrow: "The Problem",
    overviewHeading: "Appliance repair is a same-day business, and the slowest company loses the job",
    overviewParagraphs: [
      "When a refrigerator stops cooling or a washer floods the laundry room, the homeowner is calling every appliance repair company in range and booking whoever calls back first — often within the hour. Directory leads that take hours to reach you are effectively dead on arrival, and a meaningful share of submissions come from renters without authority to approve a repair or homeowners just price-checking before they call their home warranty company instead.",
      "We deliver appliance repair leads in real time, filtered by appliance type and brand, with live warm transfers available so you can be talking to the homeowner while their fridge is still warming up. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by appliance type and brand — washer, dryer, fridge, oven, dishwasher",
      "Live warm transfers for same-day repair requests that need an answer now",
      "Exclusive delivery, never resold to another repair company in your area",
      "Real-time delivery so you're the first call back, not the fourth",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We route appliance repair demand to your team as leads, live warm transfers, or inbound calls — matched to how urgent the job is.",
    howItWorksSteps: [
      { title: "Define Your Ideal Appliance Repair Customer", detail: "We qualify by appliance type, brand, property type, and the ZIP codes or metro areas your technicians actually cover." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud, homeownership, and real intent before it's counted as a lead." },
      { title: "Choose Your Delivery", detail: "Standard repair requests deliver as web-form leads; same-day breakdowns like a warm fridge or a flooding washer route as live warm transfers so your dispatcher can respond immediately." },
      { title: "Scale With Demand", detail: "Volume flexes with summer refrigeration breakdowns and holiday-season oven and dishwasher spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Appliance Repair Leads",
    whoBenefitsSubheading: "From single-tech operators to multi-branch repair companies, here's who buys appliance repair leads from Eilite.",
    whoBenefits: [
      { tag: "Local Technicians", icon: Home, title: "Local Appliance Repair Technicians", detail: "Independent technicians filling their schedule with repair calls in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Appliance Repair Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing dispatch volume across branches and technician routes." },
      { tag: "Authorized Repair", icon: Award, title: "Brand-Authorized & Warranty Repair Specialists", detail: "Technicians certified on specific brands who need leads filtered by appliance type and warranty status." },
      { tag: "Adjacent Trades", icon: Wrench, title: "HVAC & Handyman Companies Adding Appliance Repair", detail: "Home service businesses expanding into appliance repair without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What appliance repair leads can I buy?", a: "Washer, dryer, refrigerator, oven, range, dishwasher, and small appliance repair — filtered by appliance type, brand, and urgency." },
      { q: "Can I get same-day repair calls in real time?", a: "Yes. Urgent requests can be routed as live warm transfers so your dispatcher can respond immediately." },
      { q: "Are appliance repair leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing repair company." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas your technicians actually cover." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "energy-lead-generation",
    label: "Energy",
    category: "Home Services",
    keywords: ["insulation", "weatherization"],
    tagline: "Turn Rebate Season",
    highlight: "Into Your Busiest Season",
    subheadline:
      "Reach homeowners exploring insulation, air sealing, and efficiency upgrades — filtered by upgrade type and rebate eligibility, and delivered while utility incentives are still driving them to act.",
    searchChips: ["home insulation cost", "attic insulation near me", "energy efficiency rebate programs"],
    demoIndustry: "Energy",
    overviewEyebrow: "The Problem",
    overviewHeading: "Energy efficiency demand rises and falls with rebate deadlines, not the weather",
    overviewParagraphs: [
      "Demand for insulation, air sealing, and weatherization work doesn't move on its own schedule — it spikes when a utility rebate program opens, a tax credit deadline approaches, or a homeowner gets a high winter heating bill, then goes quiet in between. Homeowners researching efficiency upgrades are also easily lumped in with solar shoppers by broad ad campaigns, and many submissions come from people who are years from qualifying for the rebate programs that would actually make the project affordable.",
      "We filter energy efficiency leads by upgrade type — insulation, air sealing, weatherization, efficient HVAC — and rebate eligibility, and scale volume up around the utility incentive windows that actually drive homeowners to act. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by upgrade type — insulation, air sealing, weatherization, or efficient HVAC",
      "Filtered by utility rebate and incentive eligibility, not just interest",
      "Exclusive delivery — never resold to a competing contractor in your territory",
      "Volume scales up around utility rebate windows and seasonal bill spikes",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect energy efficiency contractors with homeowners ready to upgrade — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Energy Efficiency Customer", detail: "We qualify by upgrade type, rebate eligibility, property type, and the states or utility territories you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for real intent and rebate eligibility before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard upgrade inquiries deliver as web-form leads; rebate-deadline-driven and whole-home projects route as inbound calls or live warm transfers so your energy auditor can lock in the appointment." },
      { title: "Scale With Demand", detail: "Volume ramps around utility rebate windows, tax credit deadlines, and winter heating-bill spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Energy Efficiency Leads",
    whoBenefitsSubheading: "From local weatherization crews to multi-branch efficiency companies, here's who buys energy efficiency leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Insulation & Weatherization Contractors", detail: "Independent crews filling their schedule with efficiency upgrades in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Energy Efficiency Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing volume across branches and territories." },
      { tag: "Energy Auditors", icon: Gauge, title: "Utility Rebate & Energy Audit Specialists", detail: "Companies focused on rebate-qualified audits and whole-home efficiency assessments." },
      { tag: "HVAC Contractors", icon: Thermometer, title: "HVAC Contractors Adding Efficiency Upgrades", detail: "HVAC companies expanding into insulation and air sealing work without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What energy efficiency leads can I buy?", a: "Insulation and air sealing, weatherization, attic and duct sealing, window and door efficiency upgrades, and efficient HVAC replacement — filtered by upgrade type and rebate eligibility." },
      { q: "Are energy efficiency leads exclusive?", a: "Yes. Every lead is sold once, to a single contractor — never resold or shared with a competitor in your territory." },
      { q: "Can I target specific utility territories or states?", a: "Yes. Campaigns are built around the states and utility territories where your rebate programs and licensing apply." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time as homeowners submit, so you can follow up while rebate deadlines are still driving their decision." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, contact verification, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "handyman-lead-generation",
    label: "Handyman",
    category: "Home Services",
    keywords: ["handyman"],
    tagline: "Fill Your Schedule,",
    highlight: "Without the Middleman Markup",
    subheadline:
      "Get a steady stream of exclusive handyman leads — filtered by task type and job size — so you're never paying directory rates for jobs outside your skillset.",
    searchChips: ["handyman near me", "furniture assembly service", "small home repairs cost"],
    demoIndustry: "Handyman",
    overviewEyebrow: "The Problem",
    overviewHeading: "Handyman jobs are small, which means volume — not price per lead — decides your economics",
    overviewParagraphs: [
      "A handyman business runs on a high volume of small jobs, not a handful of big-ticket sales, so paying premium per-lead rates that make sense for a $20,000 remodel doesn't pencil out for a $150 furniture assembly or a half-day punch list. Directory sites pile on high markups and resell the same job request to multiple handymen, and a good share of submissions are DIY-curious homeowners who were never going to hire out the work.",
      "We deliver handyman leads filtered by task type — carpentry, assembly, painting, general repairs — at volume and price points built for small-job economics, so you can stay booked without directory markups eating your margin. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by task type — carpentry, assembly, painting, and general repairs",
      "Priced and delivered for small-job volume, not big-ticket remodel economics",
      "Exclusive delivery, never resold to a competing handyman in your area",
      "Real-time, mobile-ready delivery so you can respond between jobs",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect handyman businesses with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Handyman Customer", detail: "We qualify by task type, job size, property type, and the ZIP codes or neighborhoods you actually cover." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and real intent — not DIY curiosity — before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Single small jobs deliver as web-form leads; larger punch-list or multi-day jobs route as inbound calls so you can scope the full job before committing a truck." },
      { title: "Scale With Demand", detail: "Volume ramps with move-in and move-out season and holiday-prep punch-list demand, and pulls back in slower months." },
    ],
    whoBenefitsHeading: "Who Benefits From Handyman Leads",
    whoBenefitsSubheading: "From solo operators to multi-technician companies, here's who buys handyman leads from Eilite.",
    whoBenefits: [
      { tag: "Independent Pros", icon: Home, title: "Independent Handymen", detail: "Solo operators and small crews filling their schedule with small jobs in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Handyman Franchises & Multi-Technician Companies", detail: "Regional and national brands distributing task volume across technicians and territories." },
      { tag: "Property Management", icon: KeyRound, title: "Property Management & Rental Turnover Crews", detail: "Teams handling high-volume punch-list and turnover work for landlords and property managers." },
      { tag: "Remodelers", icon: HardHat, title: "Small Remodeling Companies Adding Handyman Work", detail: "Remodeling businesses filling schedule gaps with smaller repair and punch-list jobs." },
    ],
    faqs: [
      { q: "What handyman job types can I buy?", a: "Carpentry, furniture assembly, drywall and painting, fixture installs, and general repair and punch-list work — filtered by task type so you're matched to jobs within your skillset." },
      { q: "Are handyman leads exclusive?", a: "Yes. Every lead is sold once, to a single handyman or small business — never resold or shared with a competitor." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or neighborhoods you actually cover." },
      { q: "How fast are leads delivered?", a: "Leads are delivered in real time, with mobile-ready notifications so you can respond between jobs." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for contact accuracy, and checked against TCPA/DNC compliance requirements." },
    ],
  },
  {
    slug: "junk-removal-lead-generation",
    label: "Junk Removal",
    category: "Home Services",
    keywords: ["junk removal", "junk"],
    tagline: "Book the Job",
    highlight: "Before They Call the Next Hauler",
    subheadline:
      "Get exclusive junk removal leads — from single-item pickups to full estate cleanouts — filtered by job size and delivered in real time while the homeowner is still ready to book.",
    searchChips: ["junk removal near me", "furniture removal cost", "estate cleanout service"],
    demoIndustry: "Junk Removal",
    overviewEyebrow: "The Problem",
    overviewHeading: "Junk removal demand spikes overnight, and the fastest hauler gets the job",
    overviewParagraphs: [
      "Junk removal demand is driven by moments, not planning — a move-out deadline, an estate cleanout, a renovation dumpster that's already full — and most homeowners want it gone today or tomorrow, not next week. That urgency creates a mismatch problem too: a single-item pickup and a full-house cleanout require completely different crew time and truck capacity, but directory leads rarely tell you which one you're getting until you're already on-site.",
      "We filter junk removal leads by job size and type — single item, full load, estate or construction cleanout — and deliver them in real time, with live warm transfers available for same-day requests. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers, screened for real contact info and real intent before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by job size and type — single item, full load, estate, or construction cleanout",
      "Live warm transfers for same-day and next-day pickup requests",
      "Exclusive delivery, never resold to a competing hauler in your market",
      "Real-time delivery so you can book the job before they call the next company",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect junk removal companies with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Junk Removal Customer", detail: "We qualify by job size and type, property type, and the ZIP codes or metro areas your trucks actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and real intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard pickups deliver as web-form leads; same-day and next-day urgent requests route as live warm transfers so your crew can lock in the job before they call the next hauler." },
      { title: "Scale With Demand", detail: "Volume ramps with moving season, spring cleaning, and post-storm or estate cleanout spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Junk Removal Leads",
    whoBenefitsSubheading: "From single-truck haulers to multi-truck franchise operations, here's who buys junk removal leads from Eilite.",
    whoBenefits: [
      { tag: "Local Haulers", icon: Home, title: "Local Junk Removal Haulers", detail: "Independent crews filling their truck routes with pickups in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Junk Removal Franchises & Multi-Truck Companies", detail: "Regional and national brands distributing pickup volume across trucks and territories." },
      { tag: "Cleanout Specialists", icon: Package, title: "Estate & Foreclosure Cleanout Specialists", detail: "Crews focused on higher-volume full-property cleanouts rather than single-item pickups." },
      { tag: "Moving Companies", icon: Truck, title: "Moving Companies Adding Junk Removal", detail: "Movers expanding into junk hauling to capture move-out cleanout jobs without building their own lead pipeline first." },
    ],
    faqs: [
      { q: "What junk removal leads can I buy?", a: "Single-item pickups, full-house and estate cleanouts, construction debris removal, and foreclosure or move-out cleanouts — filtered by job size and type." },
      { q: "Can I get same-day removal requests in real time?", a: "Yes. Urgent, same-day requests can be routed as live warm transfers so your crew can respond immediately." },
      { q: "Are junk removal leads exclusive?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing hauler in your market." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas your trucks actually service." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
];
