import type { SolutionVertical } from "./types";

export const homeServices4: SolutionVertical[] = [
  {
    slug: "door-installation-lead-generation",
    label: "Door Installation",
    category: "Home Services",
    keywords: ["door"],
    tagline: "More Door Replacements,",
    highlight: "Booked Before the Second Quote",
    subheadline:
      "Connect with homeowners actively shopping entry doors, patio doors, and storm doors — filtered by door type and material preference, and delivered exclusively before they collect a competing bid.",
    searchChips: ["exterior door replacement cost", "entry door installation near me", "sliding patio door replacement"],
    demoIndustry: "Door Installation",
    overviewEyebrow: "The Problem",
    overviewHeading: "Door leads get bundled with windows and lost to the slowest follow-up",
    overviewParagraphs: [
      "Door installation runs on a slower buying cycle than most home services work — homeowners are picking between steel, fiberglass, and wood, comparing glass-insert styles and finish colors, and often requesting entry door and patio door quotes in the same visit. Worse, many homeowners lump door replacement into a broader window quote, which means single-trade door installers end up competing against full-exterior remodelers bidding both categories at once. A lead that isn't tagged by door type wastes an estimator's time on jobs outside your product line.",
      "We fix that by filtering every door lead before it reaches you. Leads are captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info, real project scope, and the specific door type the homeowner is shopping for.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by door type — entry, patio/sliding, storm, or interior replacement",
      "Delivered once, exclusively to you — never resold to a competing installer in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing materials",
      "Combine web-form leads with live warm transfers when you need faster-closing volume",
    ],
    faqs: [
      { q: "What types of door installation leads can I buy?", a: "Entry door replacements, patio and sliding doors, storm doors, and interior door installations — filtered by door type and material preference so you're quoting jobs that match what you actually install." },
      { q: "Are door installation leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single door installer — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve, so you're not paying to chase jobs outside your install range." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit. Warm transfers connect you live, on the phone, while the homeowner is still comparing options." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered — so you're calling a real homeowner, not a bot or a duplicate." },
    ],
  },
  {
    slug: "fencing-lead-generation",
    label: "Fencing",
    category: "Home Services",
    keywords: ["fence", "fencing"],
    tagline: "Fill Your Fencing Schedule",
    highlight: "Before the Season Peaks",
    subheadline:
      "Get exclusive fencing leads — wood, vinyl, chain-link, or aluminum — filtered by material and linear footage estimate so your crews stay booked through spring and summer demand.",
    searchChips: ["fence installation cost per foot", "vinyl privacy fence installer", "chain link fence contractor near me"],
    demoIndustry: "Fencing",
    overviewEyebrow: "The Problem",
    overviewHeading: "Fencing demand swings hard by season, and job economics swing hard by material",
    overviewParagraphs: [
      "Fencing is one of the most seasonal trades in home services — demand spikes hard in spring and summer as homeowners plan yard and privacy projects, then drops off through fall and winter. On top of that, job economics vary enormously by material: a short run of chain-link and a full perimeter of custom vinyl or wood privacy fencing are priced worlds apart. A generic fencing lead that isn't tagged by material and rough footage can send your estimator to quote a job that's nowhere near your minimum ticket.",
      "We solve both problems at once. Fencing leads are captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists — and screened for real contact info, material preference, and project scope before delivery, with volume that scales up as the season demands it.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by material — wood, vinyl, chain-link, or aluminum/ornamental",
      "Exclusive delivery, never resold to another fencing company in your market",
      "Seasonal volume that ramps up for spring/summer demand and scales back in the off-season",
      "Real-time delivery so you can quote while the homeowner is still comparing fence lines",
    ],
    faqs: [
      { q: "What types of fencing leads can I buy?", a: "Wood, vinyl, chain-link, aluminum, and ornamental fencing projects — filtered by material preference and estimated linear footage so you're quoting jobs that fit your crew's focus." },
      { q: "Are fencing leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single fencing contractor — never resold or shared with a competitor in your service area." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes, neighborhoods, or counties you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit. Live warm transfers are also available for teams that want a homeowner on the phone before handoff." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for accurate contact info, and checked against TCPA/DNC compliance requirements before it's delivered." },
    ],
  },
  {
    slug: "garage-doors-lead-generation",
    label: "Garage Doors",
    category: "Home Services",
    keywords: ["garage"],
    tagline: "From Stuck-Open Repairs",
    highlight: "to Full Door Replacements",
    subheadline:
      "Get exclusive garage door leads — spring and cable repairs, opener installs, and full door replacements — filtered by job type so your team quotes the right job at the right price.",
    searchChips: ["garage door repair cost", "garage door opener installation", "new garage door replacement near me"],
    demoIndustry: "Garage Doors",
    overviewEyebrow: "The Problem",
    overviewHeading: "Garage door jobs range from a $150 spring fix to a $3,000 replacement",
    overviewParagraphs: [
      "Garage doors span the widest repair-to-replacement spread of almost any home services trade — a broken spring or dead opener is a same-day, low-ticket emergency call, while a full insulated steel door replacement is a considered purchase homeowners compare across style catalogs for weeks. Treating both as the same generic \"garage door lead\" means your dispatchers waste time quoting emergency techs on style consultations and your sales reps waste time chasing $150 repair calls.",
      "We split garage door leads by job type before they ever reach you. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists — and screened for real contact info and real intent, so repair, opener, and replacement work route to the right part of your team.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — spring/cable repair, opener installation, or full door replacement",
      "Live warm transfers for stuck-door emergencies that need a technician now",
      "Exclusive delivery, never resold to another garage door company in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing options",
    ],
    faqs: [
      { q: "Do you offer emergency garage door leads, not just replacement quotes?", a: "Yes. Urgent repair calls — broken springs, dead openers, doors stuck open — can be routed as live warm transfers so your dispatcher can respond immediately, alongside standard web-form leads for replacement work." },
      { q: "Can I target only replacement leads, not repair work?", a: "Yes. Campaigns are configured to your target job types and service area before any leads are delivered." },
      { q: "Are garage door leads exclusive?", a: "Every lead and transfer is sold once, to a single garage door company — never resold or shared with a competitor in the same market." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for phone and address accuracy, and checked against TCPA/DNC lists before delivery." },
      { q: "How quickly can I start receiving leads?", a: "Most garage door campaigns can launch within days of confirming your service area, job types, and volume needs on a demo call." },
    ],
  },
  {
    slug: "general-remodeling-lead-generation",
    label: "General Remodeling",
    category: "Home Services",
    keywords: ["remodel", "remodeling"],
    tagline: "Remodeling Leads Sized",
    highlight: "to Match Your Crew's Capacity",
    subheadline:
      "Get exclusive remodeling leads — from single-room refreshes to whole-home renovations — filtered by project scope and budget range so you're not chasing jobs too small or too big for your team.",
    searchChips: ["kitchen remodel cost", "whole home renovation contractor", "bathroom remodel near me"],
    demoIndustry: "General Remodeling",
    overviewEyebrow: "The Problem",
    overviewHeading: "Remodeling has the widest job-size range of any trade — and the widest range of bad-fit leads",
    overviewParagraphs: [
      "No other home services category spans as wide a range as general remodeling — a single lead source can produce an $8,000 bathroom refresh and a $150,000 whole-home addition, and on paper those two inquiries look identical. Without filtering, remodelers end up quoting jobs too small to be worth the estimate or too large for their crew size and financing options, burning hours on consultations that were never going to close.",
      "We filter remodeling leads by project scope and estimated budget before they ever reach you. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — and screened for real contact info and real project scope, so single-room jobs and whole-home projects route separately.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by project scope — kitchen, bathroom, addition, or whole-home renovation",
      "Filtered by estimated budget range so you're not quoting jobs below your minimum",
      "Exclusive delivery, never resold to another remodeling company in your market",
      "Real-time delivery so you can quote while the homeowner is still gathering bids",
    ],
    faqs: [
      { q: "Can I get only large-budget remodeling leads, not small repair jobs?", a: "Yes. Campaigns can be configured to target specific project types and estimated budget ranges, so you're not paying for work below your minimum ticket." },
      { q: "Are remodeling leads exclusive?", a: "Yes. Every lead is sold once, to a single remodeling company — never resold or shared with a competitor in your service area." },
      { q: "Can I set a service radius?", a: "Yes. Campaigns are built around the ZIP codes, neighborhoods, or counties you actually serve." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for accurate contact info, and checked against TCPA/DNC compliance requirements." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit, and live warm transfers are available for teams that want a homeowner already on the phone." },
    ],
  },
  {
    slug: "gutters-lead-generation",
    label: "Gutters",
    category: "Home Services",
    keywords: ["gutter"],
    tagline: "Gutter Leads",
    highlight: "That Aren't Just Roofing Leftovers",
    subheadline:
      "Get exclusive gutter leads — seamless installation, leaf guard, and repair — filtered separately from roofing add-on work so you're not competing against a roofer's courtesy quote.",
    searchChips: ["seamless gutter installation cost", "gutter guard installation near me", "gutter repair near me"],
    demoIndustry: "Gutters",
    overviewEyebrow: "The Problem",
    overviewHeading: "Gutters get sold as an afterthought — and priced like one",
    overviewParagraphs: [
      "Most gutter work in the market gets bundled into a roofing job as a low-ticket add-on, which means dedicated gutter contractors are often competing against roofers quoting gutters as a courtesy line item rather than the main event. That drags down average ticket size and buries standalone gutter and leaf-guard requests inside a much larger pool of roofing leads.",
      "We keep gutter leads separate. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists — and tagged as standalone gutter work or a roofing add-on, then screened for real contact info and real project scope before it reaches you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads tagged as standalone gutter work, not buried inside a roofing bundle",
      "Filtered by job type — new installation, leaf guard, or repair",
      "Exclusive delivery, never resold to another gutter company in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing",
    ],
    faqs: [
      { q: "What types of gutter leads can I buy?", a: "New seamless gutter installation, leaf guard/gutter guard add-ons, and repair work — filtered by job type and property type so you're quoting jobs that match your crew's focus." },
      { q: "Are gutter leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single gutter contractor — never resold or shared with a competitor in your market." },
      { q: "Can I set a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit, so you can quote before a bundled roofing bid beats you to it." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery." },
    ],
  },
  {
    slug: "heating-lead-generation",
    label: "Heating",
    category: "Home Services",
    keywords: ["heating"],
    tagline: "Fill Your Heating Calendar",
    highlight: "Before the Next Cold Snap",
    subheadline:
      "Get exclusive heating leads — furnace and boiler repair, replacement, and maintenance — filtered by system type and urgency and delivered the moment a homeowner needs help.",
    searchChips: ["furnace repair near me", "no heat emergency service", "furnace replacement cost"],
    demoIndustry: "Heating",
    overviewEyebrow: "The Problem",
    overviewHeading: "Heating failures are urgent, cold-weather events — and the fastest caller wins",
    overviewParagraphs: [
      "Heating overlaps with general HVAC work, but it has its own urgency curve: a furnace or boiler that dies in a cold snap isn't a scheduling conversation, it's an emergency, and the homeowner is calling every company on the first page of results at once. Shared leads and slow delivery mean you're often the third or fourth call, not the first — and in freezing weather, whoever answers first usually books the job.",
      "We deliver heating leads and warm transfers built for that urgency: real-time routing, exclusivity, and filtering by system type and urgency so no-heat emergencies reach you the moment they happen, not after a competitor already dispatched a truck.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by urgency — no-heat emergency, scheduled repair, or replacement/install",
      "Live warm transfers for no-heat calls that need a technician dispatched now",
      "Exclusive delivery, never resold to another heating company in your market",
      "Filter by furnace, boiler, or heat pump system type based on your crew's focus",
    ],
    faqs: [
      { q: "Do you offer emergency no-heat leads, not just scheduled work?", a: "Yes. Urgent no-heat calls are routed as live warm transfers so your dispatcher can respond immediately, alongside standard web-form leads for maintenance and replacement work." },
      { q: "Can I target furnace, boiler, or heat pump leads specifically?", a: "Yes. Campaigns are configured to your target system types and service area before any leads are delivered." },
      { q: "Are heating leads exclusive?", a: "Every lead and transfer is sold once, to a single heating contractor — never resold or shared with a competitor in the same market." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for phone and address accuracy, and checked against TCPA/DNC lists before delivery." },
      { q: "How quickly can I start receiving leads?", a: "Most heating campaigns can launch within days of confirming your service area, system types, and volume needs on a demo call." },
    ],
  },
  {
    slug: "mold-removal-lead-generation",
    label: "Mold Removal",
    category: "Home Services",
    keywords: ["mold"],
    tagline: "Mold Removal Leads",
    highlight: "Ready to Book the Same Day",
    subheadline:
      "Connect with homeowners who just found mold and need it addressed now — filtered by testing vs. full remediation and screened for real urgency before delivery.",
    searchChips: ["mold removal cost", "black mold inspection near me", "mold remediation company"],
    demoIndustry: "Mold Removal",
    overviewEyebrow: "The Problem",
    overviewHeading: "Mold jobs mix health urgency with insurance-claim complexity",
    overviewParagraphs: [
      "Finding mold triggers immediate action — a homeowner who just spotted it behind drywall, under a sink, or after a flood is worried about their family's health and wants someone on-site fast. But the job itself often gets tangled in insurance claims, moisture-source diagnosis, and the difference between a testing-only inquiry and a full remediation project, and generic \"home services\" leads rarely separate the two or capture how urgent the homeowner actually is.",
      "We screen every mold lead for both urgency and job type before it reaches you. Leads are captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists — and verified for real contact info and real project scope, with live warm transfers available for same-day discoveries.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by job type — inspection/testing, remediation, or insurance-claim related work",
      "Live warm transfers for urgent discovery calls that need a same-day response",
      "Exclusive delivery, never resold to another remediation company in your market",
      "Real-time delivery so you can respond while the homeowner is still in decision mode",
    ],
    faqs: [
      { q: "What types of mold removal leads can I buy?", a: "Inspection and testing requests, full remediation jobs, and insurance-claim-related mold work — filtered by job type so you're not spending an on-site visit quoting a job outside your scope." },
      { q: "Are mold removal leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single remediation company — never resold or shared with a competitor in your market." },
      { q: "Can I target a specific service area?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you're licensed and equipped to serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time, and urgent discovery calls can be routed as live warm transfers so you can respond the same day." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered." },
    ],
  },
  {
    slug: "swimming-pool-cover-lead-generation",
    label: "Swimming Pool Covers",
    category: "Home Services",
    keywords: ["pool"],
    tagline: "A Narrow Niche,",
    highlight: "Leads That Actually Match It",
    subheadline:
      "Get exclusive leads from homeowners shopping automatic, safety, or winter pool covers — a specialty niche with far fewer competing contractors than general pool service.",
    searchChips: ["automatic pool cover cost", "pool safety cover installation", "winter pool cover near me"],
    demoIndustry: "Swimming Pool Covers",
    overviewEyebrow: "The Problem",
    overviewHeading: "Pool covers are a small, seasonal niche most lead sources don't bother filtering for",
    overviewParagraphs: [
      "Swimming pool covers are a narrow specialty inside the broader pool industry — automatic covers, safety covers, and winter covers each have their own buyer and season, and there are far fewer contractors who install them compared to general pool builders or pool service companies. That narrowness cuts both ways: demand is real but seasonal and concentrated, and most generic \"pool leads\" aren't filtered closely enough to separate cover buyers from someone shopping a new pool build or routine cleaning service.",
      "We filter for that specificity. Pool cover leads are captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — and screened for real contact info and real project intent before delivery, so you're not paying for pool-adjacent traffic that was never going to buy a cover.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by cover type — automatic, safety, or winter/seasonal covers",
      "Exclusive delivery, never resold to another pool cover installer in your market",
      "Seasonal volume that scales with pool opening and closing season demand",
      "Real-time delivery so you can quote while the homeowner is still comparing options",
    ],
    faqs: [
      { q: "What types of pool cover leads can I buy?", a: "Automatic pool covers, safety covers, and winter/seasonal covers — filtered by cover type and pool type so you're quoting jobs that match what you install." },
      { q: "Are pool cover leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single installer — never resold or shared with a competitor in your service area." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit, so you can respond while pool-opening or pool-closing season is top of mind." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for accurate contact info, and checked against TCPA/DNC compliance requirements before delivery." },
    ],
  },
  {
    slug: "windows-installation-lead-generation",
    label: "Windows Installation",
    category: "Home Services",
    keywords: ["window"],
    tagline: "Window Replacement Leads,",
    highlight: "Filtered by More Than Just ZIP Code",
    subheadline:
      "Connect with homeowners shopping window replacement — filtered by window count, material, and whole-house vs. partial scope — before they collect a competing bid.",
    searchChips: ["window replacement cost", "energy efficient windows installer", "vinyl window replacement near me"],
    demoIndustry: "Windows Installation",
    overviewEyebrow: "The Problem",
    overviewHeading: "Window leads run through a long, material-driven decision cycle — and often get bundled with doors",
    overviewParagraphs: [
      "Window installation runs on the same slow, style-driven buying cycle as door installation — homeowners are weighing vinyl, wood, and fiberglass frames, double- versus triple-pane glass, and grid patterns, and that consideration stretches the sales cycle to weeks. Many homeowners also request combined window-and-door quotes in a single visit, which puts single-trade window companies up against full-exterior remodelers bidding both categories at once. A lead that doesn't specify window count, material, or whole-house versus partial scope wastes an estimator's time on a mismatched job.",
      "We filter for exactly that before a lead reaches you. Every window lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — and screened for real contact info, real intent, and the scope of the project.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by scope — whole-house replacement or partial/single-window jobs",
      "Filtered by material preference and energy-efficiency upgrade intent",
      "Exclusive delivery, never resold to another window company in your market",
      "Real-time delivery so you can quote while the homeowner is still comparing materials",
    ],
    faqs: [
      { q: "What types of window installation leads can I buy?", a: "Whole-house and partial window replacements, filtered by material preference (vinyl, wood, fiberglass) and energy-efficiency upgrade intent, so you're quoting jobs that match your product line." },
      { q: "Are window installation leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single window installer — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit. Warm transfers connect you live, on the phone, while the homeowner is still deciding." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered." },
    ],
  },
  {
    slug: "siding-lead-generation",
    label: "Siding",
    category: "Home Services",
    keywords: ["siding"],
    tagline: "Siding Leads Built",
    highlight: "for a Long Consideration Cycle",
    subheadline:
      "Get exclusive siding leads — vinyl, fiber cement, and engineered wood — filtered by material and project size so you're the first credible bid the homeowner sees, not the last.",
    searchChips: ["siding replacement cost", "vinyl siding installation near me", "fiber cement siding contractor"],
    demoIndustry: "Siding",
    overviewEyebrow: "The Problem",
    overviewHeading: "Siding is a high-ticket decision homeowners take weeks to make",
    overviewParagraphs: [
      "Siding replacement is one of the highest-ticket exterior projects in home services, and like roofing it comes with a long consideration cycle — homeowners comparing vinyl, fiber cement, and engineered wood, plus color, texture, and warranty differences, across several bids before committing tens of thousands of dollars. Slow-moving, expensive jobs punish contractors who rely on stale or resold leads, because by the time a recycled lead reaches your team, the homeowner has often already anchored on a competitor's bid.",
      "We get siding leads to you while that decision is still open. Every lead is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — and screened for real contact info, real intent, and project scope before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by material preference — vinyl, fiber cement, or engineered wood",
      "Filtered by project size — full re-side or partial/accent siding work",
      "Exclusive delivery, never resold to another siding company in your market",
      "Combine web-form leads with live warm transfers when you need faster-closing volume",
    ],
    faqs: [
      { q: "What types of siding leads can I buy?", a: "Full home re-siding, partial and accent siding work, and repair jobs — filtered by material preference (vinyl, fiber cement, engineered wood) and project size." },
      { q: "Are siding leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single siding contractor — never resold or shared with a competitor bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit, so you can quote before a competitor's bid becomes the benchmark." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered." },
    ],
  },
];
