import {
  Home,
  Building2,
  Siren,
  ShieldCheck,
  Paintbrush,
  Building,
  Zap,
  Axe,
  Ruler,
  HardHat,
  Timer,
  HeartPulse,
  Construction,
  Hammer,
  Boxes,
  ChefHat,
  Factory,
  Layers,
  Fence,
} from "lucide-react";
import type { SolutionVertical } from "./types";

export const homeServices3: SolutionVertical[] = [
  {
    slug: "locksmith-lead-generation",
    label: "Locksmith",
    category: "Home Services",
    keywords: ["locksmith"],
    tagline: "Be First on Scene",
    highlight: "For Every Lockout Call",
    subheadline:
      "Get exclusive locksmith leads — emergency lockouts, rekeys, and commercial access jobs — verified and routed to your phone the moment a customer needs a locksmith now.",
    metaDescription:
      "Get exclusive locksmith leads, emergency lockouts, rekeys, and commercial access jobs, verified and routed to your phone the moment customers need help.",
    searchChips: ["locked out of my house", "car key replacement near me", "commercial lock rekey"],
    demoIndustry: "Locksmith",
    overviewEyebrow: "The Problem",
    overviewHeading: "Locksmith calls go to whoever answers first, and directories are full of noise",
    overviewParagraphs: [
      "Nearly every locksmith job starts as an emergency — someone is locked out of a house, car, or office right now, dialing down a list of results until someone picks up. That list is crowded with scam-adjacent call centers and duplicated directory listings pretending to be local shops, so a genuine customer often can't tell your business from a lead-gen broker dispatching to the highest bidder three states away. Even when a call is real, a commercial locksmith gets routed residential lockouts and vice versa, burning drive time on a job outside their scope.",
      "We deliver locksmith leads and live warm transfers built for that urgency: captured on owned, high-intent pages or sourced from a small set of vetted publishers — never resold lists or recycled directory contacts — filtered by job type (lockout, rekey, automotive, commercial access) and verified for a real phone number and real location before the call ever reaches you.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — residential lockout, automotive, rekey/install, or commercial access",
      "Live warm transfers for active lockouts, connecting the customer to you while they're still stranded",
      "Exclusive delivery — never resold to another locksmith bidding in your market",
      "Service-area targeting so you're not driving 40 minutes for a job outside your radius",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect locksmiths with customers who need help right now — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Locksmith Customer", detail: "We qualify by job type — residential lockout, automotive, rekey/install, or commercial access — plus property type and the service radius you actually cover." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real intent the moment it's captured, filtering out call-center scrapes and duplicate directory bots before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Scheduled rekeys and installs deliver as web-form leads; active lockouts route as live warm transfers, connecting the stranded customer to you while they're still standing at the door." },
      { title: "Scale With Demand", detail: "Volume flexes with weather-driven spikes — cold snaps, storms, and weekend surges — without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Locksmith Leads",
    whoBenefitsSubheading: "From single-van operators to multi-territory dispatch companies, here's who buys locksmith leads from Eilite.",
    whoBenefits: [
      { tag: "Local Locksmiths", icon: Home, title: "Independent Locksmith Shops", detail: "Independent shops filling their schedule with lockouts and rekeys in a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Locksmith Franchises & Multi-Van Companies", detail: "Regional and national brands distributing dispatch volume across vans and territories." },
      { tag: "Emergency Response", icon: Siren, title: "24/7 Emergency Lockout Responders", detail: "Companies built around live warm transfers for stranded customers who need someone on scene now." },
      { tag: "Commercial & Access Control", icon: ShieldCheck, title: "Commercial Locksmiths & Access-Control Installers", detail: "Specialists focused on higher-ticket master key systems, electronic access control, and business rekeys." },
    ],
    faqs: [
      { q: "What types of locksmith leads can I buy?", a: "Residential and commercial lockouts, automotive key replacement and programming, rekeys, lock installs, and access-control jobs — filtered so you only receive the job types you actually handle." },
      { q: "Are locksmith leads exclusive to my business?", a: "Yes. Every lead and transfer is sold once, to a single locksmith — never resold to a competitor or routed through a dispatch call center." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or metro area you actually cover, so you're not sent lockouts outside your driving range." },
      { q: "How fast are emergency lockout leads delivered?", a: "Live warm transfers connect you to the customer by phone while they're still locked out. Web-form leads for scheduled work (rekeys, installs) deliver in real time as they're submitted." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're calling a real customer, not a duplicate or a directory bot." },
    ],
  },
  {
    slug: "painting-lead-generation",
    label: "Painting",
    category: "Home Services",
    keywords: ["painting", "paint"],
    tagline: "Fill Your Painting Schedule",
    highlight: "With Jobs Worth Bidding On",
    subheadline:
      "Get exclusive painting leads — interior, exterior, residential, and commercial — filtered by project size and property type so your estimators quote jobs that match your crew.",
    metaDescription:
      "Get exclusive painting leads, interior, exterior, residential, and commercial, filtered by project size and property type.",
    searchChips: ["exterior house painting cost", "interior painter near me", "commercial painting contractor"],
    demoIndustry: "Painting",
    overviewEyebrow: "The Problem",
    overviewHeading: "A painting lead can mean a $400 accent wall or a $40,000 repaint",
    overviewParagraphs: [
      "\"Painting lead\" covers wildly different jobs — a single interior room, a full exterior repaint on a three-story house, or a recurring commercial contract — and treating them as the same product wrecks your close rate and your estimator's time. Demand also swings hard by season, with spring and summer exterior work flooding in while interior jobs stay steadier through winter, and homeowners routinely collect three or four bids before committing, so slow follow-up means quoting a job that's already gone.",
      "We filter painting leads by project type, property size, and interior-vs-exterior scope before they ever reach you. Every lead is captured on owned, high-intent pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — and screened for real contact info and real project intent so your estimators spend time quoting, not qualifying.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by scope — interior, exterior, cabinet/trim, and commercial repaint projects",
      "Filtered by property size and job budget so you're not quoting work below your minimum",
      "Exclusive delivery, never resold to another painting contractor in your market",
      "Seasonal volume that scales up for spring/summer exterior demand and steadies through winter",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect painting contractors with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Painting Customer", detail: "We qualify by scope — interior, exterior, cabinet/trim, or commercial — plus property size and job budget." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real project intent the moment it's captured, before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard interior and exterior jobs deliver as web-form leads; larger commercial or multi-unit repaint inquiries can route as live warm transfers or inbound calls for faster follow-up." },
      { title: "Scale With the Season", detail: "Volume ramps up for spring and summer exterior demand and steadies through winter interior work, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Painting Leads",
    whoBenefitsSubheading: "From single-crew operators to multi-crew commercial painters, here's who buys painting leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Independent Painting Contractors", detail: "Crews filling their calendar with interior and exterior repaints in a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Painting Franchises & Multi-Crew Companies", detail: "Regional and national brands distributing volume across crews and territories." },
      { tag: "Cabinet & Trim Specialists", icon: Paintbrush, title: "Cabinet & Trim Refinishing Specialists", detail: "Painters focused on higher-margin cabinet, trim, and fine-finish work rather than full repaints." },
      { tag: "Commercial Painters", icon: Building, title: "Commercial & Multi-Unit Painting Contractors", detail: "Businesses bidding office, retail, and multi-unit residential repaint contracts alongside homeowner work." },
    ],
    faqs: [
      { q: "Can I choose interior, exterior, or commercial leads?", a: "Yes. Campaigns are configured to your target job types — interior, exterior, cabinet/trim refinishing, or commercial repaint — so you're not fielding requests outside your specialty." },
      { q: "Are painting leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single painting contractor — never resold or shared with competitors bidding the same job." },
      { q: "Can I target a specific service area?", a: "Yes. Campaigns are built around the ZIP codes, neighborhoods, or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit, and live warm transfers are available for teams that want a prospect on the phone before handoff." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's delivered — so you're quoting a real project, not a duplicate or a price-shopper list." },
    ],
  },
  {
    slug: "tree-removal-lead-generation-accelerate-growth-with-performance-based-solutions",
    label: "Tree Removal",
    category: "Home Services",
    keywords: ["tree removal", "tree"],
    tagline: "Grow Your Crew's Workload",
    highlight: "With Performance-Based Lead Delivery",
    subheadline:
      "Get exclusive tree removal, trimming, and storm-cleanup leads — filtered by urgency and job scope and delivered in real time so your crew is never idle between jobs.",
    metaDescription:
      "Get exclusive tree removal, trimming, and storm-cleanup leads, filtered by urgency and job scope, delivered in real time so your crew stays busy.",
    searchChips: ["tree removal cost near me", "storm damage tree removal", "stump grinding service"],
    demoIndustry: "Tree Removal",
    overviewEyebrow: "The Problem",
    overviewHeading: "Storm damage creates demand spikes your ad budget can't predict",
    overviewParagraphs: [
      "Tree service demand is brutally uneven — a single storm can flood your phone with emergency removals for two weeks straight, then go quiet, and paying a flat rate per lead all year means overpaying in the slow months and getting outbid the moment a storm hits. Emergency jobs also carry real complexity: downed limbs on power lines, insurance claims that require documentation, and permit requirements for removals near property lines, so a lead that's just a name and a phone number often turns into hours of unpaid qualification before you know if the job is even legal to take.",
      "We deliver tree removal leads and live warm transfers matched to that reality — routed by urgency (storm emergency vs. scheduled trim or removal) and captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold storm-chasing lists. Every submission is screened for real contact info and real project scope before your crew gets the call.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by urgency — storm/emergency removal, scheduled removal, trimming, or stump grinding",
      "Live warm transfers for active storm-damage calls so you can respond while limbs are still down",
      "Exclusive delivery, never resold to another tree service competing in your market",
      "Volume that scales up fast during storm season and dials back when demand is steady",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect tree service companies with property owners who need work done — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Tree Service Customer", detail: "We qualify by job type — removal, trimming, stump grinding, or storm cleanup — plus property type and the counties or metro areas your crew covers." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real intent the moment it's captured, so you're not driving out to a fake address." },
      { title: "Choose Your Delivery", detail: "Scheduled trimming and removal jobs deliver as web-form leads; active storm-damage and hazard calls route as live warm transfers straight to your crew." },
      { title: "Scale With Storm Season", detail: "Volume spikes fast after severe weather and eases back to steady scheduled work the rest of the year." },
    ],
    whoBenefitsHeading: "Who Benefits From Tree Removal Leads",
    whoBenefitsSubheading: "From single-crew operators to multi-crew storm-response companies, here's who buys tree removal leads from Eilite.",
    whoBenefits: [
      { tag: "Local Crews", icon: Home, title: "Independent Tree Service Crews", detail: "Local operators filling their schedule with removals, trimming, and stump grinding in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Tree Service Franchises & Multi-Crew Companies", detail: "Regional and national brands routing volume across crews and territories." },
      { tag: "Storm Response", icon: Zap, title: "Storm & Emergency Response Crews", detail: "Companies built to ramp fast after severe weather, handling downed limbs and hazard removals through live warm transfer." },
      { tag: "Land Clearing", icon: Axe, title: "Land Clearing & Lot-Clearing Specialists", detail: "Crews focused on larger clearing jobs for developers, property managers, and land owners rather than single-tree removals." },
    ],
    faqs: [
      { q: "Do you send emergency storm-damage leads in real time?", a: "Yes. Storm and emergency removal calls can be routed as live warm transfers so your crew can respond immediately, alongside standard web-form leads for scheduled trimming and removal." },
      { q: "What tree service job types can I target?", a: "Full removal, trimming/pruning, stump grinding, and storm cleanup — filtered to the services your crew actually offers." },
      { q: "Are tree removal leads exclusive to my business?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing tree service in your area." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the counties or metro areas your crew actually covers." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're not driving out to a fake address or a duplicate storm-chaser list." },
    ],
  },
  {
    slug: "carpentry-leads-book-more-jobs-with-verified-client-requests",
    label: "Carpentry",
    category: "Home Services",
    keywords: ["carpentry", "carpenter"],
    tagline: "Book More Custom Jobs,",
    highlight: "Not More Estimates That Go Nowhere",
    subheadline:
      "Get exclusive carpentry leads — custom builds, trim and finish work, repairs, and built-ins — filtered by project scope so your shop quotes jobs that are ready to commit.",
    metaDescription:
      "Get exclusive carpentry leads, custom builds, trim and finish work, repairs, and built-ins, filtered by project scope so you quote ready clients.",
    searchChips: ["custom built-in bookshelf cost", "trim carpenter near me", "deck framing contractor"],
    demoIndustry: "Carpentry",
    overviewEyebrow: "The Problem",
    overviewHeading: "Custom carpentry has a long consideration cycle and a lot of tire-kickers",
    overviewParagraphs: [
      "Carpentry work is high-consideration by nature — a homeowner planning custom built-ins, a staircase remodel, or trim and finish work is usually weeks into research, comparing photos and quotes, before they ever fill out a form, and a meaningful share of that traffic is just gathering ideas with no budget or timeline attached. On top of that, general contractors and handyman services often scoop up carpentry-adjacent leads and resell them without any real vetting of project scope, so a shop that specializes in fine finish work ends up quoting fence repairs and vice versa.",
      "We filter carpentry leads by project type and scope before they reach you — custom/built-in work kept separate from trim, framing, and repair requests — sourced from owned, high-intent pages or a small set of vetted publishers, never resold generalist-contractor lists. Every lead is screened for real contact info and real project intent so your shop spends time on jobs worth quoting.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by scope — custom/built-in work, trim and finish carpentry, framing, and repairs",
      "Filtered by project budget so you're not quoting jobs below your shop's minimum",
      "Exclusive delivery, never resold to another carpentry contractor in your market",
      "Real-time delivery so you can follow up while the homeowner is still deciding",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect carpentry shops with homeowners and builders ready to commit — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Carpentry Customer", detail: "We qualify by project type — custom/built-in, trim and finish, framing, or repair — plus budget and the service area your shop covers." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real project intent the moment it's captured, filtering out idea-stage browsing before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard trim and repair requests deliver as web-form leads; larger custom-build inquiries can route as inbound calls so your shop can walk through scope before quoting." },
      { title: "Scale With Project Demand", detail: "Volume adjusts as remodeling season and custom-build inquiries pick up, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Carpentry Leads",
    whoBenefitsSubheading: "From single-shop operators to multi-crew millwork companies, here's who buys carpentry leads from Eilite.",
    whoBenefits: [
      { tag: "Local Shops", icon: Home, title: "Independent Carpentry Shops", detail: "Small shops filling their schedule with trim, repair, and built-in work in a defined service area." },
      { tag: "Multi-Crew Shops", icon: Building2, title: "Multi-Crew Carpentry & Millwork Companies", detail: "Larger shops distributing custom-build volume across multiple crews or locations." },
      { tag: "Custom Millwork", icon: Ruler, title: "Custom Built-In & Millwork Specialists", detail: "Shops focused on higher-ticket custom builds and fine finish work rather than general repairs." },
      { tag: "General Contractors", icon: HardHat, title: "General Contractors & Remodelers", detail: "Builders and remodeling companies adding carpentry-specific leads to fill gaps in an existing project pipeline." },
    ],
    faqs: [
      { q: "Can I get only custom/high-value carpentry leads, not general handyman work?", a: "Yes. Campaigns can be configured to target specific project types and minimum budgets, so you're not fielding requests outside your shop's focus." },
      { q: "Are carpentry leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single carpentry contractor — never resold or shared with a competing shop." },
      { q: "Can I target a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit, so you can follow up while the project is still top of mind." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're calling a real homeowner with a real project, not a duplicate." },
    ],
  },
  {
    slug: "carpet-cleaning-leads-residential-commercial-stain-removal",
    label: "Carpet Cleaning",
    category: "Home Services",
    keywords: ["carpet cleaning", "carpet"],
    tagline: "Keep Your Vans Booked",
    highlight: "With Leads That Actually Convert",
    subheadline:
      "Get exclusive carpet cleaning leads — routine cleanings, stain and pet-odor treatment, move-out cleans, and commercial contracts — filtered by job type and delivered in real time.",
    metaDescription:
      "Get exclusive carpet cleaning leads, routine cleanings, stain and pet-odor treatment, move-out cleans, and commercial contracts, filtered by job type.",
    searchChips: ["carpet cleaning near me", "pet stain removal service", "move out carpet cleaning"],
    demoIndustry: "Carpet Cleaning",
    overviewEyebrow: "The Problem",
    overviewHeading: "One-time cleans and recurring contracts need completely different economics",
    overviewParagraphs: [
      "Carpet cleaning leads split into two very different businesses — a one-time deep clean or stain job that needs to be booked and closed fast, and a recurring residential or commercial contract that's worth far more over time but takes longer to land. Treating every lead the same means either overpaying for low-value one-off jobs or missing the recurring-revenue prospects buried in the pile, and a lot of directory-sourced leads turn out to be price-shoppers comparing five quotes for the cheapest per-room rate, not a serious booking.",
      "We filter carpet cleaning leads by job type — one-time vs. recurring, residential vs. commercial, and specialty work like pet-odor or move-out cleans — sourced from owned, high-intent pages or a small set of vetted publishers, never resold directory lists. Every lead is screened for real contact info and real scheduling intent before it reaches your team.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — routine cleaning, stain/pet-odor treatment, move-in/move-out, and commercial",
      "Filtered by residential vs. commercial and recurring vs. one-time to match your service model",
      "Exclusive delivery, never resold to another cleaning company in your market",
      "Real-time delivery so you can book the appointment while demand is still fresh",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect carpet cleaning companies with customers ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Carpet Cleaning Customer", detail: "We qualify by job type — routine cleaning, stain/pet-odor, move-in/move-out, or commercial — plus residential vs. commercial and your service radius." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real scheduling intent the moment it's captured, filtering out price-comparison bots before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Routine and one-time cleanings deliver as web-form leads; move-out deadlines and larger commercial jobs can route as live warm transfers or inbound calls for faster scheduling." },
      { title: "Scale With Turnover Demand", detail: "Volume flexes with seasonal move cycles and holiday cleaning spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Carpet Cleaning Leads",
    whoBenefitsSubheading: "From single-van operators to multi-branch commercial providers, here's who buys carpet cleaning leads from Eilite.",
    whoBenefits: [
      { tag: "Local Operators", icon: Home, title: "Independent Carpet Cleaning Companies", detail: "Van-based operators filling their schedule with residential cleanings in a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Carpet Cleaning Franchises & Multi-Van Companies", detail: "Regional and national brands distributing volume across vans and territories." },
      { tag: "Turnover Specialists", icon: Timer, title: "Move-In/Move-Out Turnover Cleaners", detail: "Companies built around fast turnaround for property managers and landlords working against tight tenant-turnover deadlines." },
      { tag: "Commercial Accounts", icon: Building, title: "Commercial & Janitorial Contract Providers", detail: "Businesses growing recurring commercial cleaning contracts alongside one-time residential jobs." },
    ],
    faqs: [
      { q: "Can I target recurring commercial contracts instead of one-time residential jobs?", a: "Yes. Campaigns can be configured to prioritize commercial and recurring-service leads over one-off residential cleans, or any mix that fits your business." },
      { q: "Are carpet cleaning leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single cleaning company — never resold or shared with a competitor in your area." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or metro area your vans actually cover." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as customers submit, so you can call to book the appointment while it's still top of mind." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're calling a real customer ready to schedule, not a duplicate or a price-comparison bot." },
    ],
  },
  {
    slug: "commercial-cleaning-lead-generation",
    label: "Commercial Cleaning",
    category: "Home Services",
    keywords: ["commercial cleaning"],
    tagline: "Win More Cleaning Contracts,",
    highlight: "Not More RFPs That Go Nowhere",
    subheadline:
      "Get exclusive commercial cleaning leads — office, retail, medical, and post-construction accounts — filtered by facility type and contract size so your sales team quotes decision-makers, not researchers.",
    metaDescription:
      "Get exclusive commercial cleaning leads, office, retail, medical, and post-construction accounts, filtered by facility type and contract size.",
    searchChips: ["office cleaning service quote", "post construction cleanup company", "janitorial services contract"],
    demoIndustry: "Commercial Cleaning",
    overviewEyebrow: "The Problem",
    overviewHeading: "Commercial cleaning is a B2B sale, and most lead sources treat it like a homeowner form",
    overviewParagraphs: [
      "Selling into a facility manager or office administrator is a completely different sales motion than booking a homeowner — it involves a proposal, a walkthrough, a contract term, and often a procurement process that takes weeks, and a lead source built for one-time residential jobs simply doesn't capture the facility type, square footage, or cleaning frequency your sales team needs to price a bid. Worse, commercial listings get flooded with national franchise bids and budget providers racing to the bottom on price, so a business inquiry submitted through a generic directory rarely comes with enough detail to tell a real contract opportunity from a tire-kicker gathering quotes for a file.",
      "We deliver commercial cleaning leads built for that B2B cycle — filtered by facility type (office, retail, medical, industrial, post-construction), square footage, and cleaning frequency, and sourced from owned, high-intent pages or a small set of vetted publishers, never resold RFP-aggregator lists. Every inquiry is screened for a real decision-maker and real contract scope before it reaches your sales team.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by facility type — office, retail, medical, industrial, and post-construction cleanup",
      "Contract-size and frequency data included so your team can price the bid before the first call",
      "Exclusive delivery, never resold to a competing cleaning company or national franchise",
      "Real-time delivery so your sales team can respond while the facility is still evaluating vendors",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect commercial cleaning companies with facility decision-makers ready to buy — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Commercial Cleaning Customer", detail: "We qualify by facility type — office, retail, medical, industrial, or post-construction — plus square footage and cleaning frequency." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for a real decision-maker and real contract scope, filtering out RFP-aggregator noise before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard inquiries deliver as web-form leads with facility details attached; larger accounts can route as inbound calls or live warm transfers so your sales team reaches the decision-maker directly." },
      { title: "Scale With Contract Demand", detail: "Volume adjusts as your sales team's capacity for new accounts grows, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Commercial Cleaning Leads",
    whoBenefitsSubheading: "From independent janitorial companies to multi-branch commercial providers, here's who buys commercial cleaning leads from Eilite.",
    whoBenefits: [
      { tag: "Local Providers", icon: Home, title: "Independent Janitorial Companies", detail: "Local providers filling their account roster with office and retail contracts in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Commercial Cleaning Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing contract volume across branches or territories." },
      { tag: "Medical Facilities", icon: HeartPulse, title: "Medical & Healthcare Facility Cleaners", detail: "Providers with the compliance and training to bid on clinics, dental offices, and healthcare facility contracts." },
      { tag: "Post-Construction", icon: Construction, title: "Post-Construction Cleanup Crews", detail: "Crews specializing in the final clean-up pass builders need before a project handoff or occupancy." },
    ],
    faqs: [
      { q: "What facility types can I target?", a: "Office, retail, medical, industrial, and post-construction cleanup — filtered by facility type, square footage, and cleaning frequency so you're quoting jobs that match your crew's capacity." },
      { q: "Are commercial cleaning leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single cleaning company — never resold or shared with a competing provider or national franchise." },
      { q: "Can I target specific metro areas or a service radius?", a: "Yes. Campaigns are built around the metro areas or counties your crews actually service." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as businesses submit, so your sales team can respond while the facility is still comparing vendors." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for accurate business contact information, and checked against TCPA/DNC compliance requirements before delivery." },
    ],
  },
  {
    slug: "basement-waterproofing-lead-generation",
    label: "Basement Waterproofing",
    category: "Home Services",
    keywords: ["waterproofing", "basement"],
    tagline: "Reach Homeowners",
    highlight: "The Moment Water Starts Coming In",
    subheadline:
      "Get exclusive basement waterproofing and foundation leads — from active flooding to seepage and crack repair — filtered by urgency and delivered while the homeowner is still in crisis mode.",
    metaDescription:
      "Get exclusive basement waterproofing and foundation leads, from active flooding to seepage and crack repair, filtered by urgency.",
    searchChips: ["basement waterproofing cost", "foundation crack repair", "sump pump installation near me"],
    demoIndustry: "Basement Waterproofing",
    overviewEyebrow: "The Problem",
    overviewHeading: "A flooded basement is a high-ticket, high-panic purchase, and timing is everything",
    overviewParagraphs: [
      "Basement waterproofing sits at the intersection of high cost and high urgency — a homeowner staring at standing water isn't going to sit on a $8,000-$15,000 decision for long, but they're also not going to trust the first name that pops up if it looks like a fly-by-night operation. Demand spikes hard around storm events and spring snowmelt, when every waterproofing company in the region is suddenly flooded with the same panicked homeowners, and a lead source that can't tell active water intrusion from someone researching for next year wastes your estimator's time on jobs with no urgency behind them.",
      "We deliver basement waterproofing leads and live warm transfers matched to that urgency — filtered by symptom and severity (active flooding, seepage, foundation cracks, sump pump failure), captured on owned, high-intent pages or sourced from a small set of vetted publishers, never resold storm-season lists. Every lead is screened for real contact info and real damage scope before your estimator gets the call.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by severity — active flooding, seepage, foundation cracks, or sump pump failure",
      "Live warm transfers for active water-intrusion emergencies so you can respond same-day",
      "Exclusive delivery, never resold to another waterproofing contractor in your market",
      "Volume that scales up around storm events and spring thaw when demand surges",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect waterproofing contractors with homeowners in crisis mode — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Waterproofing Customer", detail: "We qualify by symptom and severity — active flooding, seepage, foundation cracks, or sump pump failure — plus the counties or metro areas your crew covers." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real damage scope, so your estimator isn't chasing a researcher with no urgency behind them." },
      { title: "Choose Your Delivery", detail: "Scheduled inspections and crack repair deliver as web-form leads; active water-intrusion emergencies route as live warm transfers so you can respond same-day." },
      { title: "Scale With Storm Events", detail: "Volume surges around storm season and spring snowmelt and eases back the rest of the year." },
    ],
    whoBenefitsHeading: "Who Benefits From Basement Waterproofing Leads",
    whoBenefitsSubheading: "From single-crew operators to multi-crew storm-response companies, here's who buys basement waterproofing leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Independent Waterproofing Contractors", detail: "Crews filling their schedule with inspections, sump pump work, and crack repair in a defined radius." },
      { tag: "Franchises", icon: Building2, title: "Waterproofing Franchises & Multi-Crew Companies", detail: "Regional and national brands distributing storm-driven volume across crews and territories." },
      { tag: "Emergency Response", icon: Siren, title: "24/7 Emergency Water-Intrusion Crews", detail: "Companies built around live warm transfers for homeowners with active flooding who need someone on-site today." },
      { tag: "Foundation Repair", icon: Hammer, title: "Foundation Repair Specialists", detail: "Contractors pairing structural crack and foundation repair work with core waterproofing services." },
    ],
    faqs: [
      { q: "Do you send emergency flooding leads in real time?", a: "Yes. Active water-intrusion calls can be routed as live warm transfers so your team can respond immediately, alongside standard web-form leads for scheduled inspections and crack repair." },
      { q: "What waterproofing job types can I target?", a: "Interior and exterior waterproofing, foundation crack repair, sump pump installation/repair, and French drain systems — filtered to the services you offer." },
      { q: "Are basement waterproofing leads exclusive to my business?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing waterproofing company in your area." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the counties or metro areas your crews actually cover." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so your estimator is calling a real homeowner with real water damage, not a duplicate." },
    ],
  },
  {
    slug: "cabinets-installation-lead-generation",
    label: "Cabinet Installation",
    category: "Home Services",
    keywords: ["cabinet"],
    tagline: "Get In Front of Homeowners",
    highlight: "Before They Collect Three Other Quotes",
    subheadline:
      "Get exclusive cabinet installation, refacing, and full kitchen remodel leads — filtered by project scope and timeline so your estimator is first in the door, not the fourth bid.",
    metaDescription:
      "Get exclusive cabinet installation, refacing, and full kitchen remodel leads, filtered by project scope and timeline so you're first in the door.",
    searchChips: ["kitchen cabinet installation cost", "cabinet refacing near me", "custom cabinet maker"],
    demoIndustry: "Cabinet Installation",
    overviewEyebrow: "The Problem",
    overviewHeading: "By the time a cabinet lead reaches you, they've often already got two other quotes",
    overviewParagraphs: [
      "Cabinet projects are tied tightly to the broader kitchen remodel timeline — homeowners plan for weeks or months, browsing styles and finishes long before they request a quote, and once they do, they typically request estimates from three to five contractors at once. Whoever quotes first tends to set the price anchor everyone else gets compared against, but generic remodel leads often arrive without enough detail to know if the job is a simple refacing or a full custom install, and a meaningful share are homeowners still in the early browsing stage with no real timeline yet.",
      "We filter cabinet installation leads by project scope and homeowner readiness — full custom install, stock/semi-custom install, or refacing/refinishing — sourced from owned, high-intent pages or a small set of vetted publishers, never resold generic remodel lists. Every lead is screened for real contact info and real project timeline so your estimator can be the first quote in the door.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by scope — full custom install, stock/semi-custom install, and refacing/refinishing",
      "Filtered by project timeline so you can prioritize homeowners ready to book now",
      "Exclusive delivery, never resold to another cabinet installer bidding the same kitchen",
      "Real-time delivery so your estimate reaches the homeowner before competing quotes do",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect cabinet installers with homeowners early in their kitchen remodel — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Cabinet Customer", detail: "We qualify by project scope — full custom install, stock/semi-custom, or refacing/refinishing — plus timeline and budget." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real project timeline, filtering out early-stage browsers with no timeline yet before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard install and refacing requests deliver as web-form leads; larger full-kitchen inquiries can route as inbound calls so your estimator can be the first quote in the door." },
      { title: "Scale With Remodel Season", detail: "Volume ramps with kitchen remodel demand in spring and fall and steadies through slower months." },
    ],
    whoBenefitsHeading: "Who Benefits From Cabinet Installation Leads",
    whoBenefitsSubheading: "From independent installers to full kitchen design-build firms, here's who buys cabinet installation leads from Eilite.",
    whoBenefits: [
      { tag: "Local Installers", icon: Home, title: "Independent Cabinet Installers", detail: "Local installers filling their schedule with refacing and install jobs in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Cabinet & Remodel Franchises", detail: "Regional and national brands distributing kitchen-remodel volume across showrooms or territories." },
      { tag: "Custom Cabinetmakers", icon: Boxes, title: "Custom & Semi-Custom Cabinet Makers", detail: "Shops focused on higher-ticket custom builds rather than stock refacing jobs." },
      { tag: "Design-Build Firms", icon: ChefHat, title: "Kitchen Remodel & Design-Build Firms", detail: "Full kitchen remodelers bundling cabinet work into larger renovation projects." },
    ],
    faqs: [
      { q: "Can I target full custom installs and skip refacing-only jobs?", a: "Yes. Campaigns can be configured to target specific project types and minimum budgets, so you're not fielding requests below your shop's focus." },
      { q: "Are cabinet installation leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single installer — never resold or shared with a competing contractor bidding the same job." },
      { q: "Can I target a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit, so you can be the first estimate in front of them." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're quoting a real homeowner with a real project, not a duplicate." },
    ],
  },
  {
    slug: "concrete-coating-lead-generation",
    label: "Concrete Coating",
    category: "Home Services",
    keywords: ["concrete coating", "epoxy"],
    tagline: "Own a Niche",
    highlight: "With Fewer Contractors to Compete Against",
    subheadline:
      "Get exclusive concrete coating and epoxy flooring leads — garage floors, driveways, and patios — filtered by project type and delivered before homeowners default to a big-box franchise.",
    metaDescription:
      "Get exclusive concrete coating and epoxy flooring leads for garage floors, driveways, and patios, filtered by project type.",
    searchChips: ["garage floor epoxy cost", "concrete driveway coating near me", "epoxy flooring installer"],
    demoIndustry: "Concrete Coating",
    overviewEyebrow: "The Problem",
    overviewHeading: "Concrete coating is a newer category, and awareness is still the biggest obstacle",
    overviewParagraphs: [
      "Concrete coating and epoxy flooring is a newer, higher-margin niche compared to most home services, which cuts both ways — fewer contractors compete for each job, but a lot of homeowners still don't fully understand what they're buying, confusing a professional polyaspartic or epoxy system with a DIY garage floor kit from a hardware store. That confusion stretches out research time, and because there are fewer specialized contractors per market, the ones who exist are often competing against a couple of national franchise brands with much bigger ad budgets rather than a crowded field of local competitors.",
      "We deliver concrete coating leads filtered by project type — garage floors, driveways, patios, and commercial/industrial coating — and by homeowner intent, screening out DIY researchers so your estimator only hears from people ready to hire a professional. Leads are sourced from owned, high-intent pages or a small set of vetted publishers, never resold generic remodel lists, and verified for real contact info before delivery.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by project type — garage floor, driveway, patio, and commercial/industrial coating",
      "Filtered to screen out DIY researchers so you're quoting homeowners ready to hire a pro",
      "Exclusive delivery, never resold to another coating contractor or franchise in your market",
      "Real-time delivery so you can quote before the homeowner defaults to a national brand",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect concrete coating contractors with homeowners and facilities ready to hire a pro — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Concrete Coating Customer", detail: "We qualify by project type — garage floor, driveway, patio, or commercial/industrial — plus whether the homeowner intends to hire a pro or is still comparing DIY kits." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real hiring intent, filtering out DIY researchers before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard residential jobs deliver as web-form leads; larger commercial and industrial flooring inquiries can route as inbound calls for faster scoping." },
      { title: "Scale With Demand", detail: "Volume adjusts as awareness of professional coating systems grows in your market, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Concrete Coating Leads",
    whoBenefitsSubheading: "From independent contractors to industrial flooring specialists, here's who buys concrete coating leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Independent Concrete Coating Contractors", detail: "Local crews filling their schedule with garage and driveway coating jobs in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Coating Franchises & Multi-Crew Companies", detail: "Regional and national brands distributing volume across crews and territories." },
      { tag: "Industrial Flooring", icon: Factory, title: "Commercial & Industrial Flooring Contractors", detail: "Crews focused on higher-volume warehouse and industrial coating jobs rather than single residential garages." },
      { tag: "Concrete Contractors", icon: Hammer, title: "Concrete Contractors Adding Coatings", detail: "Existing flatwork and concrete companies expanding into decorative coatings without building a coatings-specific pipeline first." },
    ],
    faqs: [
      { q: "Can I target residential garage/driveway jobs versus commercial coating?", a: "Yes. Campaigns can be configured to your target project types — residential garage, driveway, and patio coating, or commercial and industrial flooring." },
      { q: "Are concrete coating leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single contractor — never resold or shared with a competing coating company." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit, so you can quote while they're still comparing options." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're quoting a real homeowner with a real project, not a duplicate." },
    ],
  },
  {
    slug: "decks-lead-generation",
    label: "Decks",
    category: "Home Services",
    keywords: ["deck"],
    tagline: "Book Deck Season Early",
    highlight: "Before Your Competitors Get There First",
    subheadline:
      "Get exclusive deck building, replacement, and repair leads — filtered by project size and material preference so your crew is booked solid through the spring and summer rush.",
    metaDescription:
      "Get exclusive deck building, replacement, and repair leads, filtered by project size and material preference to keep your crew booked solid.",
    searchChips: ["deck builder near me", "composite deck installation cost", "deck repair and staining"],
    demoIndustry: "Decks",
    overviewEyebrow: "The Problem",
    overviewHeading: "Deck demand is brutally seasonal, and the first quote usually wins",
    overviewParagraphs: [
      "Deck projects cluster hard into spring and early summer, when every homeowner wants a new or rebuilt deck ready before backyard season — which means your crew goes from slow to slammed almost overnight, and the contractors who respond fastest in that window are the ones who fill their calendar first. Homeowners typically collect several quotes before committing, and the first credible estimate tends to set the price expectation the rest get measured against, so a slow lead-delivery pipeline doesn't just cost you a job, it costs you the pricing advantage.",
      "We deliver deck leads filtered by project type and size — new build, full replacement, or repair/refinishing — and by material preference (wood, composite, PVC), sourced from owned, high-intent pages or a small set of vetted publishers, never resold seasonal remodel lists. Every lead is verified for real contact info and real project scope before it reaches your estimator, delivered fast enough to be the first quote in the homeowner's inbox.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by project type — new build, full replacement, and repair/refinishing",
      "Filtered by material preference — wood, composite, or PVC — so you're quoting the right scope",
      "Exclusive delivery, never resold to another deck builder bidding the same job",
      "Volume that ramps up ahead of spring/summer demand and scales back in the off-season",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect deck builders with homeowners ready to book before the season fills up — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Deck Customer", detail: "We qualify by project type — new build, full replacement, or repair/refinishing — plus material preference and budget." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real project scope, so you're not quoting a job that's already gone before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard builds and repairs deliver as web-form leads; larger custom outdoor-living projects can route as inbound calls so your estimator can scope the job before quoting." },
      { title: "Scale With the Season", detail: "Volume ramps up ahead of spring and summer demand and pulls back in the off-season, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Deck Leads",
    whoBenefitsSubheading: "From single-crew builders to outdoor living design-build firms, here's who buys deck leads from Eilite.",
    whoBenefits: [
      { tag: "Local Builders", icon: Home, title: "Independent Deck Builders", detail: "Local crews filling their calendar with new builds and replacements in a defined service area." },
      { tag: "Franchises", icon: Building2, title: "Deck Building Franchises & Multi-Crew Companies", detail: "Regional and national brands distributing seasonal volume across crews and territories." },
      { tag: "Composite Specialists", icon: Layers, title: "Composite & Premium Decking Specialists", detail: "Builders focused on higher-margin composite and PVC systems rather than basic wood repairs." },
      { tag: "Outdoor Living Builders", icon: Fence, title: "Outdoor Living & Patio Builders", detail: "Broader outdoor construction companies bundling deck work with patios, pergolas, and fencing projects." },
    ],
    faqs: [
      { q: "Can I target composite deck builds and skip smaller repair jobs?", a: "Yes. Campaigns can be configured to target specific project types, materials, and minimum budgets, so you're not fielding requests below your crew's focus." },
      { q: "Are deck leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single deck builder — never resold or shared with a competing contractor bidding the same job." },
      { q: "Can I set a specific service area?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually serve." },
      { q: "How fast are leads delivered?", a: "Web-form leads deliver in real time as homeowners submit, so your estimate can be the first one in front of them." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before delivery — so you're quoting a real homeowner with a real backyard, not a duplicate." },
    ],
  },
];
