import { Home, Building2, CloudRain, HardHat, Thermometer, Wrench, Droplet, Sun, TreePine, Sparkles } from "lucide-react";
import type { SolutionVertical } from "./types";

export const homeServices1: SolutionVertical[] = [
  {
    slug: "roofing-lead-generation",
    label: "Roofing",
    category: "Home Services",
    keywords: ["roofing", "roof"],
    tagline: "More Roofing Jobs,",
    highlight: "Less Wasted Ad Spend",
    subheadline:
      "Connect with homeowners who need a new roof, storm-damage repair, or a full replacement — verified, filtered by job type and budget, and delivered exclusively to your crew.",
    metaDescription:
      "Connect with homeowners who need a new roof, storm-damage repair, or replacement, verified, filtered by job type and budget, delivered exclusively.",
    searchChips: ["roof replacement cost", "roof leak repair near me", "storm damage roof inspection"],
    demoIndustry: "Roofing",
    overviewEyebrow: "The Problem",
    overviewHeading: "Roofing leads are expensive to chase and easy to lose",
    overviewParagraphs: [
      "Roofing has one of the longest sales cycles in home services — a homeowner comparing three or four quotes before they commit, storm-damage jobs that spike and vanish with the season, and price-shoppers who ghost the moment insurance gets involved. Meanwhile every major review site and directory is charging more for the same recycled contact info.",
      "We fix the front half of that problem. Every roofing lead we deliver is captured on owned, high-intent landing pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact info, real intent, and real project scope before it reaches your team.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by job type — full replacement, repair, storm damage, or inspection",
      "Delivered once, exclusively to you — never sold to a competing crew in your market",
      "Real-time delivery so you can call while the homeowner is still comparing quotes",
      "Combine web-form leads with live warm transfers when you need faster-closing volume",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect roofing contractors with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Roofing Customer", detail: "We qualify by job type, roof age, property type, budget, and the ZIP codes or counties you actually service." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and real intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Take it as a web-form lead, a live warm transfer connected while the homeowner is on the phone, or a routed inbound call — whatever fits how your team closes." },
      { title: "Scale With the Season", detail: "Volume flexes up for storm season and spring replacement demand, and down in slower months, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Roofing Leads",
    whoBenefitsSubheading: "From single-crew operators to multi-market restoration companies, here's who buys roofing leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Roofing Contractors", detail: "Independent crews filling their calendar with homeowners in a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Roofing Franchises & Multi-Location Companies", detail: "Regional and national brands routing volume across multiple branches or territories." },
      { tag: "Storm Restoration", icon: CloudRain, title: "Storm & Hail Restoration Companies", detail: "Crews that ramp fast after severe weather and need verified, insurance-ready leads immediately." },
      { tag: "General Contractors", icon: HardHat, title: "General Contractors Adding Roofing", detail: "Remodeling and construction companies expanding into roofing without building their own pipeline first." },
    ],
    faqs: [
      { q: "What types of roofing leads can I buy?", a: "Full roof replacements, repairs, storm and hail damage, inspections, and re-roofing projects — filtered by property type, roof age, and job budget so you're not paying for jobs outside your scope." },
      { q: "Are roofing leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single roofing contractor — never resold or shared with competitors bidding in your market." },
      { q: "Can I target specific cities or a service radius?", a: "Yes. Campaigns are built around the ZIP codes, counties, or metro areas you actually serve, so you're not paying to chase jobs outside your crew's range." },
      { q: "How fast are leads delivered?", a: "Web-form leads are delivered in real time as homeowners submit. Warm transfers connect you live, on the phone, while the homeowner is still in the moment of deciding." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection, phone and address validation, and TCPA/DNC compliance checks before it's ever delivered — so you're calling a real homeowner, not a bot or a duplicate." },
    ],
  },
  {
    slug: "hvac-lead-generation",
    label: "HVAC",
    category: "Home Services",
    keywords: ["hvac"],
    tagline: "Fill Your HVAC Calendar",
    highlight: "With Ready-to-Book Homeowners",
    subheadline:
      "From emergency no-heat calls to full system replacements, get exclusive HVAC leads filtered by job urgency, system type, and budget — delivered the moment a homeowner is ready to talk.",
    metaDescription:
      "From emergency no-heat calls to full system replacements, get exclusive HVAC leads filtered by urgency, system type, and budget.",
    searchChips: ["AC repair near me", "furnace not working", "new HVAC system cost"],
    demoIndustry: "HVAC",
    overviewEyebrow: "The Problem",
    overviewHeading: "HVAC demand is seasonal, urgent, and easy to lose to the fastest caller",
    overviewParagraphs: [
      "HVAC leads live and die by speed — a homeowner with no AC in July or no heat in January is calling three companies at once, and whoever answers first usually books the job. Shared leads and slow follow-up cost you jobs you'd otherwise win on service alone.",
      "We deliver HVAC leads and live warm transfers built for that urgency: real-time delivery, exclusive to your business, and pre-filtered by job type so your team spends time closing instead of qualifying.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by job type — repair, replacement, maintenance plans, or new install",
      "Live warm transfers for emergency no-heat/no-cool calls that need an answer now",
      "Exclusive delivery — never resold to another HVAC company in your area",
      "Scale volume up during peak season and dial it back in the off-season",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We route HVAC demand to your team as leads, live warm transfers, or inbound calls — matched to how urgent the job is.",
    howItWorksSteps: [
      { title: "Define Your Ideal HVAC Customer", detail: "We qualify by system type, job type, property type, and the service area your crews actually cover." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real intent the moment it's captured, before it's counted as a lead." },
      { title: "Choose Your Delivery", detail: "Standard jobs deliver as web-form leads; no-heat and no-cool emergencies route as live warm transfers so your dispatcher can respond immediately." },
      { title: "Scale With Demand", detail: "Volume ramps up in peak summer and winter weeks and pulls back in the shoulder seasons, without a new contract each time." },
    ],
    whoBenefitsHeading: "Who Benefits From HVAC Leads",
    whoBenefitsSubheading: "From single-truck operators to multi-branch service companies, here's who buys HVAC leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local HVAC Contractors", detail: "Independent techs and small crews filling their schedule within a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "HVAC Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing volume across branches or dispatch zones." },
      { tag: "Emergency Service", icon: Thermometer, title: "24/7 Emergency Service Providers", detail: "Companies built around fast response to no-heat and no-cool calls that need a live transfer, not a form." },
      { tag: "Maintenance Plans", icon: Wrench, title: "Maintenance Plan & Tune-Up Providers", detail: "Businesses growing recurring service agreements alongside one-time repair and install work." },
    ],
    faqs: [
      { q: "Do you offer emergency HVAC leads, not just scheduled work?", a: "Yes. We route urgent no-heat and no-cool calls as live warm transfers so your team can respond immediately, alongside standard web-form leads for maintenance and replacement work." },
      { q: "Can I choose residential, commercial, or both?", a: "Yes. Campaigns are configured to your target property type, system type, and service area before any leads are delivered." },
      { q: "Are HVAC leads exclusive?", a: "Every lead and transfer is sold once, to a single HVAC contractor — never resold or shared with a competitor in the same market." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for phone and address accuracy, and checked against TCPA/DNC lists before delivery." },
      { q: "How quickly can I start receiving leads?", a: "Most HVAC campaigns can launch within days of confirming your service area, job types, and volume needs on a demo call." },
    ],
  },
  {
    slug: "plumbing-lead-generation",
    label: "Plumbing",
    category: "Home Services",
    keywords: ["plumbing", "plumber"],
    tagline: "Book More Plumbing Jobs,",
    highlight: "From Emergencies to Remodels",
    subheadline:
      "Get exclusive plumbing leads — from burst-pipe emergencies to water heater installs and full re-pipes — filtered by job type and delivered while the homeowner still needs help now.",
    metaDescription:
      "Get exclusive plumbing leads, from burst-pipe emergencies to water heater installs and re-pipes, filtered by job type and delivered fast.",
    searchChips: ["emergency plumber near me", "water heater replacement cost", "drain cleaning service"],
    demoIndustry: "Plumbing",
    overviewEyebrow: "The Problem",
    overviewHeading: "Plumbing emergencies don't wait, and neither do your competitors",
    overviewParagraphs: [
      "A homeowner with a burst pipe or a backed-up drain isn't comparison shopping for a week — they're calling everyone on the first page of results and booking whoever answers. Slow lead delivery and shared contact lists mean you're often the third or fourth call, not the first.",
      "We deliver plumbing leads and warm transfers built for that reality: real-time routing, exclusivity, and filtering by job type so emergency calls reach you the moment they happen, not hours later.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by urgency — emergency repair, scheduled service, or install/remodel work",
      "Live warm transfers for burst pipes, backups, and no-water emergencies",
      "Exclusive delivery, never resold to another plumbing company in your market",
      "Filter by residential, commercial, or both based on your crew's focus",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We route plumbing demand to your team as leads, live warm transfers, or inbound calls — matched to how urgent the job is.",
    howItWorksSteps: [
      { title: "Define Your Ideal Plumbing Customer", detail: "We qualify by job type, property type, and the ZIP codes or metro areas your crews actually service." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud and real intent the moment it's captured, before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Scheduled work delivers as web-form leads; burst pipes, backups, and no-water emergencies route as live warm transfers straight to your dispatcher." },
      { title: "Scale With Demand", detail: "Volume flexes with seasonal spikes like winter freeze events, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Plumbing Leads",
    whoBenefitsSubheading: "From single-truck operators to multi-branch service companies, here's who buys plumbing leads from Eilite.",
    whoBenefits: [
      { tag: "Local Contractors", icon: Home, title: "Local Plumbing Contractors", detail: "Independent plumbers and small crews filling their schedule within a defined service radius." },
      { tag: "Franchises", icon: Building2, title: "Plumbing Franchises & Multi-Branch Companies", detail: "Regional and national brands distributing volume across branches or dispatch zones." },
      { tag: "Emergency Service", icon: Droplet, title: "24/7 Emergency Plumbers", detail: "Companies built around fast response to burst pipes, backups, and no-water calls that need a live transfer, not a form." },
      { tag: "Remodel & Install", icon: Wrench, title: "Water Heater & Re-Pipe Specialists", detail: "Businesses focused on higher-ticket install and remodel work alongside routine repair calls." },
    ],
    faqs: [
      { q: "Can I get emergency plumbing calls in real time?", a: "Yes. Emergency calls — burst pipes, backups, no hot water — can be routed as live warm transfers so your dispatcher can respond immediately." },
      { q: "What plumbing job types can I target?", a: "Repairs, drain cleaning, water heater installation, re-pipes, and remodel/rough-in work — filtered to the services your business actually offers." },
      { q: "Are the leads exclusive to my business?", a: "Yes. Every lead and transfer is sold once, never resold or shared with a competing plumber in your area." },
      { q: "How is lead quality verified?", a: "Every submission goes through fraud screening, contact verification, and TCPA/DNC compliance checks before delivery." },
      { q: "Can I set a specific service radius?", a: "Yes. Campaigns are built around the ZIP codes or metro areas you actually service." },
    ],
  },
  {
    slug: "solar-lead-generation-power-your-pipeline-with-high-intent-leads",
    label: "Solar",
    category: "Home Services",
    keywords: ["solar"],
    tagline: "Power Your Pipeline",
    highlight: "With High-Intent Solar Leads",
    subheadline:
      "Reach homeowners actively researching solar — pre-qualified by homeownership, roof suitability, and utility bill size — so your reps spend time closing, not disqualifying.",
    metaDescription:
      "Reach homeowners actively researching solar, pre-qualified by homeownership, roof suitability, and utility bill size, so reps spend time closing.",
    searchChips: ["solar panel cost", "is solar worth it", "solar installation near me"],
    demoIndustry: "Solar",
    overviewEyebrow: "The Problem",
    overviewHeading: "Solar has a long sales cycle and a low tolerance for bad data",
    overviewParagraphs: [
      "Solar deals often take weeks to close and involve real money — which means a lead with a bad phone number, a renter instead of a homeowner, or a shaded roof isn't just wasted spend, it's wasted rep hours. Volume without qualification is the fastest way to burn a solar sales team's trust in your leads.",
      "Every solar lead we deliver is pre-qualified on the fields that actually matter to a close — homeownership, roof condition, average utility bill, and credit tier where applicable — and verified for real contact info before it reaches your CRM.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-qualified by homeownership, roof suitability, and average monthly utility bill",
      "Exclusive delivery — never resold to a competing installer or sales org",
      "Real-time CRM integration so reps can call while intent is highest",
      "Live warm transfers available for teams that want appointment-set leads",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect solar installers and sales orgs with pre-qualified homeowners — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Solar Customer", detail: "We qualify by homeownership, roof condition, average utility bill, and the states or utility territories you're licensed in." },
      { title: "Capture & Pre-Qualify", detail: "Interest is captured on owned pages or vetted publisher sites, then filtered against your qualification criteria before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Take raw web-form leads into your CRM, or take live warm transfers with a homeowner already on the phone for teams that want appointment-set volume." },
      { title: "Refine as You Scale", detail: "We tune targeting and qualification criteria against your close rate as volume grows, so cost per acquisition keeps improving." },
    ],
    whoBenefitsHeading: "Who Benefits From Solar Leads",
    whoBenefitsSubheading: "From regional installers to national sales organizations, here's who buys solar leads from Eilite.",
    whoBenefits: [
      { tag: "Installers", icon: Home, title: "Regional Solar Installers", detail: "Installation companies filling their pipeline with pre-qualified homeowners in their licensed territory." },
      { tag: "National Orgs", icon: Building2, title: "National Solar Sales Organizations", detail: "Multi-state sales orgs distributing appointment-set volume across regional teams." },
      { tag: "Appointment Setters", icon: Sun, title: "Appointment-Setting Teams", detail: "Teams that want live warm transfers with a pre-qualified homeowner already on the line." },
      { tag: "Financing Partners", icon: Sparkles, title: "Solar Financing & Leasing Partners", detail: "Partners qualifying homeowners on credit tier alongside roof and utility bill fit." },
    ],
    faqs: [
      { q: "How are solar leads qualified before delivery?", a: "Leads are filtered on homeownership status, roof condition and orientation, and average monthly utility bill — the factors that determine whether a homeowner is actually a fit for solar." },
      { q: "Are solar leads exclusive?", a: "Yes. Every lead is sold once, to a single installer or sales organization — never resold or shared." },
      { q: "Can I target specific states or utility territories?", a: "Yes. Solar campaigns are built around your licensed states and the utility territories where your incentives and financing options apply." },
      { q: "Do you offer appointment-set leads or just raw contacts?", a: "Both. Standard web-form leads deliver in real time, and live warm transfers are available for teams that want a homeowner already on the phone before handoff." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud detection and contact verification, and is checked against TCPA/DNC compliance requirements before delivery." },
    ],
  },
  {
    slug: "landscaping-lead-generation-performance-based-growth-for-landscaping-businesses",
    label: "Landscaping",
    category: "Home Services",
    keywords: ["landscaping", "lawn"],
    tagline: "Grow Your Landscaping Book",
    highlight: "Without Growing Your Ad Budget",
    subheadline:
      "Get exclusive landscaping leads — from routine lawn care to full design-and-build projects — filtered by service type and job size so your crews stay booked without chasing bad-fit work.",
    metaDescription:
      "Get exclusive landscaping leads, from routine lawn care to full design-and-build projects, filtered by service type and job size.",
    searchChips: ["landscaping company near me", "lawn care service cost", "backyard landscape design"],
    demoIndustry: "Landscaping",
    overviewEyebrow: "The Problem",
    overviewHeading: "Landscaping leads range from $50 lawn mows to $50,000 backyards",
    overviewParagraphs: [
      "A generic \"landscaping lead\" could be a one-time mow or a full outdoor renovation — and paying the same rate for both wrecks your economics. Seasonal spikes make it worse: everyone wants spring cleanup at once, and slow follow-up means the homeowner has already booked someone else.",
      "We filter landscaping leads by service type and estimated job size before they ever reach you, so routine maintenance requests and design-and-build inquiries route separately — and your best crews spend time on the jobs worth their time.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads separated by service type — maintenance, hardscaping, design-and-build, irrigation",
      "Exclusive delivery, never resold to another landscaping company in your market",
      "Seasonal volume that scales up for spring/summer demand and down in the off-season",
      "Real-time delivery so you can quote while the homeowner is still comparing",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect landscaping businesses with homeowners ready to book — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Landscaping Customer", detail: "We qualify by service type, estimated job size, and the ZIP codes or neighborhoods you actually serve." },
      { title: "Capture & Screen in Real Time", detail: "Homeowner interest is captured on owned pages or vetted publisher sites, then screened for fraud and real intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Routine maintenance requests deliver as web-form leads; larger design-and-build inquiries can route as live warm transfers for faster follow-up." },
      { title: "Scale With the Season", detail: "Volume ramps up for spring cleanup and summer demand and pulls back in the off-season, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Landscaping Leads",
    whoBenefitsSubheading: "From single-crew operators to multi-service outdoor companies, here's who buys landscaping leads from Eilite.",
    whoBenefits: [
      { tag: "Local Crews", icon: Home, title: "Local Landscaping Crews", detail: "Independent operators filling their schedule with mowing, cleanup, and maintenance work in a defined radius." },
      { tag: "Design-Build", icon: Sparkles, title: "Design-and-Build Firms", detail: "Companies focused on higher-ticket hardscaping and full outdoor renovation projects." },
      { tag: "Multi-Service", icon: Building2, title: "Multi-Service Outdoor Companies", detail: "Businesses combining lawn care, irrigation, and hardscaping under one crew or franchise." },
      { tag: "Irrigation", icon: TreePine, title: "Irrigation & Lawn Care Specialists", detail: "Teams focused on recurring seasonal service agreements alongside one-time projects." },
    ],
    faqs: [
      { q: "Can I get only high-value design-and-build leads, not routine mowing?", a: "Yes. Campaigns can be configured to target specific service types and estimated job sizes, so you're not paying for work below your minimum." },
      { q: "Are landscaping leads exclusive?", a: "Yes. Every lead is sold once, to a single landscaping business — never resold or shared with a competitor in your service area." },
      { q: "Can I set a service radius?", a: "Yes. Campaigns are built around the ZIP codes, neighborhoods, or counties you actually serve." },
      { q: "How is lead quality verified?", a: "Every submission is screened for fraud, verified for accurate contact info, and checked against TCPA/DNC compliance requirements." },
      { q: "Can volume scale with the season?", a: "Yes. Most landscaping businesses ramp volume up heading into spring and summer and scale back in slower months — campaigns adjust with you." },
    ],
  },
];
