import type { SolutionVertical } from "./types";

export const insuranceSolutions: SolutionVertical[] = [
  {
    slug: "business-insurance-lead-generation",
    label: "Business Insurance",
    category: "Insurance",
    keywords: ["business-insurance", "business insurance"],
    tagline: "More Bindable Business Insurance Leads,",
    highlight: "Not More Tire-Kickers",
    subheadline:
      "Connect with business owners actively shopping general liability, workers' comp, commercial property, and BOP coverage — filtered by industry, employee count, and revenue, and delivered straight to your producers.",
    searchChips: ["general liability insurance quote", "workers comp cost for small business", "commercial property insurance near me"],
    demoIndustry: "Business Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Commercial insurance leads swing wildly in size, industry, and readiness to bind",
    overviewParagraphs: [
      "A \"business insurance lead\" could be a solo contractor shopping a $600 policy or a 200-employee manufacturer needing a layered commercial package — and treating them the same wrecks producer time. Add in sales cycles that stretch across renewal dates and multiple decision-makers, coverage requests that get routed to the wrong line of business, and broad keyword traffic that's researching insurance concepts instead of actually requesting a quote, and most agencies end up paying full price for leads that were never close to binding.",
      "Every business insurance lead we deliver is pre-qualified on the fields that actually predict a bind — industry class code, employee count, revenue band, and the specific coverage line requested — and runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and TCPA/DNC compliance screening before it ever reaches your producers. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by coverage line — general liability, workers' comp, commercial property, commercial auto, professional or cyber liability",
      "Pre-qualified by industry class, employee count, and revenue band so producers aren't quoting outside your appetite",
      "Exclusive delivery — never resold to a competing agency or carrier writing in the same market",
      "Live warm transfers available for agents who want a business owner already on the line, ready to talk coverage",
    ],
    faqs: [
      { q: "What business insurance coverage lines can I target?", a: "General liability, workers' compensation, commercial property, commercial auto, professional liability, cyber liability, and BOP packages — filtered by the coverage lines your agency actually writes." },
      { q: "Are business insurance leads exclusive to my agency?", a: "Yes. Every lead is sold once, to a single agency or producer — never resold or shared with a competing agency quoting the same business." },
      { q: "Can I target specific states or licensed territories?", a: "Yes. Campaigns are built around the states you're licensed and appointed in, so every lead delivered is one you can actually write." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as business owners submit. Live warm transfers are also available if you'd rather have a business owner already on the phone before your producer picks up." },
      { q: "How is lead compliance verified?", a: "Every lead is screened against the TCPA Litigator List and DNC.com before delivery, in addition to identity verification and consent certification, so you're never calling a number that puts your agency at risk." },
    ],
  },
  {
    slug: "life-insurance-lead-generation",
    label: "Life Insurance",
    category: "Insurance",
    keywords: ["life-insurance", "life insurance"],
    tagline: "Life Insurance Leads",
    highlight: "Ready for Underwriting, Not Just Curious",
    subheadline:
      "Get exclusive term and whole life insurance leads from prospects who've already worked through coverage type and amount — filtered by age, health class, and enrollment intent so producers spend time closing, not educating.",
    searchChips: ["term life insurance quote", "whole life insurance cost calculator", "life insurance for parents"],
    demoIndustry: "Life Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Most life insurance traffic is curious. Very little of it is underwriting-ready",
    overviewParagraphs: [
      "Life insurance is a crowded, complicated purchase — term versus whole life, coverage amount, riders, and health class all have to click into place before a prospect is actually ready to sit for underwriting. Generic web traffic clicks a calculator, gets a rough number, and disappears; even leads that fill out a form are often still comparing products, not ready to commit, which means agents burn calls re-explaining basics to people who were never close to applying.",
      "Every life insurance lead we deliver is filtered for real underwriting-stage intent — not just calculator curiosity — and verified for age, coverage amount, and stated health information before it's ever sent. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by product type — term, whole, universal, or final expense — so you're matched to the right underwriting path",
      "Filtered by age, coverage amount requested, and stated health class, not just contact info",
      "Exclusive delivery, sold once and never resold to a competing agent or IMO",
      "Live warm transfers available for agents who want a prospect already engaged and ready to talk policy details",
    ],
    faqs: [
      { q: "What life insurance lead types are available?", a: "Term, whole, universal, and final expense leads, filtered by age, requested coverage amount, and stated health class so you're working prospects that match your appetite." },
      { q: "Are life insurance leads exclusive?", a: "Yes. Every lead is sold once, to a single agent or agency — never resold or shared with a competing producer." },
      { q: "Can I target specific states or licensed lines?", a: "Yes. Campaigns are built around the states and product lines you're licensed to write, so you only receive leads you can actually close." },
      { q: "How fast do I get the lead, and can I get a live transfer instead?", a: "Web-form leads route in real time as prospects submit. Live warm transfers are also available if you'd rather have someone already on the phone, engaged and ready to discuss coverage." },
      { q: "How is compliance handled?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, plus identity verification and documented consent, before it's delivered — so your agency stays protected on every call you make." },
    ],
  },
  {
    slug: "pet-insurance-lead-generation",
    label: "Pet Insurance",
    category: "Insurance",
    keywords: ["pet-insurance", "pet insurance"],
    tagline: "Pet Insurance Leads",
    highlight: "Before the Owner Picks a Competitor",
    subheadline:
      "Reach pet owners actively comparing coverage right after adoption, a vet visit, or a diagnosis — filtered by pet age, species, and pre-existing conditions, and delivered while they're still deciding who to buy from.",
    searchChips: ["pet insurance cost", "best pet insurance for dogs", "does pet insurance cover pre-existing conditions"],
    demoIndustry: "Pet Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Pet insurance decisions happen fast, and owners compare three plans in one sitting",
    overviewParagraphs: [
      "Pet insurance is still a newer, lower-consideration category than most insurance lines — owners typically start shopping after a specific trigger (a new puppy, a surprise vet bill, a breed known for health issues) and make a decision within days, often with two or three provider tabs open at once. That short window means a lead that sits for even an hour is likely already enrolled somewhere else, and generic traffic that hasn't nailed down the pet's age, species, or pre-existing conditions wastes calls on quotes you can't actually honor.",
      "Every pet insurance lead we deliver is captured close to the moment of decision and filtered on the details that determine insurability — pet age, species and breed, and any pre-existing conditions — before it's sent. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by pet species, breed, and age so you're quoting policies you can actually underwrite",
      "Flagged for pre-existing conditions upfront, so your team isn't surprised mid-call",
      "Exclusive delivery — never resold to a competing pet insurance provider or comparison site",
      "Real-time delivery so you can reach the owner while they're still comparing plans, not after they've enrolled",
    ],
    faqs: [
      { q: "What pet details come with each lead?", a: "Species, breed, age, and any disclosed pre-existing conditions — the fields that determine what coverage and pricing you can actually offer." },
      { q: "Are pet insurance leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single provider — never resold or shared with a competing pet insurance company." },
      { q: "Can I target specific states or coverage types?", a: "Yes. Campaigns are built around the states you're licensed to write in and the coverage tiers — accident-only, accident and illness, or wellness add-ons — you actually sell." },
      { q: "How fast are leads delivered, and are live transfers available?", a: "Web-form leads deliver in real time as owners submit. Live warm transfers are also available for teams that want an owner already on the phone before handoff." },
      { q: "How is lead quality and compliance verified?", a: "Every lead is checked against the TCPA Litigator List and DNC.com, along with identity verification and consent certification, before it's delivered — so you're calling a real, reachable pet owner." },
    ],
  },
  {
    slug: "senior-care-lead-generation",
    label: "Senior Care",
    category: "Insurance",
    keywords: ["medicare", "senior-care"],
    tagline: "Senior Care Leads",
    highlight: "Screened for Real Eligibility, Not Just a Zip Code",
    subheadline:
      "Connect with seniors and families actively evaluating Medicare plans, in-home care, or placement options — screened for age, location, and current coverage, and handled with the compliance a heavily regulated category demands.",
    searchChips: ["medicare advantage plans near me", "in-home senior care cost", "assisted living options for parents"],
    demoIndustry: "Senior Care",
    overviewEyebrow: "The Problem",
    overviewHeading: "Senior-focused leads carry more compliance risk and less room for guesswork",
    overviewParagraphs: [
      "Senior care and Medicare-adjacent leads are a different animal from most consumer categories. The buyer is often an adult child researching on a parent's behalf, real eligibility depends on hard filters like age, ZIP code, and current coverage that a generic form never confirms, and the category is one of the most heavily regulated in all of marketing — a single mistargeted or non-consented call can trigger real regulatory exposure, not just a wasted dial. Volume without real screening is a liability here, not just a cost problem.",
      "Every senior care lead we deliver is screened for the eligibility fields that actually matter — age, location, and current coverage status — before it's sent, and handled with the sensitivity this audience deserves. Each one runs through real-time fraud detection, identity verification, consent certification via Jornaya or TrustedForm, and TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads pre-screened for age, ZIP code, and current coverage status before they ever reach your team",
      "Split by need — Medicare Advantage, Medigap, in-home care, or assisted living placement",
      "Exclusive delivery — never resold to a competing agent, agency, or care provider",
      "Live warm transfers available for agents who want a screened senior or family member already on the phone",
    ],
    faqs: [
      { q: "What senior care and Medicare-adjacent lead types are available?", a: "Medicare Advantage, Medigap/Medicare Supplement, in-home care, and assisted living or memory care placement leads — filtered by the specific need your team serves." },
      { q: "Are senior care leads exclusive to my agency or organization?", a: "Yes. Every lead is sold once, to a single agent, agency, or care provider — never resold or shared with a competitor." },
      { q: "Can I target specific states or licensed service areas?", a: "Yes. Campaigns are built around the states you're licensed in or the counties your care organization actually serves, with eligibility screened before delivery." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as families submit. Live warm transfers are also available if you'd rather have a screened senior or family member already on the phone." },
      { q: "How is compliance handled given how regulated this space is?", a: "Every lead is screened against the TCPA Litigator List and DNC.com, in addition to identity verification and documented consent certification, before it's ever delivered — critical given how closely senior-targeted marketing is regulated." },
    ],
  },
];
