import { UserCheck, Building2, Phone, ShieldCheck, Car, Home } from "lucide-react";
import type { SolutionVertical } from "./types";

export const insuranceSolutions2: SolutionVertical[] = [
  {
    slug: "health-insurance-lead-generation",
    label: "Health Insurance",
    category: "Insurance",
    keywords: ["health-insurance"],
    tagline: "Health Insurance Leads",
    highlight: "Timed to When Buyers Actually Enroll",
    subheadline:
      "Connect with individuals and families shopping ACA marketplace and off-exchange health coverage — filtered by subsidy eligibility and enrollment window, and delivered while they're still comparing plans, not after they've picked one.",
    metaDescription:
      "Connect with individuals and families shopping ACA marketplace and off-exchange coverage, filtered by subsidy eligibility and enrollment window.",
    searchChips: ["health insurance marketplace plans", "affordable health insurance for self employed", "health insurance open enrollment deadline"],
    demoIndustry: "Health Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Health insurance demand spikes hard, then buyers shop five agents at once",
    overviewParagraphs: [
      "Health insurance leads behave like almost no other category: volume concentrates violently around open enrollment and special enrollment triggers like job loss or a move, and inside that narrow window a single shopper is often filling out three or four different forms, comparing subsidized marketplace plans against off-exchange options within minutes of each other. A generic lead that doesn't distinguish subsidy-eligible buyers from those shopping full-price coverage wastes a call explaining basics to someone who already knows what they want, or worse, pitching a plan type the prospect doesn't even qualify for.",
      "Every health insurance lead we deliver is filtered for real enrollment-stage intent — not calculator curiosity — and flagged for subsidy eligibility signals and enrollment window so your team pitches the right plan type from the first call. Each one runs through real-time fraud detection, identity verification, consent certification, and TCPA/DNC compliance screening before it ever reaches you. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads split by marketplace versus off-exchange intent, so producers aren't guessing which subsidy conversation applies",
      "Volume that scales with open enrollment and special enrollment periods, timed to when shoppers are actually deciding",
      "Exclusive delivery — never resold to a competing agent, agency, or call center working the same enrollment window",
      "Live warm transfers available for agents who want a shopper already on the line before the window closes",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect agents and agencies with individuals and families ready to enroll in health coverage — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Health Insurance Customer", detail: "We qualify by household size, subsidy eligibility signals, current coverage status, and marketplace versus off-exchange intent." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud, documented consent, and real enrollment-stage intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Take it as a web-form lead, a live warm transfer with the shopper already on the line, or a routed inbound call — whatever fits your enrollment team." },
      { title: "Scale With Open Enrollment", detail: "Volume ramps hard around Open Enrollment and Special Enrollment Periods, then pulls back the rest of the year, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Health Insurance Leads",
    whoBenefitsSubheading: "From independent ACA agents to national enrollment call centers, here's who buys health insurance leads from Eilite.",
    whoBenefits: [
      { tag: "Independent Agents", icon: UserCheck, title: "Independent ACA Marketplace Agents", detail: "Licensed agents enrolling individuals and families in subsidized marketplace plans within their state." },
      { tag: "Agencies", icon: Building2, title: "Health Insurance Agencies & FFM Brokers", detail: "Multi-agent shops distributing volume across producers by state and plan type." },
      { tag: "Call Centers", icon: Phone, title: "Licensed Enrollment Call Centers", detail: "High-volume teams built to handle the compressed rush of open enrollment and SEP demand." },
      { tag: "Off-Exchange Carriers", icon: ShieldCheck, title: "Off-Exchange & Short-Term Plan Providers", detail: "Providers enrolling shoppers who don't qualify for subsidies or want coverage outside the marketplace." },
    ],
    faqs: [
      { q: "What qualification criteria are used for health insurance leads?", a: "Leads are filtered for current shopping intent, household and coverage details relevant to marketplace versus off-exchange fit, and enrollment window timing, so your producers aren't working stale or mismatched prospects." },
      { q: "Are health insurance leads exclusive to my agency?", a: "Yes. Every lead is sold once, to a single agent or agency — never resold or shared with a competing producer working the same enrollment period." },
      { q: "Can I target specific states or licensed territories?", a: "Yes. Campaigns are built around the states and marketplaces you're licensed to write in, so every lead delivered is one you can actually enroll." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as shoppers submit. Live warm transfers are also available if you'd rather have a prospect already engaged and ready to enroll before your producer picks up." },
      { q: "How is lead compliance verified?", a: "Every lead is screened against the TCPA Litigator List and DNC.com before delivery, in addition to identity verification and consent certification, so you're never calling a number that puts your agency at risk." },
    ],
  },
  {
    slug: "auto-insurance-lead-generation",
    label: "Auto Insurance",
    category: "Insurance",
    keywords: ["auto-insurance"],
    tagline: "Auto Insurance Leads",
    highlight: "Reached Before They Pick the Cheapest Quote",
    subheadline:
      "Get exclusive auto insurance leads from drivers actively requesting quotes — filtered by vehicle count, driving record, and coverage type, and delivered fast enough to win a category where price and speed decide the sale.",
    metaDescription:
      "Get exclusive auto insurance leads from drivers actively requesting quotes, filtered by vehicle count, driving record, and coverage type.",
    searchChips: ["cheap car insurance quotes near me", "auto insurance quote comparison", "car insurance for high risk drivers"],
    demoIndustry: "Auto Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Auto insurance is the most commoditized, price-driven category in the industry",
    overviewParagraphs: [
      "A driver requesting a car insurance quote is almost never talking to just one agent — most auto insurance leads are actively submitting the same request to five or more carriers within the same sitting, which means every minute of delay is a minute a competitor's quote lands first and closes the sale on price alone. Undifferentiated leads that don't separate standard drivers from high-risk, non-standard, or SR-22 cases waste calls quoting coverage your agency can't actually place, and generic traffic that hasn't nailed down vehicle count or renewal timing burns producer time before the pitch even starts.",
      "Every auto insurance lead we deliver is filtered on the fields that actually predict a bind — vehicle count, driving record, and liability-only versus full coverage intent — and routed fast enough to reach the driver while they're still comparing, not after they've bound elsewhere. Each one runs through real-time fraud detection, identity verification, consent certification, and TCPA/DNC compliance screening before it's ever sent. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by vehicle count, driving record, and liability-only versus full coverage intent",
      "Standard and non-standard/high-risk driver segments available, so producers aren't quoting outside your carrier appointments",
      "Exclusive delivery — never resold to a competing agency chasing the same quote request",
      "Real-time and live warm transfer delivery so your team reaches the driver before a cheaper quote wins the call",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect agencies and producers with drivers actively requesting auto insurance quotes — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Auto Insurance Customer", detail: "We qualify by vehicle and driver count, driving record, current carrier and renewal timing, and liability-only versus full coverage intent." },
      { title: "Capture & Screen in Real Time", detail: "Every quote request is screened for fraud and real intent the moment it's captured, before it's counted as a lead." },
      { title: "Choose Your Delivery", detail: "Take it as a web-form lead, a live warm transfer with the driver already on the phone, or a routed inbound call — critical in a category where speed wins." },
      { title: "Scale With Renewal Cycles", detail: "Volume flexes with policy renewal timing and non-standard or high-risk demand spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Auto Insurance Leads",
    whoBenefitsSubheading: "From independent agents to non-standard specialty writers, here's who buys auto insurance leads from Eilite.",
    whoBenefits: [
      { tag: "Independent Agents", icon: UserCheck, title: "Independent Auto Insurance Agents", detail: "Agents building a book of standard auto business within their licensed states." },
      { tag: "Agencies", icon: Building2, title: "Multi-Carrier Auto Insurance Agencies", detail: "Brokerages comparing rates across carriers to place drivers with the best fit on price and coverage." },
      { tag: "Captive Agents", icon: ShieldCheck, title: "Captive Carrier Agents", detail: "Agents appointed to a single carrier filling their pipeline with prospects matched to that carrier's rating." },
      { tag: "Non-Standard Writers", icon: Car, title: "Non-Standard & High-Risk Specialty Writers", detail: "Agencies and MGAs writing SR-22, high-risk, and non-standard policies that standard carriers decline." },
    ],
    faqs: [
      { q: "What qualification criteria are used for auto insurance leads?", a: "Leads are filtered on vehicle and driver count, driving record and claims history, current carrier and renewal timing, and whether the shopper wants liability-only or full coverage, so producers know exactly what they're quoting before they dial." },
      { q: "Are auto insurance leads exclusive to my agency?", a: "Yes. Every lead is sold once, to a single agency or producer — never resold or shared with a competitor chasing the same driver." },
      { q: "Can I target specific states or licensed territories?", a: "Yes. Campaigns are built around the states you're licensed and appointed in, including non-standard or high-risk segments if your agency writes them." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as drivers submit — critical in a category where the first agent to call usually wins. Live warm transfers are also available for agencies that want a driver already on the phone." },
      { q: "How is lead compliance verified?", a: "Every lead is screened against the TCPA Litigator List and DNC.com before delivery, in addition to identity verification and consent certification, so you're never calling a number that puts your agency at risk." },
    ],
  },
  {
    slug: "home-insurance-lead-generation",
    label: "Home Insurance",
    category: "Insurance",
    keywords: ["home-insurance"],
    tagline: "Home Insurance Leads",
    highlight: "Filtered by the Property, Not Just the ZIP Code",
    subheadline:
      "Reach homeowners shopping coverage around a mortgage closing, refinance, or a non-renewal notice from their current carrier — filtered by property type, dwelling value, and coverage need before your producers ever pick up the phone.",
    metaDescription:
      "Reach homeowners shopping coverage around a mortgage closing, refinance, or non-renewal notice, filtered by property type and dwelling value.",
    searchChips: ["homeowners insurance quote", "home insurance after non-renewal", "cheapest home insurance company near me"],
    demoIndustry: "Home Insurance",
    overviewEyebrow: "The Problem",
    overviewHeading: "Home insurance demand tracks mortgage activity and carrier pull-back, not just interest",
    overviewParagraphs: [
      "Home insurance leads correlate heavily with events outside the homeowner's control — a mortgage closing, a refinance, or a non-renewal notice from a carrier exiting a high-risk market — which means shopping urgency and placement difficulty swing wildly from lead to lead. A lead that doesn't capture property type, dwelling value, and catastrophe exposure forces producers to discover mid-call that the home sits in a wildfire or flood zone their standard carriers won't touch, wasting time that could have gone to a placeable prospect.",
      "Every home insurance lead we deliver is filtered on the details that determine both urgency and placement — property type, dwelling coverage need, and the mortgage or non-renewal trigger behind the shop — before it's ever sent. Each one runs through real-time fraud detection, identity verification, consent certification, and TCPA/DNC compliance screening first. Never aggregator leftovers, never resold lists.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by property type and dwelling coverage need, so producers aren't quoting homes they can't underwrite",
      "Flagged for mortgage, refinance, or carrier non-renewal triggers, so you can prioritize the most time-sensitive shoppers first",
      "Exclusive delivery — never resold to a competing agency or carrier quoting the same homeowner",
      "Live warm transfers available for agents who want a homeowner already on the line, ready to talk coverage",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect agencies and producers with homeowners shopping coverage — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Home Insurance Customer", detail: "We qualify by property type, estimated dwelling value, and the mortgage, refinance, or non-renewal trigger behind the shop." },
      { title: "Capture & Screen in Real Time", detail: "Every inquiry is screened for fraud, documented consent, and real intent before it's counted as a lead." },
      { title: "Choose Your Delivery", detail: "Take it as a web-form lead, a live warm transfer with the homeowner already on the phone, or a routed inbound call — whatever fits your producers." },
      { title: "Scale With Non-Renewal Spikes", detail: "Volume flexes with mortgage and refinance activity plus carrier non-renewal or storm-driven surges in high-risk markets." },
    ],
    whoBenefitsHeading: "Who Benefits From Home Insurance Leads",
    whoBenefitsSubheading: "From independent agents to excess-and-surplus specialists, here's who buys home insurance leads from Eilite.",
    whoBenefits: [
      { tag: "Independent Agents", icon: UserCheck, title: "Independent Home Insurance Agents", detail: "Agents building a book of homeowners policies within their licensed states and service areas." },
      { tag: "Agencies", icon: Building2, title: "Multi-Carrier Home Insurance Agencies", detail: "Brokerages comparing carriers to place homes standard markets are pulling back from." },
      { tag: "E&S Specialists", icon: ShieldCheck, title: "Excess & Surplus Lines Specialists", detail: "Agencies placing catastrophe-exposed and high-value homes that admitted carriers won't write." },
      { tag: "Mortgage Partners", icon: Home, title: "Mortgage & Title Partners", detail: "Lenders and title companies connecting homebuyers to coverage at the point of closing." },
    ],
    faqs: [
      { q: "What qualification criteria are used for home insurance leads?", a: "Leads are filtered on property type, estimated dwelling value or replacement cost, and the shopping trigger — mortgage closing, refinance, or a carrier non-renewal notice — so producers can prioritize and quote accurately from the first call." },
      { q: "Are home insurance leads exclusive to my agency?", a: "Yes. Every lead is sold once, to a single agency or producer — never resold or shared with a competitor quoting the same homeowner." },
      { q: "Can I target specific states or catastrophe-exposed markets?", a: "Yes. Campaigns are built around the states and property types you're licensed and equipped to write, including whether you have excess and surplus lines access for high-risk zones." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as homeowners submit. Live warm transfers are also available if you'd rather have a homeowner already engaged and ready to discuss coverage." },
      { q: "How is lead compliance verified?", a: "Every lead is screened against the TCPA Litigator List and DNC.com before delivery, in addition to identity verification and consent certification, so you're never calling a number that puts your agency at risk." },
    ],
  },
];
