import { Scale, Building2, TrendingUp, Handshake, Gem, Landmark, Rocket, Car, Truck, ShieldAlert, Calendar, Gavel } from "lucide-react";
import type { SolutionVertical } from "./types";

export const legalSolutions: SolutionVertical[] = [
  {
    slug: "personal-injury-lead-generation",
    label: "Personal Injury",
    category: "Legal",
    keywords: ["personal-injury", "personal injury"],
    tagline: "More Signed Cases,",
    highlight: "Not More Shared Leads",
    subheadline:
      "Get exclusive personal injury case leads and live warm transfers from claimants actively searching for representation — screened for real contact info, injury details, and genuine intent before they ever reach your intake team.",
    searchChips: ["personal injury lawyer near me", "do I have a case after my accident", "free injury case consultation"],
    demoIndustry: "Personal Injury",
    overviewEyebrow: "The Problem",
    overviewHeading: "Personal injury is the most competitive practice area to buy leads in",
    overviewParagraphs: [
      "Personal injury draws more advertisers, more bid competition, and more resold contact lists than almost any other legal vertical — which means the same claimant's name and phone number often lands in three or four firms' intake queues at once, driving up cost-per-case while shrinking the odds any single firm actually signs the client. Add in leads with no real injury, bad phone numbers, or claims outside your firm's practical case value, and a lot of PI marketing budget goes toward intake staff chasing dead ends instead of qualified prospects.",
      "Every personal injury lead and warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists or aggregator leftovers — then screened for real contact information, genuine injury details, and case intent before it reaches your firm. Given how heavily regulated legal marketing is, TCPA and DNC compliance is built into every step of that pipeline, not bolted on afterward.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by injury type and case value — auto accidents, slip and fall, premises liability, and other injury claims",
      "Exclusive delivery — every lead and transfer sold once, never resold to a competing firm bidding the same case",
      "Live warm transfers for firms that want a screened claimant already on the phone, ready to talk to intake",
      "State and jurisdiction targeting so you're only paying for cases that fall inside your firm's practice footprint",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect personal injury firms with claimants actively searching for representation — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Personal Injury Case", detail: "We qualify by injury type, case value threshold, liability clarity, and the states or jurisdictions your firm is licensed and actively taking cases in." },
      { title: "Capture & Screen in Real Time", detail: "Claimant interest is captured on owned pages or vetted publisher sites, then screened for fraud, real injury details, and genuine intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Take standard case inquiries as web-form leads, or take live warm transfers with a screened claimant already on the phone for firms that want to close before the claimant calls a competitor." },
      { title: "Scale With Your Intake Capacity", detail: "Volume flexes up or down with your firm's intake bandwidth and case-value targets, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Personal Injury Leads",
    whoBenefitsSubheading: "From solo practices to high-volume contingency firms, here's who buys personal injury leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Scale, title: "Solo & Small PI Firms", detail: "Independent attorneys and small practices filling their caseload with claimants in a defined jurisdiction." },
      { tag: "Multi-Office Firms", icon: Building2, title: "Multi-Attorney & Multi-Office Firms", detail: "Firms routing case volume across multiple attorneys, offices, or intake teams in different markets." },
      { tag: "High-Volume Firms", icon: TrendingUp, title: "High-Volume Contingency Firms", detail: "Firms built to intake and sign a high number of cases per month and staffed for rapid follow-up." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route cases outside their own capacity or case-value focus to partner firms." },
    ],
    faqs: [
      { q: "What types of personal injury leads can I buy?", a: "Auto accidents, slip and fall, premises liability, dog bites, and other general injury claims — filtered by injury severity and case type so you're not paying for claims below your firm's minimum case value." },
      { q: "Are personal injury leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold into a shared pool or passed to a competing firm bidding the same claimant." },
      { q: "Can I target specific states or jurisdictions?", a: "Yes. Campaigns are built around the states and jurisdictions you're licensed and actively taking cases in, so delivery matches your firm's actual footprint." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as claimants submit. Live warm transfers connect your intake team directly with a screened claimant already on the phone, which matters given how quickly PI prospects call other firms." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
  {
    slug: "divorce-lead-generation",
    label: "Divorce & Family Law",
    category: "Legal",
    keywords: ["divorce", "family law"],
    tagline: "Case Leads That Match",
    highlight: "The Cases You Actually Want",
    subheadline:
      "Get exclusive divorce and family law case leads and live warm transfers — filtered by case complexity, from simple uncontested filings to contested and high-asset matters — delivered while the prospect is still deciding who to call.",
    searchChips: ["divorce lawyer near me", "how much does a divorce attorney cost", "child custody lawyer consultation"],
    demoIndustry: "Divorce & Family Law",
    overviewEyebrow: "The Problem",
    overviewHeading: "Not every divorce lead is worth the same to your firm",
    overviewParagraphs: [
      "Divorce and family law leads span an enormous range — a simple, uncontested filing with no real assets or custody disputes sits at one end, and a contested, high-asset divorce with custody litigation and complex property division sits at the other, yet many lead providers price and deliver both identically. A firm built around higher-value contested work ends up paying for uncontested inquiries it can't profitably serve, while a volume-focused firm overpays for complex cases it isn't staffed to handle.",
      "Every divorce and family law lead or warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists — and screened for case type, contested versus uncontested status, and genuine intent before delivery, so the leads reaching your intake team actually match the cases your firm wants. TCPA and DNC compliance is verified on every lead, given how closely legal marketing in this space is regulated.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by case type — uncontested filings, contested divorce, custody disputes, and high-asset matters",
      "Exclusive delivery — never resold to another family law firm competing in your market",
      "Live warm transfers for firms that want a prospect already on the phone before intake picks up",
      "State and jurisdiction targeting so cases land inside the counties and courts you actually practice in",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect family law firms with prospects ready to move forward — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Family Law Case", detail: "We qualify by case type — uncontested or contested divorce, custody, or high-asset matters — plus the states and counties you practice in." },
      { title: "Capture & Screen in Real Time", detail: "Prospect interest is captured on owned pages or vetted publisher sites, then screened for fraud and genuine intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard filings deliver as web-form leads, while live warm transfers connect you with a prospect already on the phone — useful in a category where people often call more than one firm at once." },
      { title: "Scale With Filing Season", detail: "Family law inquiries spike after the holidays and into January; volume flexes with that seasonal pattern without a new contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Divorce & Family Law Leads",
    whoBenefitsSubheading: "From solo practitioners to high-asset divorce specialists, here's who buys family law leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Scale, title: "Solo & Small Family Law Practices", detail: "Independent attorneys handling a full range of divorce and custody matters in a defined jurisdiction." },
      { tag: "Multi-Attorney Firms", icon: Building2, title: "Multi-Attorney Family Law Firms", detail: "Firms routing volume across attorneys who specialize in custody, support, or high-asset division." },
      { tag: "High-Asset Specialists", icon: Gem, title: "High-Asset & Contested Divorce Specialists", detail: "Firms focused on complex property division and litigated custody disputes worth the added intake time." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route contested or out-of-scope matters to partner firms better positioned to handle them." },
    ],
    faqs: [
      { q: "What types of divorce and family law leads can I buy?", a: "Uncontested and contested divorce, child custody, spousal support, and high-asset divorce leads — filtered by case complexity so you're not paying the same rate for a simple filing and a contested, high-asset matter." },
      { q: "Are divorce leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold or shared with a competing family law practice in your area." },
      { q: "Can I target specific states or counties?", a: "Yes. Campaigns are built around the states and counties you practice in, since family law procedure and court systems vary significantly by jurisdiction." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as prospects submit. Live warm transfers are available for firms that want a screened prospect already on the phone, which helps in a category where callers often reach out to more than one firm at once." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
  {
    slug: "mass-tort-lead-generation",
    label: "Mass Tort",
    category: "Legal",
    keywords: ["mass-tort", "mass tort"],
    tagline: "Case Leads That Actually Match",
    highlight: "Your Docket's Criteria",
    subheadline:
      "Get exclusive mass tort case leads screened against your specific docket's exposure, injury, and timing criteria — plus live warm transfers for firms that want a qualified claimant on the phone before intake takes over.",
    searchChips: ["do I qualify for a lawsuit", "class action lawsuit eligibility", "free case review lawsuit"],
    demoIndustry: "Mass Tort",
    overviewEyebrow: "The Problem",
    overviewHeading: "An off-criteria mass tort lead is worthless, not just low-quality",
    overviewParagraphs: [
      "Mass tort intake lives or dies on strict case-criteria fit — a specific drug or product exposure, a specific diagnosis or injury type, and a timing window that lines up with the docket. A lead that doesn't match those criteria isn't a discount lead, it's a dead one, and volume-focused vendors that relabel a general injury or legal-interest pool for whatever docket a firm is currently buying produce exactly that outcome: intake staff spending hours screening claimants who were never going to qualify.",
      "Every mass tort lead we deliver is built around your docket's actual exposure, diagnosis, and timing criteria before it's ever generated — sourced from owned, docket-specific landing pages or a small set of vetted publishers, never a repurposed general-injury pool — and verified for real contact info and documented consent before delivery. TCPA and DNC compliance is checked on every lead, which matters given the scale and scrutiny mass tort campaigns typically draw.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads screened against your docket's specific exposure, product use, diagnosis, and timing criteria",
      "Exclusive delivery — never syndicated across multiple firms buying the same docket",
      "Live warm transfers for firms that want a pre-qualified claimant already on the phone, not just a form submission",
      "State and jurisdiction targeting to match your firm's filing venues and licensing footprint",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect mass tort firms with claimants who match your docket's criteria — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Docket's Exact Criteria", detail: "We qualify by specific exposure or product use, diagnosis or injury type, timing window, and the states or filing venues your docket requires." },
      { title: "Capture & Screen in Real Time", detail: "Claimant interest is captured on docket-specific pages or vetted publisher sites, then screened against your exact criteria before it counts as a lead — not relabeled from a general injury pool." },
      { title: "Choose Your Delivery", detail: "Because an off-criteria lead is worthless in mass tort, every delivery type — web-form leads or live warm transfers with a pre-qualified claimant — passes the same strict screening first." },
      { title: "Scale With Docket Volume", detail: "Volume ramps to match filing deadlines, new docket developments, or MDL milestones, and pulls back as a docket matures." },
    ],
    whoBenefitsHeading: "Who Benefits From Mass Tort Leads",
    whoBenefitsSubheading: "From national mass tort firms to firms entering a fresh docket, here's who buys mass tort leads from Eilite.",
    whoBenefits: [
      { tag: "National Firms", icon: Landmark, title: "National Mass Tort Firms", detail: "Firms running large-scale dockets that need consistent, criteria-matched claimant volume across multiple states." },
      { tag: "Regional Firms", icon: Building2, title: "Regional Firms Filing Into National Dockets", detail: "Firms sourcing docket-specific claimants locally before referring or co-counseling into a larger MDL." },
      { tag: "New Docket Entrants", icon: Rocket, title: "Firms Ramping Up On Emerging Dockets", detail: "Firms moving fast to build volume on a newly certified or fast-moving docket before intake windows tighten." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route qualified claimants to firms with the case inventory or MDL leadership role to handle them." },
    ],
    faqs: [
      { q: "How are mass tort leads qualified against my docket's criteria?", a: "Leads are screened for the specific exposure or product use, diagnosis or injury type, and timing window your docket requires before they're ever delivered, rather than pulled from a general injury or legal-interest pool and relabeled." },
      { q: "Are mass tort leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never syndicated across multiple buyers working the same docket." },
      { q: "Can I target specific states or filing jurisdictions?", a: "Yes. Campaigns are built around the states and jurisdictions relevant to your docket and your firm's filing venues." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as claimants submit. Live warm transfers connect your intake team with a claimant already screened against your docket's criteria and on the phone, which shortens the path to a signed retainer on a newer or fast-moving docket." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's delivered — critical given the scale and regulatory scrutiny mass tort advertising attracts." },
    ],
  },
  {
    slug: "car-accident-lead-generation",
    label: "Car Accident (MVA)",
    category: "Legal",
    keywords: ["car-accident", "auto-accident"],
    tagline: "Screened Crash Leads,",
    highlight: "Not Fender-Bender Filler",
    subheadline:
      "Get exclusive car accident and motor vehicle accident case leads and live warm transfers — screened for fault clarity and injury severity — delivered while the claimant is still deciding which firm to call.",
    searchChips: ["car accident lawyer near me", "should I get a lawyer after a car accident", "free car accident case review"],
    demoIndustry: "Car Accident (MVA)",
    overviewEyebrow: "The Problem",
    overviewHeading: "Not every car accident lead is worth the same call",
    overviewParagraphs: [
      "Car accident leads range from minor, disputed-fault fender-benders to catastrophic, clear-liability crashes with real case value — and a provider that doesn't screen for fault clarity and injury severity before delivery hands your intake team the same volume of low-value claims as high-value ones. Layer on how fast MVA claimants call multiple firms after a crash, and slow or unscreened delivery means you're often the third or fourth call, not the first.",
      "Every car accident lead and warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists — and screened for fault clarity, injury severity, and genuine contact info before it reaches your firm. TCPA and DNC compliance is verified on every lead, given how tightly legal advertising in this space is regulated.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads screened for fault clarity and injury severity, so you're not paying full price for disputed-liability fender-benders",
      "Exclusive delivery — every lead and transfer sold once, never resold to a competing firm in your market",
      "Live warm transfers for firms that want a screened claimant on the phone in the critical hours after a crash",
      "State and jurisdiction targeting to match the venues and comparative-fault rules where you actually practice",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect car accident firms with claimants in the critical hours after a crash — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Car Accident Case", detail: "We qualify by fault clarity, injury severity, case value threshold, and the states you practice in given how much comparative-fault rules vary." },
      { title: "Capture & Screen in Real Time", detail: "Claimant interest is captured moments after a crash and screened for fraud, fault clarity, and genuine injury before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Because MVA claimants call multiple firms within hours of a crash, live warm transfers connect you while they're still on the phone — standard cases still deliver as real-time web-form leads." },
      { title: "Scale With Demand", detail: "Volume flexes with seasonal spikes like winter weather and holiday travel, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Car Accident Leads",
    whoBenefitsSubheading: "From solo practices to firms handling catastrophic crashes, here's who buys car accident leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Car, title: "Solo & Small Auto Accident Firms", detail: "Independent attorneys building a caseload of car accident claims in a defined service area." },
      { tag: "Multi-Office Firms", icon: Building2, title: "Multi-Attorney & Multi-Office Firms", detail: "Firms routing crash-claim volume across offices or intake teams in different markets." },
      { tag: "Catastrophic & Commercial Injury Firms", icon: Truck, title: "Catastrophic & Commercial Vehicle Injury Firms", detail: "Firms focused on high-value crashes involving commercial trucks, rideshare vehicles, or severe injury." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route crash claims outside their own capacity or case-value focus to partner firms." },
    ],
    faqs: [
      { q: "What types of car accident leads can I buy?", a: "Single-vehicle, multi-vehicle, rideshare, and commercial truck collision leads — screened for fault clarity and injury severity so you're not paying the same rate for a minor fender-bender and a clear-liability injury crash." },
      { q: "Are car accident leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold or shared with a competing firm working the same claimant." },
      { q: "Can I target specific states or jurisdictions?", a: "Yes. Campaigns are built around the states you practice in, which matters given how much comparative-fault and liability rules vary state to state." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as claimants submit. Live warm transfers connect you directly with a screened claimant already on the phone, which matters most in the hours right after a crash when claimants are calling several firms at once." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
  {
    slug: "workers-comp-lead-generation",
    label: "Workers' Compensation",
    category: "Legal",
    keywords: ["workers-comp", "workers compensation"],
    tagline: "Injured Worker Leads,",
    highlight: "Screened and Ready to Talk",
    subheadline:
      "Get exclusive workers' compensation case leads and live warm transfers from injured workers actively seeking representation — screened for state eligibility and handled with the retaliation-sensitive intake this practice area requires.",
    searchChips: ["workers comp lawyer near me", "can my employer fire me for filing workers comp", "workplace injury lawyer consultation"],
    demoIndustry: "Workers' Compensation",
    overviewEyebrow: "The Problem",
    overviewHeading: "Workers' comp eligibility and intake are more complicated than standard PI",
    overviewParagraphs: [
      "Workers' compensation eligibility rules differ meaningfully from state to state — coverage thresholds, filing deadlines, and what counts as a compensable injury all vary — so a lead that's a strong fit in one state may not even qualify in another. On top of that, injured workers calling about a potential claim are often anxious about employer retaliation and confused about the process, which means intake that doesn't address those concerns directly loses prospects who were otherwise ready to sign.",
      "Every workers' comp lead and warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists — and screened against your state's eligibility rules and genuine claimant intent before delivery. TCPA and DNC compliance is checked on every submission, given how closely legal advertising is regulated in this space.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads screened against state-specific eligibility rules, so you're not paying for claims that don't qualify in your jurisdiction",
      "Exclusive delivery — never resold to a competing firm in your market",
      "Live warm transfers for firms that want an injured worker already on the phone, ready for intake",
      "State and jurisdiction targeting to match the specific states you're licensed and practicing in",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect workers' comp firms with injured workers seeking representation — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Workers' Comp Case", detail: "We qualify by injury type, employer industry, filing timeline, and the state-specific eligibility rules your firm practices under." },
      { title: "Capture & Screen in Real Time", detail: "Worker interest is captured on owned pages or vetted publisher sites, then screened for fraud, state eligibility, and genuine intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard claims deliver as web-form leads; live warm transfers connect an injured worker directly to intake for time-sensitive matters like an approaching filing deadline or retaliation concern." },
      { title: "Scale With Demand", detail: "Volume flexes with injury patterns in industries like construction and warehousing, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Workers' Compensation Leads",
    whoBenefitsSubheading: "From solo practices to firms focused on denied claims, here's who buys workers' comp leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Scale, title: "Solo & Small Workers' Comp Practices", detail: "Independent attorneys building a caseload of workplace injury claims in a defined jurisdiction." },
      { tag: "Multi-Attorney Firms", icon: Building2, title: "Multi-Attorney Firms", detail: "Firms routing injured-worker volume across attorneys or offices handling different industries or claim types." },
      { tag: "Denied Claims Specialists", icon: ShieldAlert, title: "Denied Claims & Appeals Specialists", detail: "Firms focused on workers whose initial claims were denied and need representation through appeal." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route out-of-state or out-of-scope claims to partner firms licensed to handle them." },
    ],
    faqs: [
      { q: "What types of workers' comp leads can I buy?", a: "Workplace injury, repetitive stress, denied claim, and employer-retaliation-related leads — screened against your state's specific eligibility rules and filing deadlines before delivery." },
      { q: "Are workers' comp leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold or shared with a competing firm in your area." },
      { q: "Can I target specific states?", a: "Yes. Campaigns are built around the specific states you practice in, since workers' comp eligibility rules and benefit structures vary significantly state to state." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as injured workers submit. Live warm transfers are available for firms that want a claimant already on the phone, which can matter when a worker is deciding quickly amid retaliation concerns or an approaching filing deadline." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
  {
    slug: "bankruptcy-lead-generation",
    label: "Bankruptcy",
    category: "Legal",
    keywords: ["bankruptcy"],
    tagline: "Filing-Ready Leads,",
    highlight: "Split by Chapter",
    subheadline:
      "Get exclusive bankruptcy case leads and live warm transfers — screened for Chapter 7 versus Chapter 13 qualification and genuine filing intent — delivered while the prospect's financial situation is still current.",
    searchChips: ["bankruptcy lawyer near me", "chapter 7 vs chapter 13 which is right for me", "free bankruptcy consultation"],
    demoIndustry: "Bankruptcy",
    overviewEyebrow: "The Problem",
    overviewHeading: "Chapter 7 and Chapter 13 leads need different qualification, not the same intake",
    overviewParagraphs: [
      "Bankruptcy leads split sharply along Chapter 7 versus Chapter 13 lines — Chapter 7 eligibility hinges on a means test against state median income, while Chapter 13 involves a longer intake conversation around income documentation and a repayment plan — and a provider that doesn't capture household income and debt details up front leaves your staff to sort out which chapter a prospect even qualifies for. Because bankruptcy matters typically run on flat or modest fees rather than contingency, a firm also needs a tighter cost-per-lead ceiling than in other practice areas to stay profitable.",
      "Every bankruptcy lead and warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists — and screened for debt level, filing intent, and genuine contact information before delivery, so your intake team knows which chapter a prospect is likely headed toward before the first call. TCPA and DNC compliance is verified on every lead.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads screened for debt level and filing circumstances relevant to Chapter 7 versus Chapter 13 qualification",
      "Exclusive delivery — never resold to a competing firm in your market",
      "Live warm transfers for firms that want a prospect already on the phone and ready for intake",
      "State targeting so means-test and income comparisons reflect the state median your firm actually files under",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect bankruptcy firms with prospects ready to file — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Bankruptcy Case", detail: "We qualify by Chapter 7 versus Chapter 13 fit, debt level, household income against your state's median, and filing timeline." },
      { title: "Capture & Screen in Real Time", detail: "Prospect interest is captured on owned pages or vetted publisher sites, then screened for fraud and genuine filing intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard filings deliver as web-form leads; live warm transfers connect you with a prospect already on the phone for time-sensitive situations like a pending wage garnishment." },
      { title: "Scale With Demand", detail: "Filing interest often rises after the holidays and during economic downturns; volume flexes with that pattern without a new contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Bankruptcy Leads",
    whoBenefitsSubheading: "From solo filers' attorneys to Chapter 13 specialists, here's who buys bankruptcy leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Scale, title: "Solo & Small Bankruptcy Practices", detail: "Independent attorneys handling both Chapter 7 and Chapter 13 filings in a defined jurisdiction." },
      { tag: "Multi-Attorney Firms", icon: Building2, title: "Multi-Attorney Firms", detail: "Firms routing filing volume across attorneys or offices covering different counties or districts." },
      { tag: "Chapter 13 Specialists", icon: Calendar, title: "Chapter 13 Repayment Plan Specialists", detail: "Firms focused on the longer intake and repayment-plan work Chapter 13 filings require." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route prospects outside their chapter focus or district to partner firms." },
    ],
    faqs: [
      { q: "What types of bankruptcy leads can I buy?", a: "Chapter 7 and Chapter 13 filing leads, screened for debt level, household income, and genuine filing intent so your team knows which chapter a prospect is likely to qualify for before the first call." },
      { q: "Are bankruptcy leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold or shared with a competing bankruptcy practice in your area." },
      { q: "Can I target specific states?", a: "Yes. Campaigns are built around the states you practice in, which matters directly for Chapter 7 means-test comparisons against state median income." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as prospects submit. Live warm transfers are available for firms that want a prospect already on the phone, which helps since financial circumstances driving bankruptcy interest — like a pending wage garnishment — can be time-sensitive." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
  {
    slug: "immigration-lead-generation",
    label: "Immigration Law",
    category: "Legal",
    keywords: ["immigration"],
    tagline: "Case-Type Leads That Match",
    highlight: "Your Firm's Practice Focus",
    subheadline:
      "Get exclusive immigration case leads and live warm transfers — filtered by case type, from family-based petitions to asylum and deportation defense — delivered to the firms actually equipped to handle them.",
    searchChips: ["immigration lawyer near me", "green card application lawyer", "deportation defense attorney consultation"],
    demoIndustry: "Immigration Law",
    overviewEyebrow: "The Problem",
    overviewHeading: "Immigration case types vary too widely for one-size-fits-all leads",
    overviewParagraphs: [
      "Family-based petitions, employment visas, asylum claims, and deportation defense each involve different urgency levels, different documentation, and often different language needs — and a lead provider that treats \"immigration\" as a single category delivers case types your firm may not even handle, or misses the urgency of a fast-approaching deportation deadline. Generic legal lead-gen playbooks that skip language access and case-type screening tend to underperform badly in this vertical.",
      "Every immigration lead and warm transfer we deliver is captured on owned, high-intent legal pages or sourced from a small set of vetted publishers — never resold lists — and screened for case type, language preference, and genuine intent before it reaches your firm, so family-based, employment-based, and defense matters route to the firms actually positioned to handle them. TCPA and DNC compliance is verified on every lead.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by case type — family-based petitions, employment visas, asylum claims, and deportation defense",
      "Exclusive delivery — never resold to a competing firm in your market",
      "Live warm transfers for firms that want a screened prospect already on the phone, including urgent deadline-driven matters",
      "Language preference and jurisdiction targeting so leads match your firm's staffing and geographic focus",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect immigration firms with prospects who match your case-type focus — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Immigration Case", detail: "We qualify by case type — family-based, employment-based, asylum, or deportation defense — plus language preference and the jurisdictions you practice in." },
      { title: "Capture & Screen in Real Time", detail: "Prospect interest is captured on owned pages or vetted publisher sites, then screened for fraud, case type, and genuine intent before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard petitions deliver as web-form leads; live warm transfers connect you with a screened prospect already on the phone for urgent, deadline-driven matters like an active deportation case." },
      { title: "Scale With Demand", detail: "Volume flexes with policy changes and filing-deadline driven spikes, without renegotiating a contract." },
    ],
    whoBenefitsHeading: "Who Benefits From Immigration Leads",
    whoBenefitsSubheading: "From solo practices to deportation defense specialists, here's who buys immigration leads from Eilite.",
    whoBenefits: [
      { tag: "Solo Practices", icon: Scale, title: "Solo & Small Immigration Practices", detail: "Independent attorneys handling a range of case types in a defined jurisdiction." },
      { tag: "Multi-Language Firms", icon: Building2, title: "Multi-Attorney & Multi-Language Firms", detail: "Firms routing volume across attorneys and staff who serve specific language communities." },
      { tag: "Deportation Defense Specialists", icon: Gavel, title: "Deportation Defense & Removal Specialists", detail: "Firms focused on urgent, deadline-driven removal proceedings before an immigration judge." },
      { tag: "Referral Networks", icon: Handshake, title: "Referral & Co-Counsel Networks", detail: "Networks that route case types outside their focus — like employment visas or asylum — to partner firms." },
    ],
    faqs: [
      { q: "What types of immigration leads can I buy?", a: "Family-based petitions, employment-based visas, asylum claims, deportation defense, and naturalization leads — filtered by case type so you're only receiving inquiries that match what your firm actually practices." },
      { q: "Are immigration leads exclusive to my firm?", a: "Yes. Every lead and warm transfer is sold once, to a single firm — never resold or shared with a competing immigration practice in your area." },
      { q: "Can I target specific states or language preferences?", a: "Yes. Campaigns can be configured by state, jurisdiction, and language preference, since many immigration prospects specifically search for an attorney who serves their community or speaks their native language." },
      { q: "How fast are leads delivered, and can I get live transfers?", a: "Web-form leads deliver in real time as prospects submit. Live warm transfers are available for firms that want a screened prospect already on the phone, which matters most for urgent, deadline-driven matters like an active deportation case." },
      { q: "How is lead quality and compliance verified?", a: "Every submission is screened against the TCPA Litigator List and DNC.com, run through fraud detection and contact verification, and checked for documented consent before it's ever delivered." },
    ],
  },
];
