import {
  Rocket,
  Building2,
  Layers,
  Handshake,
  Network,
  HardHat,
  Utensils,
  Store,
  PhoneCall,
  Headset,
  Stethoscope,
  Hospital,
  Route,
  Cpu,
  ShoppingCart,
} from "lucide-react";
import type { SolutionVertical } from "./types";

export const softwareSolutions: SolutionVertical[] = [
  {
    slug: "crm-software-leads-exclusive-qualified-b2b-inquiries",
    label: "CRM Software",
    category: "Software & B2B",
    keywords: ["crm"],
    tagline: "Fill Your Demo Calendar,",
    highlight: "Not Your Free-Trial Graveyard",
    subheadline:
      "Get exclusive B2B leads from companies actively evaluating a new CRM — filtered by company size, industry, and current tooling so your reps are demoing real buyers, not tire-kickers.",
    metaDescription:
      "Get exclusive B2B leads from companies actively evaluating a new CRM, filtered by company size, industry, and current tooling.",
    searchChips: ["best CRM for small business", "CRM software comparison", "switch from spreadsheets to CRM"],
    demoIndustry: "CRM Software",
    overviewEyebrow: "The Problem",
    overviewHeading: "The CRM market is crowded, and most inbound leads never touch a paid seat",
    overviewParagraphs: [
      "CRM software is one of the most competitive categories in B2B — dozens of vendors bidding on the same handful of high-value keywords, and the leads that come through are overwhelmingly low-intent free-trial signups from people who spin up an account, never invite a teammate, and churn before a rep ever gets them on the phone. Generic \"request a demo\" forms attract students, competitors doing research, and companies with no budget and no urgency, which means your SDRs spend more time disqualifying than selling.",
      "We fix that by capturing CRM leads through targeted paid and organic channels built around real buying intent, then qualifying every submission against your actual ideal-customer profile — company size, industry vertical, team headcount, and the tool they're currently using or replacing — before it ever reaches you. Qualified leads route in real time into your CRM or as a live warm transfer when a prospect is ready to talk now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by company size, industry, and current CRM or workaround (spreadsheets, another platform)",
      "Exclusive delivery — never resold to a competing CRM vendor",
      "Real-time routing into your CRM or sales workflow the moment a lead is qualified",
      "Live warm transfers available for sales-ready prospects who want to talk immediately",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect CRM providers with businesses actively evaluating new software — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal CRM Customer", detail: "We qualify by company size, industry, team headcount, current CRM or workaround, and who on the buying team holds budget authority." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it ever counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for sales-ready prospects who want to talk now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting and qualification criteria against your actual close rate and CAC as volume grows, so cost per opportunity keeps improving." },
    ],
    whoBenefitsHeading: "Who Benefits From CRM Software Leads",
    whoBenefitsSubheading: "From scrappy SMB platforms to enterprise sales suites, here's who buys CRM software leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: Rocket, title: "SMB-Focused CRM Vendors", detail: "Platforms built for small teams that need volume from businesses still running deals out of spreadsheets or inboxes." },
      { tag: "Enterprise Sales", icon: Building2, title: "Enterprise & Mid-Market CRM Providers", detail: "Sales teams targeting larger accounts that need demos qualified on headcount, seat count, and existing platform before a rep engages." },
      { tag: "Vertical CRM", icon: Layers, title: "Industry-Specific CRM Providers", detail: "Platforms built for a single vertical — real estate, healthcare, legal — that need leads pre-filtered to that exact industry." },
      { tag: "Channel Partners", icon: Handshake, title: "CRM Implementation & Reseller Partners", detail: "Consultants and resellers who need qualified demand to fill their own pipeline of implementation and migration work." },
    ],
    faqs: [
      { q: "How are CRM leads qualified before I get them?", a: "Every lead is screened against your ideal-customer profile — company size, industry, team headcount, and current CRM or manual process — so you're not paying for anonymous free-trial signups that never convert." },
      { q: "Are the leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single CRM provider — never shared with competing vendors bidding for the same deal." },
      { q: "Can I target specific industries or company sizes?", a: "Yes. Campaigns are built around the verticals and company-size bands you actually sell into, whether that's SMB, mid-market, or a specific industry like real estate or healthcare." },
      { q: "How fast are leads delivered and can they integrate with my CRM?", a: "Leads deliver in real time via API, webhook, or direct integration with platforms like Salesforce, HubSpot, or your own pipeline — no manual exports." },
      { q: "How do you verify lead quality?", a: "Every submission runs through fraud and bot detection, real-time contact validation, and manual review before delivery, so you're reaching a real person with real buying intent." },
    ],
  },
  {
    slug: "business-phone-systems-lead-generation",
    label: "Business Phone Systems",
    category: "Software & B2B",
    keywords: ["phone system", "phone systems"],
    tagline: "Reach IT Buyers",
    highlight: "While Their Budget Window Is Still Open",
    subheadline:
      "Get exclusive leads from businesses actively shopping for a new business phone system — filtered by company size, location count, and decision-maker role, delivered while procurement is still active.",
    metaDescription:
      "Get exclusive leads from businesses actively shopping for a new phone system, filtered by company size, location count, and decision-maker role.",
    searchChips: ["best business phone system", "cloud phone system for small business", "multi-location phone system"],
    demoIndustry: "Business Phone Systems",
    overviewEyebrow: "The Problem",
    overviewHeading: "Phone system sales cycles run through IT, not the front desk",
    overviewParagraphs: [
      "Business phone system deals rarely close with the person who fills out the contact form. Real evaluations run through IT directors and operations leaders who have to weigh multi-location rollout, integration with existing hardware, and a budget approval process — and by the time a generic lead reaches your reps, the buying window may already be closing or the contact may not have purchasing authority at all. Vendors waste calls chasing office managers who were just asked to \"look into pricing.\"",
      "We fix that by capturing business phone system leads through targeted campaigns aimed at the actual decision-maker, then qualifying every submission against your ideal-customer profile — company size, number of locations, and current phone provider — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer for prospects ready to talk to sales now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by company size, number of locations, and current phone provider",
      "Targeting built around actual decision-makers, not front-desk gatekeepers",
      "Real-time delivery into your CRM so reps can respond while procurement is active",
      "Live warm transfers for businesses ready to talk pricing and rollout now",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect business phone system providers with companies actively shopping for a new platform — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Phone System Customer", detail: "We qualify by company size, number of locations, current phone provider, and whether the inquiry comes from IT, operations, or a purchasing decision-maker." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for businesses with procurement open now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, sharpening which company sizes and industries convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From Business Phone System Leads",
    whoBenefitsSubheading: "From SMB-focused cloud phone providers to enterprise UCaaS teams, here's who buys business phone system leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: Rocket, title: "SMB-Focused Cloud Phone Providers", detail: "Platforms built for single-location small businesses that need volume from companies replacing an old landline setup." },
      { tag: "Enterprise UCaaS", icon: Building2, title: "Enterprise & Multi-Location UCaaS Teams", detail: "Providers targeting larger rollouts that need leads qualified on location count and integration with existing hardware." },
      { tag: "Vertical Systems", icon: Network, title: "Industry-Specific Phone System Providers", detail: "Platforms built for a specific vertical — healthcare, retail, hospitality — that need leads pre-filtered to that use case." },
      { tag: "Channel Partners", icon: Handshake, title: "Telecom Agents & Reseller Partners", detail: "Master agents and resellers who need qualified demand to fill their own book of business across multiple carriers." },
    ],
    faqs: [
      { q: "How do you make sure leads are from actual decision-makers?", a: "Campaigns and forms are built to capture the role and purchasing authority of the person requesting information, so you're reaching IT directors and operations leaders instead of front-desk staff doing early research." },
      { q: "Are business phone system leads exclusive to me?", a: "Yes. Every lead is sold once, to a single provider — never resold to a competing phone system or VoIP vendor." },
      { q: "Can I target multi-location businesses specifically?", a: "Yes. Campaigns can be filtered by company size, number of locations, and industry so you're only reaching businesses that match your typical deal size." },
      { q: "How fast do leads reach my team, and can they hit our CRM directly?", a: "Leads deliver in real time via API or webhook integration with your CRM, and live warm transfers connect you by phone while the buyer is still evaluating." },
      { q: "How is lead quality verified?", a: "Every submission goes through fraud and bot detection and real-time contact validation before delivery, so your reps are calling a verified business contact, not a duplicate or fake entry." },
    ],
  },
  {
    slug: "payroll-software-lead-generation",
    label: "Payroll Software",
    category: "Software & B2B",
    keywords: ["payroll"],
    tagline: "Talk to Businesses",
    highlight: "Actually Ready to Switch Payroll Providers",
    subheadline:
      "Get exclusive leads from companies actively shopping for payroll software — filtered by employee headcount and current provider so your reps only call businesses worth the conversation.",
    metaDescription:
      "Get exclusive leads from companies actively shopping for payroll software, filtered by employee headcount and current provider.",
    searchChips: ["best payroll software for small business", "switch payroll providers", "payroll software pricing comparison"],
    demoIndustry: "Payroll Software",
    overviewEyebrow: "The Problem",
    overviewHeading: "A payroll lead is only worth a call if the headcount and timing are right",
    overviewParagraphs: [
      "Payroll software has a narrow band of good-fit customers — a five-person company and a five-hundred-person company have nothing in common as buyers, and a business mid-contract with another provider isn't going anywhere for months. Unfiltered leads mix in solopreneurs who will never need a real payroll platform, businesses locked into annual contracts elsewhere, and HR coordinators without budget authority, which burns rep hours on calls that were never going to close.",
      "We fix that by capturing payroll software leads through targeted campaigns, then qualifying every submission against your ideal-customer profile — employee headcount, current payroll provider or process, and decision-maker role — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer when a business is ready to talk switching now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by employee headcount and current payroll provider or manual process",
      "Targeting built around finance and operations decision-makers, not HR administrators alone",
      "Exclusive delivery — never resold to a competing payroll vendor",
      "Live warm transfers for businesses ready to discuss switching immediately",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect payroll software providers with businesses actively evaluating a switch — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Payroll Customer", detail: "We qualify by employee headcount, current payroll provider or manual process, industry, and whether the inquiry has finance or ownership-level authority." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for businesses ready to talk switching now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, narrowing in on the headcount bands that convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From Payroll Software Leads",
    whoBenefitsSubheading: "From SMB payroll platforms to enterprise HR suites, here's who buys payroll software leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: Rocket, title: "SMB-Focused Payroll Vendors", detail: "Platforms built for small businesses that need volume from companies still running payroll manually or on spreadsheets." },
      { tag: "Enterprise HR", icon: Building2, title: "Enterprise & Mid-Market HR Platforms", detail: "Providers targeting larger accounts that need leads qualified on headcount, multi-state compliance needs, and current system." },
      { tag: "Vertical Payroll", icon: HardHat, title: "Industry-Specific Payroll Providers", detail: "Platforms built for a specific vertical — construction certified payroll, restaurant tip reporting — that need leads pre-filtered to that use case." },
      { tag: "Channel Partners", icon: Handshake, title: "Accounting Firms & Payroll Resellers", detail: "Bookkeepers, accountants, and resellers who need qualified demand to fill their own client-referral pipeline." },
    ],
    faqs: [
      { q: "How are payroll leads filtered by company size?", a: "Every lead is qualified by employee headcount and current payroll setup, so you're only reaching businesses that fit the client size your platform is built to serve." },
      { q: "Are payroll software leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single payroll provider — never shared with a competitor bidding on the same business." },
      { q: "Can I target specific industries or company sizes?", a: "Yes. Campaigns are built around your target headcount range and the industries where your platform fits best, whether that's small business, mid-market, or a specific vertical like construction or healthcare." },
      { q: "How fast are leads delivered and can they connect to my CRM?", a: "Leads deliver in real time via API, webhook, or direct CRM integration, so your sales team can follow up while intent is still high." },
      { q: "How do you verify lead quality?", a: "Every submission runs through fraud and bot detection, real-time contact and business validation, and manual review before delivery." },
    ],
  },
  {
    slug: "pos-systems-lead-generation",
    label: "POS Systems",
    category: "Software & B2B",
    keywords: ["pos system", "point of sale"],
    tagline: "Get In Front of Merchants",
    highlight: "Ready to Upgrade Their POS Today",
    subheadline:
      "Get exclusive leads from retailers, restaurants, and service businesses actively shopping for a new point-of-sale system — filtered by industry and hardware needs so your reps aren't guessing at fit.",
    metaDescription:
      "Get exclusive leads from retailers, restaurants, and service businesses shopping for a new POS system, filtered by industry and hardware needs.",
    searchChips: ["best POS system for retail", "restaurant POS system cost", "POS system for small business"],
    demoIndustry: "POS Systems",
    overviewEyebrow: "The Problem",
    overviewHeading: "A retail POS lead and a restaurant POS lead are not the same lead",
    overviewParagraphs: [
      "Point-of-sale demand spans wildly different buyers — a boutique retailer needs inventory tracking, a restaurant needs table management and kitchen display integration, and a service business needs invoicing and appointment booking. Unfiltered POS leads mix all three together along with hardware-only shoppers who just want a card reader, which means reps waste calls pitching the wrong bundle to the wrong business type.",
      "We fix that by capturing POS leads through targeted campaigns segmented by industry, then qualifying every submission against your ideal-customer profile — business type, transaction volume, and whether they need hardware, software, or both — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer for merchants ready to buy now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads segmented by industry — retail, restaurant, or service-based business",
      "Filtered by whether the merchant needs hardware, software, or a full bundle",
      "Exclusive delivery — never resold to a competing POS provider",
      "Live warm transfers for merchants ready to move forward on a purchase now",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect POS providers with merchants actively shopping for a new system — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal POS Customer", detail: "We qualify by business type, transaction volume, current POS or cash-only setup, and whether the merchant needs hardware, software, or both." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for merchants ready to buy now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, sharpening which business types convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From POS System Leads",
    whoBenefitsSubheading: "From SMB point-of-sale platforms to enterprise multi-location systems, here's who buys POS leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: Rocket, title: "SMB-Focused POS Vendors", detail: "Platforms built for single-location merchants that need volume from businesses still running a cash drawer or basic card reader." },
      { tag: "Enterprise POS", icon: Building2, title: "Enterprise & Multi-Location POS Providers", detail: "Providers targeting larger rollouts that need leads qualified on location count and integration with existing back-office systems." },
      { tag: "Vertical POS", icon: Utensils, title: "Industry-Specific POS Providers", detail: "Platforms built for a specific vertical — restaurant, salon, retail boutique — that need leads pre-filtered to that use case." },
      { tag: "Channel Partners", icon: Handshake, title: "POS Hardware Resellers & Channel Partners", detail: "Resellers and integrators who need qualified demand to fill their own book of installs and support contracts." },
    ],
    faqs: [
      { q: "Can I get leads specific to my industry focus, like restaurants or retail?", a: "Yes. Campaigns are segmented by business type — retail, restaurant, or service — so you're only reaching merchants whose needs match your platform." },
      { q: "Are POS system leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single POS provider — never resold to a competitor." },
      { q: "Can I target by transaction volume or business size?", a: "Yes. Leads can be filtered by estimated transaction volume and business size so you're prioritizing merchants that match your ideal deal size." },
      { q: "How fast are leads delivered and can they reach my CRM directly?", a: "Leads deliver in real time via API or webhook integration, so your sales team can respond while the merchant is still comparing options." },
      { q: "How is lead quality verified?", a: "Every submission is screened through fraud and bot detection and real-time business and contact validation before it's delivered to you." },
    ],
  },
  {
    slug: "voip-lead-generation",
    label: "VoIP",
    category: "Software & B2B",
    keywords: ["voip"],
    tagline: "Connect With Businesses",
    highlight: "Actively Comparing VoIP Providers",
    subheadline:
      "Get exclusive leads from businesses shopping for a new VoIP or unified communications solution — filtered by company size and current provider so your sales team calls buyers, not browsers.",
    metaDescription:
      "Get exclusive leads from businesses shopping for a new VoIP or unified communications solution, filtered by company size and current provider.",
    searchChips: ["best VoIP provider for business", "VoIP vs landline cost", "VoIP phone service comparison"],
    demoIndustry: "VoIP",
    overviewEyebrow: "The Problem",
    overviewHeading: "Most VoIP inquiries are spec-shopping, not switching",
    overviewParagraphs: [
      "VoIP is a heavily researched category — businesses comparing call quality, uptime guarantees, and pricing tiers across a dozen open tabs, most of them months away from a real decision. Generic VoIP leads mix serious multi-location businesses ready to switch with solo consultants comparing free tiers, and reps burn hours qualifying before they ever find the accounts with real budget and a real timeline.",
      "We fix that by capturing VoIP leads through targeted campaigns built around active buying signals, then qualifying every submission against your ideal-customer profile — company size, number of users, and current phone or VoIP provider — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer when a business is ready to talk switching now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by company size, user count, and current VoIP or landline provider",
      "Targeting built around businesses with active switching intent, not casual researchers",
      "Exclusive delivery — never resold to a competing VoIP provider",
      "Live warm transfers for businesses ready to discuss plans and pricing immediately",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect VoIP providers with businesses actively comparing platforms — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal VoIP Customer", detail: "We qualify by company size, user count, current VoIP or landline provider, and whether the business has an active contract expiration or switching trigger." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for businesses ready to talk switching now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, narrowing in on the user-count bands that convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From VoIP Leads",
    whoBenefitsSubheading: "From SMB-focused VoIP providers to enterprise unified communications teams, here's who buys VoIP leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: PhoneCall, title: "SMB-Focused VoIP Providers", detail: "Platforms built for small teams that need volume from businesses still running a legacy landline or bare-bones plan." },
      { tag: "Enterprise UC", icon: Building2, title: "Enterprise & Mid-Market UC Providers", detail: "Providers targeting larger accounts that need leads qualified on user count, number of locations, and current contract status." },
      { tag: "Vertical VoIP", icon: Headset, title: "Industry-Specific VoIP Providers", detail: "Platforms built for a specific use case — call centers, healthcare, real estate — that need leads pre-filtered to that vertical." },
      { tag: "Channel Partners", icon: Handshake, title: "Telecom Agents & Master Agent Partners", detail: "Agents and resellers who need qualified demand to fill their own multi-carrier sales pipeline." },
    ],
    faqs: [
      { q: "How do you filter out low-intent researchers from real buyers?", a: "Leads are qualified against signals like company size, user count, and current provider before delivery, so you're reaching businesses with an active reason to switch, not casual comparison shoppers." },
      { q: "Are VoIP leads exclusive to my business?", a: "Yes. Every lead is sold once, to a single VoIP provider — never shared with a competing vendor." },
      { q: "Can I target specific company sizes or industries?", a: "Yes. Campaigns are built around your ideal customer's user count, number of locations, and industry vertical." },
      { q: "How fast are leads delivered and can they integrate with my CRM?", a: "Leads deliver in real time via API, webhook, or direct CRM integration so your team can respond while intent is highest." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud and bot detection, real-time contact validation, and compliance checks before it reaches your team." },
    ],
  },
  {
    slug: "medical-practice-management-software-lead-generation",
    label: "Medical Practice Management Software",
    category: "Software & B2B",
    keywords: ["practice management", "medical software"],
    tagline: "Reach Practice Owners",
    highlight: "Ready to Replace Their Current System",
    subheadline:
      "Get exclusive leads from medical practices actively evaluating new practice management or EHR software — filtered by practice size and specialty, and routed straight to your sales team.",
    metaTitle: "Medical Practice Software Leads",
    metaDescription:
      "Get exclusive leads from medical practices evaluating new practice management or EHR software, filtered by practice size and specialty.",
    searchChips: ["best practice management software", "EHR software for small practice", "medical billing software comparison"],
    demoIndustry: "Medical Practice Management Software",
    overviewEyebrow: "The Problem",
    overviewHeading: "The real buyer is hard to reach, and the sales cycle is long",
    overviewParagraphs: [
      "Practice management software has one of the narrowest buyer pools in B2B — the real decision-maker is usually a practice administrator or physician-owner, not front-office staff, and reaching them means getting past a gatekeeper who was just asked to \"collect some information.\" On top of that, procurement in healthcare is slow: data migration, staff retraining, and compliance review stretch evaluations out for months, so a lead with no real budget or timeline is a dead end dressed up as an opportunity.",
      "We fix that by capturing practice management leads through targeted campaigns aimed at owners and administrators, then qualifying every submission against your ideal-customer profile — practice size, specialty, and current software or paper-based process — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer for practices ready to talk now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by practice size, specialty, and current system or manual process",
      "Targeting built around practice owners and administrators, not front-desk staff",
      "Exclusive delivery — never resold to a competing practice management vendor",
      "Live warm transfers for practices ready to discuss a switch immediately",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect practice management software providers with practices actively evaluating a switch — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Practice Customer", detail: "We qualify by practice size, specialty, current software or paper-based process, and whether the inquiry comes from an owner or administrator with budget authority." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for practices ready to talk now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, sharpening which specialties and practice sizes convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From Practice Management Software Leads",
    whoBenefitsSubheading: "From single-practice-focused platforms to enterprise EHR suites, here's who buys practice management leads from Eilite.",
    whoBenefits: [
      { tag: "Practice Admins", icon: Rocket, title: "Practice Administrator-Focused Vendors", detail: "Platforms built for independent practices that need volume from administrators replacing paper charts or an aging system." },
      { tag: "Enterprise EHR", icon: Hospital, title: "Enterprise & Health System EHR Providers", detail: "Providers targeting multi-physician groups and health systems that need leads qualified on provider count and compliance requirements." },
      { tag: "Specialty Software", icon: Stethoscope, title: "Specialty-Specific Practice Software Providers", detail: "Platforms built for a specific specialty — dental, chiropractic, dermatology — that need leads pre-filtered to that exact practice type." },
      { tag: "Channel Partners", icon: Handshake, title: "Billing Companies & Consultant Partners", detail: "Medical billing services and IT consultants who need qualified demand to fill their own practice-referral pipeline." },
    ],
    faqs: [
      { q: "How do you make sure I'm reaching the actual decision-maker?", a: "Campaigns and qualification questions are built to capture the role of the person inquiring, prioritizing practice owners and administrators over front-office staff doing preliminary research." },
      { q: "Are practice management leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single software vendor — never resold to a competitor pitching the same practice." },
      { q: "Can I target specific specialties or practice sizes?", a: "Yes. Campaigns can be built around specific specialties — like dental, chiropractic, or multi-physician primary care — and the practice size your platform serves best." },
      { q: "How fast are leads delivered and can they reach our CRM?", a: "Leads deliver in real time via API, webhook, or direct CRM integration, so your team can follow up while the practice is still actively evaluating." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud and bot detection and real-time contact and practice validation before delivery, so you're speaking with a verified practice, not a duplicate or fabricated entry." },
    ],
  },
  {
    slug: "fleet-tracking-lead-generation",
    label: "Fleet Tracking",
    category: "Software & B2B",
    keywords: ["fleet tracking", "fleet management"],
    tagline: "Fill Your Pipeline",
    highlight: "With Fleets Worth Tracking",
    subheadline:
      "Get exclusive leads from businesses shopping for GPS fleet tracking or fleet management software — filtered by fleet size so your reps spend time on accounts worth closing.",
    metaDescription:
      "Get exclusive leads from businesses shopping for GPS fleet tracking or fleet management software, filtered by fleet size.",
    searchChips: ["best fleet tracking software", "GPS fleet tracking cost", "fleet management software for small business"],
    demoIndustry: "Fleet Tracking",
    overviewEyebrow: "The Problem",
    overviewHeading: "A 3-vehicle fleet and a 300-vehicle fleet are not the same deal",
    overviewParagraphs: [
      "Fleet tracking demand comes from every size of operation, from a single-owner delivery service with two vans to a regional logistics company running hundreds of trucks — and those are entirely different sales motions with entirely different deal sizes. Unfiltered leads bury serious multi-vehicle accounts under a pile of tire-kickers just pricing out a single tracker, which wastes rep time and skews your cost per qualified opportunity.",
      "We fix that by capturing fleet tracking leads through targeted campaigns, then qualifying every submission against your ideal-customer profile — fleet size, vehicle type, and current tracking solution or lack thereof — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer for fleet operators ready to buy now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by fleet size and vehicle type so you're prioritizing serious accounts",
      "Segmented by industry — logistics, construction, field service, delivery, and more",
      "Exclusive delivery — never resold to a competing fleet tracking provider",
      "Live warm transfers for fleet operators ready to move forward on a purchase now",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect fleet tracking providers with operators actively shopping for a new platform — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Fleet Customer", detail: "We qualify by fleet size, vehicle type, current tracking solution or lack thereof, and the industries — logistics, construction, field service — you actually serve." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for fleet operators ready to buy now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, narrowing in on the fleet-size bands that convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From Fleet Tracking Leads",
    whoBenefitsSubheading: "From small-fleet-focused platforms to enterprise logistics software, here's who buys fleet tracking leads from Eilite.",
    whoBenefits: [
      { tag: "Small Fleets", icon: Rocket, title: "Small-Fleet-Focused Providers", detail: "Platforms built for operators running a handful of vehicles that need volume from businesses tracking mileage on paper or not at all." },
      { tag: "Enterprise Fleets", icon: Building2, title: "Enterprise Fleet Management Platforms", detail: "Providers targeting large fleets that need leads qualified on vehicle count, telematics needs, and multi-depot operations." },
      { tag: "Vertical Fleet", icon: Route, title: "Industry-Specific Fleet Providers", detail: "Platforms built for a specific use case — construction, last-mile delivery, field service dispatch — that need leads pre-filtered to that industry." },
      { tag: "Channel Partners", icon: Handshake, title: "Installer & Reseller Partners", detail: "Hardware installers and resellers who need qualified demand to fill their own installation and support pipeline." },
    ],
    faqs: [
      { q: "How do you filter out tire-kickers from serious fleet accounts?", a: "Every lead is qualified by fleet size, vehicle type, and current tracking setup, so you're prioritizing operators whose fleet size matches your ideal deal size instead of single-vehicle price shoppers." },
      { q: "Are fleet tracking leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single fleet tracking provider — never resold to a competitor." },
      { q: "Can I target specific industries or fleet sizes?", a: "Yes. Campaigns are built around the industries and minimum fleet size that match your typical customer, whether that's construction, logistics, or field service." },
      { q: "How fast are leads delivered and can they reach my CRM directly?", a: "Leads deliver in real time via API or webhook integration, so your team can follow up while the fleet operator is still evaluating providers." },
      { q: "How is lead quality verified?", a: "Every submission is screened through fraud and bot detection and real-time business and contact validation before it's delivered to your team." },
    ],
  },
  {
    slug: "b2b-saas-lead-generation",
    label: "B2B SaaS",
    category: "Software & B2B",
    keywords: ["saas"],
    tagline: "Turn Ad Spend Into",
    highlight: "Sales-Qualified Pipeline, Not Form Fills",
    subheadline:
      "Get exclusive leads from businesses that match your ideal-customer profile and are actively evaluating a solution like yours — qualified before delivery, not just another \"contact us\" submission.",
    metaDescription:
      "Get exclusive leads from businesses that match your ideal-customer profile and are actively evaluating a solution like yours, qualified before delivery.",
    searchChips: ["best software for [use case]", "compare SaaS platforms", "software free trial vs demo"],
    demoIndustry: "B2B SaaS",
    overviewEyebrow: "The Problem",
    overviewHeading: "Generic \"contact us\" leads waste your sales team's time",
    overviewParagraphs: [
      "Most B2B SaaS lead flow comes from generic contact forms and paid campaigns that capture anyone curious enough to click — students, competitors, job seekers, and people with no budget or authority mixed in with real buyers. Without qualification up front, SDRs spend the bulk of their day sorting signal from noise instead of running discovery calls, and marketing's cost per lead climbs while conversion rate stays flat.",
      "We fix that by capturing B2B SaaS leads through targeted paid and organic channels, then qualifying every submission against your actual ideal-customer profile — company size, industry, and current tooling or workaround — before it ever reaches you. Qualified leads route in real time into your CRM or as a live warm transfer when a prospect is ready to talk to sales now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by company size, industry, and current tooling or process being replaced",
      "Exclusive delivery — never resold to a competing software vendor",
      "Real-time routing into your CRM so reps follow up while intent is highest",
      "Live warm transfers available for sales-ready prospects who want to talk now",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect B2B SaaS companies with businesses that match their ideal-customer profile — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal SaaS Customer", detail: "We qualify by company size, industry, current tooling or workaround being replaced, and who on the buying team holds budget authority." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it ever counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request or trial-signup leads, or take live warm transfers for sales-ready prospects who want to talk now, or inbound calls." },
      { title: "Refine as You Scale", detail: "We tune targeting and qualification criteria against your actual close rate and CAC as volume grows, so cost per opportunity keeps improving." },
    ],
    whoBenefitsHeading: "Who Benefits From B2B SaaS Leads",
    whoBenefitsSubheading: "From product-led startups to enterprise sales orgs, here's who buys B2B SaaS leads from Eilite.",
    whoBenefits: [
      { tag: "SMB SaaS", icon: Rocket, title: "SMB-Focused SaaS Vendors", detail: "Growth-stage software companies that need volume from small businesses still solving the problem manually or with a workaround." },
      { tag: "Enterprise Sales", icon: Building2, title: "Enterprise & Mid-Market Sales Teams", detail: "SaaS orgs targeting larger accounts that need demos qualified on company size, seat count, and existing tooling before a rep engages." },
      { tag: "Vertical SaaS", icon: Layers, title: "Vertical SaaS Providers", detail: "Software built for a single industry — construction, legal, healthcare — that needs leads pre-filtered to that exact vertical." },
      { tag: "Channel Partners", icon: Handshake, title: "Partner-Led & Reseller SaaS Orgs", detail: "Companies that sell through implementation partners and resellers and need qualified demand to hand off to their partner network." },
    ],
    faqs: [
      { q: "How is a lead qualified before I receive it?", a: "Every lead is screened against your ideal-customer profile — company size, industry, and the tool or process they're currently using — so you're not paying for anonymous form fills that never book a call." },
      { q: "Are the leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single software provider — never shared with a competitor bidding for the same deal." },
      { q: "Can I target a specific industry, company size, or use case?", a: "Yes. Campaigns are built around the verticals, company sizes, and use cases that match your product's actual fit." },
      { q: "How fast are leads delivered and can they hit our CRM directly?", a: "Leads deliver in real time via API, webhook, or direct CRM integration, so your team can follow up while the prospect is still actively evaluating." },
      { q: "How do you verify lead quality and filter out bots?", a: "Every submission runs through fraud and bot detection, real-time contact validation, and manual review before delivery." },
    ],
  },
  {
    slug: "lead-generation-for-technology-companies",
    label: "Technology Companies",
    category: "Software & B2B",
    keywords: ["technology", "tech company"],
    tagline: "Pipeline Built For",
    highlight: "How Technology Companies Actually Sell",
    subheadline:
      "Get exclusive B2B leads for your technology company — qualified by company size, industry, and current stack, and delivered in real time so your sales and RevOps teams can move fast.",
    metaDescription:
      "Get exclusive B2B leads for your technology company, qualified by company size, industry, and current stack, delivered in real time.",
    searchChips: ["best software solution for [industry]", "enterprise software vendor comparison", "request a demo software"],
    demoIndustry: "Technology Companies",
    overviewEyebrow: "The Problem",
    overviewHeading: "Manual lead handoffs slow down technology sales teams",
    overviewParagraphs: [
      "Technology companies selling into other businesses often deal with leads that arrive as messy spreadsheet exports, delayed CRM syncs, or unverified form fills padded with bot traffic — by the time a rep gets to them, the prospect has already moved on to a competitor who responded faster. Attribution gets muddy across paid channels, and marketing ends up unable to say which campaigns actually produce pipeline versus noise.",
      "We fix that by capturing technology-company leads through targeted paid and organic campaigns, then qualifying every submission against your ideal-customer profile — company size, industry, and current tooling — before it reaches you. Qualified leads route instantly into your CRM via API or webhook, or as a live warm transfer for prospects ready to talk to sales immediately.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by company size, industry, and current stack or vendor being replaced",
      "Real-time delivery via API, webhook, or direct CRM integration — no manual exports",
      "Exclusive delivery — never resold to a competing technology vendor",
      "Live warm transfers available for sales-ready prospects who want to talk now",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect technology companies with businesses actively evaluating a new solution — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Technology Customer", detail: "We qualify by company size, industry, current stack or vendor being replaced, and who on the buying team holds purchasing authority." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it ever counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request leads, or take live warm transfers for sales-ready prospects who want to talk to sales now, or inbound calls." },
      { title: "Refine as You Scale", detail: "We tune targeting and qualification criteria against your actual close rate and CAC as volume grows, so RevOps can trust the pipeline math." },
    ],
    whoBenefitsHeading: "Who Benefits From Technology Company Leads",
    whoBenefitsSubheading: "From SMB-focused tech vendors to enterprise RevOps teams, here's who buys technology leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Vendors", icon: Cpu, title: "SMB-Focused Technology Vendors", detail: "Companies building for small businesses that need volume from prospects still evaluating whether they need a solution like theirs at all." },
      { tag: "Enterprise RevOps", icon: Building2, title: "Enterprise & Mid-Market Sales and RevOps Teams", detail: "Teams targeting larger accounts that need demos qualified on company size, current stack, and buying-committee role before a rep engages." },
      { tag: "Vertical Tech", icon: Layers, title: "Industry-Specific Technology Providers", detail: "Companies building for a single industry that need leads pre-filtered to that exact vertical and use case." },
      { tag: "Channel Partners", icon: Handshake, title: "Channel & Systems Integrator Partners", detail: "Resellers and integrators who need qualified demand to fill their own implementation and referral pipeline." },
    ],
    faqs: [
      { q: "How are leads qualified before delivery?", a: "Every lead is screened against your ideal-customer profile — company size, industry, and current tooling — so your team is working real opportunities instead of unqualified form fills." },
      { q: "Are technology leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single provider — never resold to a competing vendor in the same space." },
      { q: "Can I target specific industries, company sizes, or geographies?", a: "Yes. Campaigns are built around the verticals, company sizes, and regions that match your product's actual fit." },
      { q: "How fast are leads delivered and can they integrate with our CRM?", a: "Leads deliver in real time via API, webhook, or direct CRM integration with platforms like Salesforce or HubSpot, with custom field mapping available." },
      { q: "How do you verify lead quality and prevent bot traffic?", a: "Every submission runs through fraud and bot detection, real-time contact validation, and manual review before it's delivered to your team." },
    ],
  },
  {
    slug: "merchant-account-lead-generation",
    label: "Merchant Account & Payment Processing",
    category: "Software & B2B",
    keywords: ["merchant account", "payment processing"],
    tagline: "Talk to Merchants",
    highlight: "With Volume Worth Your Sales Reps' Time",
    subheadline:
      "Get exclusive leads from businesses shopping for a new merchant account or payment processor — filtered by monthly transaction volume so your reps focus on deals worth closing.",
    metaTitle: "Merchant Account Lead Generation",
    metaDescription:
      "Get exclusive leads from businesses shopping for a new merchant account or payment processor, filtered by monthly transaction volume.",
    searchChips: ["best merchant account provider", "lower credit card processing fees", "switch payment processors"],
    demoIndustry: "Merchant Account & Payment Processing",
    overviewEyebrow: "The Problem",
    overviewHeading: "Not every business shopping for a processor is worth a sales call",
    overviewParagraphs: [
      "Merchant account and payment processing leads span everyone from a solo Etsy seller looking for the cheapest possible rate to a multi-location retailer processing millions a year — and treating them the same wrecks your sales team's economics. Unfiltered leads are dominated by low-volume shoppers chasing the lowest advertised rate who will never generate meaningful residual revenue, while the businesses with real transaction volume get buried in the noise.",
      "We fix that by capturing merchant account leads through targeted campaigns, then qualifying every submission against your ideal-customer profile — monthly transaction volume, business type, and current processor — before it reaches you. Qualified leads route in real time into your CRM or as a live warm transfer for merchants ready to switch now.",
    ],
    benefitsHeading: "What You Get",
    benefits: [
      "Leads filtered by monthly transaction volume so reps focus on deals worth the call",
      "Segmented by business type — retail, restaurant, e-commerce, or service-based",
      "Exclusive delivery — never resold to a competing processor or ISO",
      "Live warm transfers for merchants ready to discuss switching immediately",
    ],
    howItWorksHeading: "How It Works",
    howItWorksSubheading: "We connect merchant account and payment processing providers with businesses actively shopping for a switch — as leads, live warm transfers, or inbound calls.",
    howItWorksSteps: [
      { title: "Define Your Ideal Merchant Customer", detail: "We qualify by monthly transaction volume, business type, current processor, and whether the merchant meets your minimum deal size." },
      { title: "Capture & Qualify in Real Time", detail: "Every submission is screened for fraud and bot activity, then checked against your ICP before it counts as a lead." },
      { title: "Choose Your Delivery", detail: "Standard leads route into your CRM as demo-request submissions, or take live warm transfers for merchants ready to switch now, or inbound calls from active shoppers." },
      { title: "Refine as You Scale", detail: "We tune targeting against your actual close rate and CAC as volume grows, narrowing in on the transaction-volume bands that convert best." },
    ],
    whoBenefitsHeading: "Who Benefits From Merchant Account Leads",
    whoBenefitsSubheading: "From SMB-focused processors to enterprise payment platforms, here's who buys merchant account leads from Eilite.",
    whoBenefits: [
      { tag: "SMB Processors", icon: Store, title: "SMB-Focused Processors & ISOs", detail: "Providers built for low-to-mid volume merchants that need volume from businesses still overpaying a legacy processor." },
      { tag: "Enterprise Payments", icon: Building2, title: "Enterprise & High-Volume Payment Platforms", detail: "Platforms targeting larger merchants that need leads qualified on monthly transaction volume and multi-location processing needs." },
      { tag: "Vertical Payments", icon: ShoppingCart, title: "Industry-Specific Payment Providers", detail: "Processors built for a specific vertical — e-commerce, restaurant, high-risk — that need leads pre-filtered to that exact business type." },
      { tag: "Channel Partners", icon: Handshake, title: "ISO Agents & Reseller Partners", detail: "Independent sales agents and reseller organizations who need qualified demand to fill their own residual-revenue pipeline." },
    ],
    faqs: [
      { q: "How do you filter for merchants with real transaction volume?", a: "Every lead is qualified by estimated monthly processing volume and current provider before delivery, so your reps are prioritizing accounts that match your minimum deal size instead of low-volume rate shoppers." },
      { q: "Are merchant account leads exclusive to my company?", a: "Yes. Every lead is sold once, to a single processor or ISO — never resold to a competing sales organization." },
      { q: "Can I target specific business types or industries?", a: "Yes. Campaigns can be filtered by business type — retail, restaurant, e-commerce, or professional services — and by geography." },
      { q: "How fast are leads delivered and can they connect to my CRM?", a: "Leads deliver in real time via API, webhook, or direct CRM integration, so reps can follow up while the merchant is still actively comparing rates." },
      { q: "How is lead quality verified?", a: "Every submission runs through fraud and bot detection and real-time business and contact validation before delivery, so you're speaking with a verified merchant, not a duplicate or fake entry." },
    ],
  },
];
